// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/canton_oracle_v1/request.proto

package canton_oracle_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamCantonOracleServiceRequestV1 is the request message for the StreamCantonOracleService.
type StreamCantonOracleServiceRequestV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// feeds is the list of feeds to subscribe to (at least one).
	Feeds []*CantonOracleFeedV1 `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	// network selects the Canton network to serve: "mainnet" or "testnet" (required).
	Network       string `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCantonOracleServiceRequestV1) Reset() {
	*x = StreamCantonOracleServiceRequestV1{}
	mi := &file_sdk_stream_canton_oracle_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCantonOracleServiceRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCantonOracleServiceRequestV1) ProtoMessage() {}

func (x *StreamCantonOracleServiceRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCantonOracleServiceRequestV1.ProtoReflect.Descriptor instead.
func (*StreamCantonOracleServiceRequestV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *StreamCantonOracleServiceRequestV1) GetFeeds() []*CantonOracleFeedV1 {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *StreamCantonOracleServiceRequestV1) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

// CantonOracleFeedV1 identifies a single oracle feed by category and id.
type CantonOracleFeedV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// feed_category is the type of data: "crypto" (signed index rates) or "nav" (tokenized-fund NAV).
	FeedCategory string `protobuf:"bytes,1,opt,name=feed_category,json=feedCategory,proto3" json:"feed_category,omitempty"`
	// feed_id is the id of the feed: the index code for "crypto" (e.g. KK_BRR_BTCUSD, KK_RFR_EURUSD)
	// or a DTI for "nav".
	FeedId        string `protobuf:"bytes,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CantonOracleFeedV1) Reset() {
	*x = CantonOracleFeedV1{}
	mi := &file_sdk_stream_canton_oracle_v1_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CantonOracleFeedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CantonOracleFeedV1) ProtoMessage() {}

func (x *CantonOracleFeedV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v1_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CantonOracleFeedV1.ProtoReflect.Descriptor instead.
func (*CantonOracleFeedV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v1_request_proto_rawDescGZIP(), []int{1}
}

func (x *CantonOracleFeedV1) GetFeedCategory() string {
	if x != nil {
		return x.FeedCategory
	}
	return ""
}

func (x *CantonOracleFeedV1) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

var File_sdk_stream_canton_oracle_v1_request_proto protoreflect.FileDescriptor

const file_sdk_stream_canton_oracle_v1_request_proto_rawDesc = "" +
	"\n" +
	")sdk/stream/canton_oracle_v1/request.proto\x12\bkaikosdk\"r\n" +
	"\"StreamCantonOracleServiceRequestV1\x122\n" +
	"\x05feeds\x18\x01 \x03(\v2\x1c.kaikosdk.CantonOracleFeedV1R\x05feeds\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\"R\n" +
	"\x12CantonOracleFeedV1\x12#\n" +
	"\rfeed_category\x18\x01 \x01(\tR\ffeedCategory\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\tR\x06feedIdB\x96\x01\n" +
	"%com.kaiko.sdk.stream.canton_oracle_v1P\x01ZJgithub.com/kaikodata/kaiko-go-sdk/stream/canton_oracle_v1;canton_oracle_v1\xaa\x02\x1eKaikoSdk.Stream.CantonOracleV1b\x06proto3"

var (
	file_sdk_stream_canton_oracle_v1_request_proto_rawDescOnce sync.Once
	file_sdk_stream_canton_oracle_v1_request_proto_rawDescData []byte
)

func file_sdk_stream_canton_oracle_v1_request_proto_rawDescGZIP() []byte {
	file_sdk_stream_canton_oracle_v1_request_proto_rawDescOnce.Do(func() {
		file_sdk_stream_canton_oracle_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_canton_oracle_v1_request_proto_rawDesc), len(file_sdk_stream_canton_oracle_v1_request_proto_rawDesc)))
	})
	return file_sdk_stream_canton_oracle_v1_request_proto_rawDescData
}

var file_sdk_stream_canton_oracle_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_stream_canton_oracle_v1_request_proto_goTypes = []any{
	(*StreamCantonOracleServiceRequestV1)(nil), // 0: kaikosdk.StreamCantonOracleServiceRequestV1
	(*CantonOracleFeedV1)(nil),                 // 1: kaikosdk.CantonOracleFeedV1
}
var file_sdk_stream_canton_oracle_v1_request_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamCantonOracleServiceRequestV1.feeds:type_name -> kaikosdk.CantonOracleFeedV1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_stream_canton_oracle_v1_request_proto_init() }
func file_sdk_stream_canton_oracle_v1_request_proto_init() {
	if File_sdk_stream_canton_oracle_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_canton_oracle_v1_request_proto_rawDesc), len(file_sdk_stream_canton_oracle_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_canton_oracle_v1_request_proto_goTypes,
		DependencyIndexes: file_sdk_stream_canton_oracle_v1_request_proto_depIdxs,
		MessageInfos:      file_sdk_stream_canton_oracle_v1_request_proto_msgTypes,
	}.Build()
	File_sdk_stream_canton_oracle_v1_request_proto = out.File
	file_sdk_stream_canton_oracle_v1_request_proto_goTypes = nil
	file_sdk_stream_canton_oracle_v1_request_proto_depIdxs = nil
}
