// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: sdk/stream/canton_oracle_v1/response.proto

package canton_oracle_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamCantonOracleServiceResponseV1 contains the signed oracle data and the Canton oracle payload.
type StreamCantonOracleServiceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data contains the signed oracle data payload.
	Data *CantonOracleDataV1 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// canton_oracle contains the Canton MasterOracle disclosure used for on-chain proof.
	CantonOracle  *CantonOraclePayloadV1 `protobuf:"bytes,2,opt,name=canton_oracle,json=cantonOracle,proto3" json:"canton_oracle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCantonOracleServiceResponseV1) Reset() {
	*x = StreamCantonOracleServiceResponseV1{}
	mi := &file_sdk_stream_canton_oracle_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCantonOracleServiceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCantonOracleServiceResponseV1) ProtoMessage() {}

func (x *StreamCantonOracleServiceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCantonOracleServiceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamCantonOracleServiceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamCantonOracleServiceResponseV1) GetData() *CantonOracleDataV1 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamCantonOracleServiceResponseV1) GetCantonOracle() *CantonOraclePayloadV1 {
	if x != nil {
		return x.CantonOracle
	}
	return nil
}

// CantonOracleDataV1 contains the signed oracle data information.
type CantonOracleDataV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the id of the feed: the index code for "crypto" (e.g. KK_BRR_BTCUSD), the DTI for "nav".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value is the scaled integer value of the feed. It is unset when the upstream tick carries no
	// price (e.g. the market is closed); such ticks are still emitted and still signed (the value is
	// signed as an empty string), so the signature remains verifiable with the value left unset.
	Value *int64 `protobuf:"varint,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// decimal specifies that the actual value must be equal to value * 10e-{decimal}.
	Decimal int32 `protobuf:"varint,3,opt,name=decimal,proto3" json:"decimal,omitempty"`
	// timestamp is the millisecond UTC epoch of the value.
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// signature is the DER-formatted SECP256K1 signature of the SHA-256 hash of the concatenation of all fields in the data payload.
	Signature     string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CantonOracleDataV1) Reset() {
	*x = CantonOracleDataV1{}
	mi := &file_sdk_stream_canton_oracle_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CantonOracleDataV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CantonOracleDataV1) ProtoMessage() {}

func (x *CantonOracleDataV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CantonOracleDataV1.ProtoReflect.Descriptor instead.
func (*CantonOracleDataV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *CantonOracleDataV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CantonOracleDataV1) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *CantonOracleDataV1) GetDecimal() int32 {
	if x != nil {
		return x.Decimal
	}
	return 0
}

func (x *CantonOracleDataV1) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CantonOracleDataV1) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// CantonOraclePayloadV1 lets the client use the KaikoOraclePull contract and publish their own price.
type CantonOraclePayloadV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// template_id for the Canton contract template.
	TemplateId string `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// contract_id for the Canton contract.
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// synchronizer_id for the Canton synchronizer.
	SynchronizerId string `protobuf:"bytes,3,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// created_event_blob contains the serialized contract event data.
	CreatedEventBlob string `protobuf:"bytes,4,opt,name=created_event_blob,json=createdEventBlob,proto3" json:"created_event_blob,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CantonOraclePayloadV1) Reset() {
	*x = CantonOraclePayloadV1{}
	mi := &file_sdk_stream_canton_oracle_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CantonOraclePayloadV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CantonOraclePayloadV1) ProtoMessage() {}

func (x *CantonOraclePayloadV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CantonOraclePayloadV1.ProtoReflect.Descriptor instead.
func (*CantonOraclePayloadV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *CantonOraclePayloadV1) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CantonOraclePayloadV1) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *CantonOraclePayloadV1) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *CantonOraclePayloadV1) GetCreatedEventBlob() string {
	if x != nil {
		return x.CreatedEventBlob
	}
	return ""
}

var File_sdk_stream_canton_oracle_v1_response_proto protoreflect.FileDescriptor

var file_sdk_stream_canton_oracle_v1_response_proto_rawDesc = string([]byte{
	0x0a, 0x2a, 0x73, 0x64, 0x6b, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x63, 0x61, 0x6e,
	0x74, 0x6f, 0x6e, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x76, 0x31, 0x2f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x61,
	0x69, 0x6b, 0x6f, 0x73, 0x64, 0x6b, 0x22, 0x9d, 0x01, 0x0a, 0x23, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x43, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x30,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b,
	0x61, 0x69, 0x6b, 0x6f, 0x73, 0x64, 0x6b, 0x2e, 0x43, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x4f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x31, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x44, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x73,
	0x64, 0x6b, 0x2e, 0x43, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x31, 0x52, 0x0c, 0x63, 0x61, 0x6e, 0x74, 0x6f, 0x6e,
	0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x74, 0x6f,
	0x6e, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x56, 0x31, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb0, 0x01, 0x0a,
	0x15, 0x43, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x56, 0x31, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x79, 0x6e, 0x63,
	0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x42,
	0x96, 0x01, 0x0a, 0x25, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x5f,
	0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x4a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x63, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x5f, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x5f, 0x76, 0x31, 0x3b, 0x63, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x5f, 0x6f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x5f, 0x76, 0x31, 0xaa, 0x02, 0x1e, 0x4b, 0x61, 0x69, 0x6b, 0x6f, 0x53,
	0x64, 0x6b, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x43, 0x61, 0x6e, 0x74, 0x6f, 0x6e,
	0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sdk_stream_canton_oracle_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_canton_oracle_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_canton_oracle_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_canton_oracle_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_canton_oracle_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_canton_oracle_v1_response_proto_rawDesc), len(file_sdk_stream_canton_oracle_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_canton_oracle_v1_response_proto_rawDescData
}

var file_sdk_stream_canton_oracle_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sdk_stream_canton_oracle_v1_response_proto_goTypes = []any{
	(*StreamCantonOracleServiceResponseV1)(nil), // 0: kaikosdk.StreamCantonOracleServiceResponseV1
	(*CantonOracleDataV1)(nil),                  // 1: kaikosdk.CantonOracleDataV1
	(*CantonOraclePayloadV1)(nil),               // 2: kaikosdk.CantonOraclePayloadV1
}
var file_sdk_stream_canton_oracle_v1_response_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamCantonOracleServiceResponseV1.data:type_name -> kaikosdk.CantonOracleDataV1
	2, // 1: kaikosdk.StreamCantonOracleServiceResponseV1.canton_oracle:type_name -> kaikosdk.CantonOraclePayloadV1
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sdk_stream_canton_oracle_v1_response_proto_init() }
func file_sdk_stream_canton_oracle_v1_response_proto_init() {
	if File_sdk_stream_canton_oracle_v1_response_proto != nil {
		return
	}
	file_sdk_stream_canton_oracle_v1_response_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_canton_oracle_v1_response_proto_rawDesc), len(file_sdk_stream_canton_oracle_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_canton_oracle_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_canton_oracle_v1_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_canton_oracle_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_canton_oracle_v1_response_proto = out.File
	file_sdk_stream_canton_oracle_v1_response_proto_goTypes = nil
	file_sdk_stream_canton_oracle_v1_response_proto_depIdxs = nil
}
