// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: sdk/stream/canton_oracle_v2/response.proto

package canton_oracle_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamCantonOracleServiceResponseV2 is one Pull Oracle V2 signed update for exactly one feed. Only
// `payload` is signed; the routing fields and canonical_hash are not covered by the signature.
type StreamCantonOracleServiceResponseV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network the payload belongs to; echoes the request.
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// feed_category echoes the selector.
	FeedCategory string `protobuf:"bytes,2,opt,name=feed_category,json=feedCategory,proto3" json:"feed_category,omitempty"`
	// feed_id is the feed this message belongs to; equals payload.quote.feedId.
	FeedId string `protobuf:"bytes,3,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	// payload is the oracle-signed payload, reconstructed verbatim and re-canonicalised on-ledger.
	Payload *SignedPayloadV2 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// signature is the hex-encoded DER secp256k1 signature over the sha256 digest of the hex-encoded
	// canonical text of `payload`: codec "v1-quote-concat" when `payload.cost` is unset (free path),
	// "v1-paid-quote-concat" when it is set (paid path, cost + payee).
	Signature string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// canonical_hash is the informative lowercase-hex sha256 digest of the hex-encoded canonical text,
	// for client-side pre-checks only; the verifier always recomputes it on-ledger.
	CanonicalHash string `protobuf:"bytes,6,opt,name=canonical_hash,json=canonicalHash,proto3" json:"canonical_hash,omitempty"`
	// verifier_disclosure is the opaque explicit-disclosure blob (base64) for the verifier contract whose
	// key signed this payload (KaikoQuoteVerifier when free, KaikoPaidQuoteVerifier when paid). The
	// subscriber passes it through unmodified.
	VerifierDisclosure string `protobuf:"bytes,7,opt,name=verifier_disclosure,json=verifierDisclosure,proto3" json:"verifier_disclosure,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamCantonOracleServiceResponseV2) Reset() {
	*x = StreamCantonOracleServiceResponseV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCantonOracleServiceResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCantonOracleServiceResponseV2) ProtoMessage() {}

func (x *StreamCantonOracleServiceResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCantonOracleServiceResponseV2.ProtoReflect.Descriptor instead.
func (*StreamCantonOracleServiceResponseV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamCantonOracleServiceResponseV2) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetFeedCategory() string {
	if x != nil {
		return x.FeedCategory
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetPayload() *SignedPayloadV2 {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamCantonOracleServiceResponseV2) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetCanonicalHash() string {
	if x != nil {
		return x.CanonicalHash
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetVerifierDisclosure() string {
	if x != nil {
		return x.VerifierDisclosure
	}
	return ""
}

// SignedPayloadV2 is the record signed off-chain by the oracle (DataStandard.SignatureVerifierV1).
// The field names mirror the Canton PaidSignedPayload literal the
// PaidQuoteConsumer.VerifyAndRecordQuote choice consumes.
// protolint:disable FIELD_NAMES_LOWER_SNAKE_CASE
// protolint:disable FIELD_NAMES_EXCLUDE_PREPOSITIONS
type SignedPayloadV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// publishedAt is when the oracle produced this payload, as an ISO-8601 UTC timestamp with microsecond
	// precision (e.g. "2026-07-04T13:41:50.852000Z"), injected as a DAML Time.
	PublishedAt string `protobuf:"bytes,1,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	// expiresAt is the validity deadline, as an ISO-8601 UTC timestamp with microsecond precision (e.g.
	// "2026-07-04T13:41:50.852000Z"), injected as a DAML Time; Verify rejects a payload strictly later.
	ExpiresAt string `protobuf:"bytes,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	// cost is the per-call price. Unset means the unpriced (free) case (cost = None), signed with the
	// "v1-quote-concat" codec; when set the payload is signed with the "v1-paid-quote-concat" codec.
	Cost *CostV2 `protobuf:"bytes,3,opt,name=cost,proto3,oneof" json:"cost,omitempty"`
	// quote is the strict typed quote.
	Quote *QuoteV2 `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	// payee is the fee recipient the oracle signs into every paid payload (DataStandard PaidSignedPayload
	// .payee). Set only on the paid path (alongside cost) and covered by the signature; empty on the free
	// path.
	Payee         string `protobuf:"bytes,5,opt,name=payee,proto3" json:"payee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPayloadV2) Reset() {
	*x = SignedPayloadV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPayloadV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPayloadV2) ProtoMessage() {}

func (x *SignedPayloadV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPayloadV2.ProtoReflect.Descriptor instead.
func (*SignedPayloadV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{1}
}

func (x *SignedPayloadV2) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *SignedPayloadV2) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *SignedPayloadV2) GetCost() *CostV2 {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *SignedPayloadV2) GetQuote() *QuoteV2 {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *SignedPayloadV2) GetPayee() string {
	if x != nil {
		return x.Payee
	}
	return ""
}

// CostV2 is the per-call fee and the instrument it is denominated in.
type CostV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fee is the decimal fee, string-encoded to preserve precision.
	Fee string `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	// instrument is the Token Standard instrument the fee is paid in.
	Instrument    *InstrumentIdV2 `protobuf:"bytes,2,opt,name=instrument,proto3" json:"instrument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostV2) Reset() {
	*x = CostV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostV2) ProtoMessage() {}

func (x *CostV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostV2.ProtoReflect.Descriptor instead.
func (*CostV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{2}
}

func (x *CostV2) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *CostV2) GetInstrument() *InstrumentIdV2 {
	if x != nil {
		return x.Instrument
	}
	return nil
}

// InstrumentIdV2 is a Token Standard instrument identifier (Splice.Api.Token.HoldingV1.InstrumentId).
type InstrumentIdV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// admin is the instrument administrator party id (the registry).
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// id is the instrument symbol, e.g. "Amulet" for Canton Coin. MUST NOT contain ';'.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentIdV2) Reset() {
	*x = InstrumentIdV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentIdV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentIdV2) ProtoMessage() {}

func (x *InstrumentIdV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentIdV2.ProtoReflect.Descriptor instead.
func (*InstrumentIdV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{3}
}

func (x *InstrumentIdV2) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

func (x *InstrumentIdV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// QuoteV2 is the strict typed quote payload (DataStandard.QuoteV1.Quote).
// protolint:disable FIELD_NAMES_LOWER_SNAKE_CASE
type QuoteV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// feedId is the stable feed identifier; MUST equal the requested feed_id and MUST NOT contain ';'.
	FeedId string `protobuf:"bytes,1,opt,name=feedId,proto3" json:"feedId,omitempty"`
	// price is the decimal price, string-encoded.
	Price string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	// priceTime is when the producer observed the quote, as an ISO-8601 UTC timestamp with microsecond
	// precision (e.g. "2026-07-04T13:41:50.852000Z"), injected as a DAML Time.
	PriceTime     string `protobuf:"bytes,3,opt,name=priceTime,proto3" json:"priceTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteV2) Reset() {
	*x = QuoteV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteV2) ProtoMessage() {}

func (x *QuoteV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteV2.ProtoReflect.Descriptor instead.
func (*QuoteV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{4}
}

func (x *QuoteV2) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *QuoteV2) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *QuoteV2) GetPriceTime() string {
	if x != nil {
		return x.PriceTime
	}
	return ""
}

var File_sdk_stream_canton_oracle_v2_response_proto protoreflect.FileDescriptor

var file_sdk_stream_canton_oracle_v2_response_proto_rawDesc = string([]byte{
	0x0a, 0x2a, 0x73, 0x64, 0x6b, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x63, 0x61, 0x6e,
	0x74, 0x6f, 0x6e, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x76, 0x32, 0x2f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x61,
	0x69, 0x6b, 0x6f, 0x73, 0x64, 0x6b, 0x22, 0xa8, 0x02, 0x0a, 0x23, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x43, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x32, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x65, 0x65, 0x64,
	0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x66, 0x65, 0x65, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x65, 0x65, 0x64, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x73,
	0x64, 0x6b, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x56, 0x32, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x61, 0x6e,
	0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x2f, 0x0a, 0x13, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x64, 0x69, 0x73,
	0x63, 0x6c, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6c, 0x6f, 0x73, 0x75, 0x72,
	0x65, 0x22, 0xc4, 0x01, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x56, 0x32, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x73, 0x64, 0x6b, 0x2e, 0x43,
	0x6f, 0x73, 0x74, 0x56, 0x32, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x73, 0x64, 0x6b, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x56, 0x32, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x79,
	0x65, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x79, 0x65, 0x65, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x06, 0x43, 0x6f, 0x73, 0x74,
	0x56, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x66, 0x65, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f,
	0x73, 0x64, 0x6b, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x56, 0x32, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x36,
	0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x56, 0x32,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x07, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x56,
	0x32, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x65, 0x65, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x65, 0x65, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x96, 0x01,
	0x0a, 0x25, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x5f, 0x6f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x5f, 0x76, 0x32, 0x50, 0x01, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2f, 0x63, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c,
	0x65, 0x5f, 0x76, 0x32, 0x3b, 0x63, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x5f, 0x6f, 0x72, 0x61, 0x63,
	0x6c, 0x65, 0x5f, 0x76, 0x32, 0xaa, 0x02, 0x1e, 0x4b, 0x61, 0x69, 0x6b, 0x6f, 0x53, 0x64, 0x6b,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x43, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x4f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x56, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sdk_stream_canton_oracle_v2_response_proto_rawDescOnce sync.Once
	file_sdk_stream_canton_oracle_v2_response_proto_rawDescData []byte
)

func file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_canton_oracle_v2_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_canton_oracle_v2_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_canton_oracle_v2_response_proto_rawDesc), len(file_sdk_stream_canton_oracle_v2_response_proto_rawDesc)))
	})
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescData
}

var file_sdk_stream_canton_oracle_v2_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sdk_stream_canton_oracle_v2_response_proto_goTypes = []any{
	(*StreamCantonOracleServiceResponseV2)(nil), // 0: kaikosdk.StreamCantonOracleServiceResponseV2
	(*SignedPayloadV2)(nil),                     // 1: kaikosdk.SignedPayloadV2
	(*CostV2)(nil),                              // 2: kaikosdk.CostV2
	(*InstrumentIdV2)(nil),                      // 3: kaikosdk.InstrumentIdV2
	(*QuoteV2)(nil),                             // 4: kaikosdk.QuoteV2
}
var file_sdk_stream_canton_oracle_v2_response_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamCantonOracleServiceResponseV2.payload:type_name -> kaikosdk.SignedPayloadV2
	2, // 1: kaikosdk.SignedPayloadV2.cost:type_name -> kaikosdk.CostV2
	4, // 2: kaikosdk.SignedPayloadV2.quote:type_name -> kaikosdk.QuoteV2
	3, // 3: kaikosdk.CostV2.instrument:type_name -> kaikosdk.InstrumentIdV2
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sdk_stream_canton_oracle_v2_response_proto_init() }
func file_sdk_stream_canton_oracle_v2_response_proto_init() {
	if File_sdk_stream_canton_oracle_v2_response_proto != nil {
		return
	}
	file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_canton_oracle_v2_response_proto_rawDesc), len(file_sdk_stream_canton_oracle_v2_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_canton_oracle_v2_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_canton_oracle_v2_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_canton_oracle_v2_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_canton_oracle_v2_response_proto = out.File
	file_sdk_stream_canton_oracle_v2_response_proto_goTypes = nil
	file_sdk_stream_canton_oracle_v2_response_proto_depIdxs = nil
}
