// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/canton_oracle_v2/response.proto

package canton_oracle_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamCantonOracleServiceResponseV2 is one Pull Oracle V2 signed update for exactly one feed. Only
// `payload` is signed; the routing fields and canonical_hash are not covered by the signature.
type StreamCantonOracleServiceResponseV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network the payload belongs to; echoes the request.
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// feed_category echoes the selector.
	FeedCategory string `protobuf:"bytes,2,opt,name=feed_category,json=feedCategory,proto3" json:"feed_category,omitempty"`
	// feed_id is the feed this message belongs to; equals the `feedId` entry of payload.values.
	FeedId string `protobuf:"bytes,3,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	// payload is the oracle-signed payload, reconstructed verbatim and re-canonicalised on-ledger.
	Payload *SignedPayloadV2 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// signature is the hex-encoded DER secp256k1 signature committing to the KDS v0.2 structural
	// root hash of `payload`: codec "v2-datapoint-hash" when `payload.cost` is unset (free path),
	// "v2-paid-quote-hash" when it is set (paid path, cost + payee). The signed digest is the
	// sha256 of the decoded root-hash bytes.
	Signature string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// canonical_hash is the lowercase-hex KDS v0.2 structural root hash of `payload` (the value the
	// signature commits to), for client-side pre-checks; the verifier always recomputes it on-ledger.
	CanonicalHash string `protobuf:"bytes,6,opt,name=canonical_hash,json=canonicalHash,proto3" json:"canonical_hash,omitempty"`
	// verifier_contract identifies the verifier contract whose key signed this payload (KaikoQuoteVerifier
	// when free, KaikoPaidQuoteVerifier when paid) and carries its explicit-disclosure blob. The subscriber
	// passes it through unmodified.
	VerifierContract *VerifierContract `protobuf:"bytes,7,opt,name=verifier_contract,json=verifierContract,proto3" json:"verifier_contract,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamCantonOracleServiceResponseV2) Reset() {
	*x = StreamCantonOracleServiceResponseV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCantonOracleServiceResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCantonOracleServiceResponseV2) ProtoMessage() {}

func (x *StreamCantonOracleServiceResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCantonOracleServiceResponseV2.ProtoReflect.Descriptor instead.
func (*StreamCantonOracleServiceResponseV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamCantonOracleServiceResponseV2) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetFeedCategory() string {
	if x != nil {
		return x.FeedCategory
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetPayload() *SignedPayloadV2 {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamCantonOracleServiceResponseV2) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetCanonicalHash() string {
	if x != nil {
		return x.CanonicalHash
	}
	return ""
}

func (x *StreamCantonOracleServiceResponseV2) GetVerifierContract() *VerifierContract {
	if x != nil {
		return x.VerifierContract
	}
	return nil
}

// VerifierContract identifies the verifier contract (KaikoQuoteVerifier when free, KaikoPaidQuoteVerifier
// when paid) whose key signed a V2 payload, and carries its explicit-disclosure blob. The subscriber
// passes these through unmodified when exercising the verifier on-ledger. Field names are camelCase to
// mirror the on-ledger disclosed-contract literal.
// protolint:disable FIELD_NAMES_LOWER_SNAKE_CASE
type VerifierContract struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// templateId is the fully-qualified Daml template id of the verifier contract.
	TemplateId string `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	// contractId is the ledger contract id of the verifier contract.
	ContractId string `protobuf:"bytes,2,opt,name=contractId,proto3" json:"contractId,omitempty"`
	// createdEventBlob is the opaque explicit-disclosure blob (base64) for the verifier contract.
	CreatedEventBlob string `protobuf:"bytes,3,opt,name=createdEventBlob,proto3" json:"createdEventBlob,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifierContract) Reset() {
	*x = VerifierContract{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifierContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifierContract) ProtoMessage() {}

func (x *VerifierContract) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifierContract.ProtoReflect.Descriptor instead.
func (*VerifierContract) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{1}
}

func (x *VerifierContract) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *VerifierContract) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *VerifierContract) GetCreatedEventBlob() string {
	if x != nil {
		return x.CreatedEventBlob
	}
	return ""
}

// SignedPayloadV2 is the record signed off-chain by the oracle (DataStandard.SignatureVerifierV1).
// The field names mirror the Canton PaidSignedPayload literal the
// PaidQuoteConsumer.VerifyAndRecordQuote choice consumes.//
// The quote's three fields are flat rather than a tagged values map. On-ledger a quote is a data
// point whose `values` carry them under schema "quote-1", but assembling that map is a chore in
// JSON and easy to get subtly wrong — a price tagged as text rather than a decimal hashes
// differently and simply fails to verify. `VerifyAndPay` rebuilds the map from these fields with
// the standard's own encoder before checking anything, so the signature still covers the tagged
// form while a client submits the flat one.
// protolint:disable FIELD_NAMES_LOWER_SNAKE_CASE
// protolint:disable FIELD_NAMES_EXCLUDE_PREPOSITIONS
type SignedPayloadV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// publishedAt is when the oracle produced this payload, as an ISO-8601 UTC timestamp with microsecond
	// precision (e.g. "2026-07-04T13:41:50.852000Z"), injected as a DAML Time.
	PublishedAt string `protobuf:"bytes,1,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	// expiresAt is the validity deadline, as an ISO-8601 UTC timestamp with microsecond precision (e.g.
	// "2026-07-04T13:41:50.852000Z"), injected as a DAML Time; Verify rejects a payload strictly later.
	ExpiresAt string `protobuf:"bytes,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	// cost is the per-call price. Unset means the unpriced (free) case (cost = None), signed with the
	// "v2-datapoint-hash" codec; when set the payload is signed with the "v2-paid-quote-hash" codec.
	Cost *CostV2 `protobuf:"bytes,3,opt,name=cost,proto3,oneof" json:"cost,omitempty"`
	// payee is the fee recipient the oracle signs into every paid payload (DataStandard PaidSignedPayload
	// .payee). Set only on the paid path (alongside cost) and covered by the signature; empty on the free
	// path.
	Payee string `protobuf:"bytes,4,opt,name=payee,proto3" json:"payee,omitempty"`
	// schemaVersion names the shape the quote was signed under: "quote-1"
	// (DataStandard.Codecs.Quote.quoteSchemaVersion). Carried rather than assumed, because it is
	// inside the signed hash — re-labelling an authentic quote breaks verification rather than
	// succeeding quietly.
	SchemaVersion string `protobuf:"bytes,5,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	// feedId is the stable feed identifier; MUST equal the requested feed id.
	FeedId string `protobuf:"bytes,6,opt,name=feedId,proto3" json:"feedId,omitempty"`
	// price is the decimal price, string-encoded to preserve precision. It is the Daml `show` form
	// (shortest exact, at least one fractional digit), which is also how a Daml `Decimal` decodes
	// from JSON, so the field is submitted verbatim.
	Price string `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	// priceTime is when the producer observed the quote, as an ISO-8601 UTC timestamp with
	// microsecond precision (e.g. "2026-07-04T13:41:50.852000Z"), injected as a DAML Time.
	PriceTime     string `protobuf:"bytes,8,opt,name=priceTime,proto3" json:"priceTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPayloadV2) Reset() {
	*x = SignedPayloadV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPayloadV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPayloadV2) ProtoMessage() {}

func (x *SignedPayloadV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPayloadV2.ProtoReflect.Descriptor instead.
func (*SignedPayloadV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{2}
}

func (x *SignedPayloadV2) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *SignedPayloadV2) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *SignedPayloadV2) GetCost() *CostV2 {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *SignedPayloadV2) GetPayee() string {
	if x != nil {
		return x.Payee
	}
	return ""
}

func (x *SignedPayloadV2) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SignedPayloadV2) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *SignedPayloadV2) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SignedPayloadV2) GetPriceTime() string {
	if x != nil {
		return x.PriceTime
	}
	return ""
}

// CostV2 is the per-call fee and the instrument it is denominated in.
type CostV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fee is the decimal fee, string-encoded to preserve precision.
	Fee string `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	// instrument is the Token Standard instrument the fee is paid in.
	Instrument    *InstrumentIdV2 `protobuf:"bytes,2,opt,name=instrument,proto3" json:"instrument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostV2) Reset() {
	*x = CostV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostV2) ProtoMessage() {}

func (x *CostV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostV2.ProtoReflect.Descriptor instead.
func (*CostV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{3}
}

func (x *CostV2) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *CostV2) GetInstrument() *InstrumentIdV2 {
	if x != nil {
		return x.Instrument
	}
	return nil
}

// InstrumentIdV2 is a Token Standard instrument identifier (Splice.Api.Token.HoldingV1.InstrumentId).
type InstrumentIdV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// admin is the instrument administrator party id (the registry).
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// id is the instrument symbol, e.g. "Amulet" for Canton Coin.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentIdV2) Reset() {
	*x = InstrumentIdV2{}
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentIdV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentIdV2) ProtoMessage() {}

func (x *InstrumentIdV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentIdV2.ProtoReflect.Descriptor instead.
func (*InstrumentIdV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP(), []int{4}
}

func (x *InstrumentIdV2) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

func (x *InstrumentIdV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_sdk_stream_canton_oracle_v2_response_proto protoreflect.FileDescriptor

const file_sdk_stream_canton_oracle_v2_response_proto_rawDesc = "" +
	"\n" +
	"*sdk/stream/canton_oracle_v2/response.proto\x12\bkaikosdk\"\xc0\x02\n" +
	"#StreamCantonOracleServiceResponseV2\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12#\n" +
	"\rfeed_category\x18\x02 \x01(\tR\ffeedCategory\x12\x17\n" +
	"\afeed_id\x18\x03 \x01(\tR\x06feedId\x123\n" +
	"\apayload\x18\x04 \x01(\v2\x19.kaikosdk.SignedPayloadV2R\apayload\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12%\n" +
	"\x0ecanonical_hash\x18\x06 \x01(\tR\rcanonicalHash\x12G\n" +
	"\x11verifier_contract\x18\a \x01(\v2\x1a.kaikosdk.VerifierContractR\x10verifierContract\"~\n" +
	"\x10VerifierContract\x12\x1e\n" +
	"\n" +
	"templateId\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1e\n" +
	"\n" +
	"contractId\x18\x02 \x01(\tR\n" +
	"contractId\x12*\n" +
	"\x10createdEventBlob\x18\x03 \x01(\tR\x10createdEventBlob\"\x8d\x02\n" +
	"\x0fSignedPayloadV2\x12 \n" +
	"\vpublishedAt\x18\x01 \x01(\tR\vpublishedAt\x12\x1c\n" +
	"\texpiresAt\x18\x02 \x01(\tR\texpiresAt\x12)\n" +
	"\x04cost\x18\x03 \x01(\v2\x10.kaikosdk.CostV2H\x00R\x04cost\x88\x01\x01\x12\x14\n" +
	"\x05payee\x18\x04 \x01(\tR\x05payee\x12$\n" +
	"\rschemaVersion\x18\x05 \x01(\tR\rschemaVersion\x12\x16\n" +
	"\x06feedId\x18\x06 \x01(\tR\x06feedId\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12\x1c\n" +
	"\tpriceTime\x18\b \x01(\tR\tpriceTimeB\a\n" +
	"\x05_cost\"T\n" +
	"\x06CostV2\x12\x10\n" +
	"\x03fee\x18\x01 \x01(\tR\x03fee\x128\n" +
	"\n" +
	"instrument\x18\x02 \x01(\v2\x18.kaikosdk.InstrumentIdV2R\n" +
	"instrument\"6\n" +
	"\x0eInstrumentIdV2\x12\x14\n" +
	"\x05admin\x18\x01 \x01(\tR\x05admin\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02idB\x96\x01\n" +
	"%com.kaiko.sdk.stream.canton_oracle_v2P\x01ZJgithub.com/kaikodata/kaiko-go-sdk/stream/canton_oracle_v2;canton_oracle_v2\xaa\x02\x1eKaikoSdk.Stream.CantonOracleV2b\x06proto3"

var (
	file_sdk_stream_canton_oracle_v2_response_proto_rawDescOnce sync.Once
	file_sdk_stream_canton_oracle_v2_response_proto_rawDescData []byte
)

func file_sdk_stream_canton_oracle_v2_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_canton_oracle_v2_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_canton_oracle_v2_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_canton_oracle_v2_response_proto_rawDesc), len(file_sdk_stream_canton_oracle_v2_response_proto_rawDesc)))
	})
	return file_sdk_stream_canton_oracle_v2_response_proto_rawDescData
}

var file_sdk_stream_canton_oracle_v2_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sdk_stream_canton_oracle_v2_response_proto_goTypes = []any{
	(*StreamCantonOracleServiceResponseV2)(nil), // 0: kaikosdk.StreamCantonOracleServiceResponseV2
	(*VerifierContract)(nil),                    // 1: kaikosdk.VerifierContract
	(*SignedPayloadV2)(nil),                     // 2: kaikosdk.SignedPayloadV2
	(*CostV2)(nil),                              // 3: kaikosdk.CostV2
	(*InstrumentIdV2)(nil),                      // 4: kaikosdk.InstrumentIdV2
}
var file_sdk_stream_canton_oracle_v2_response_proto_depIdxs = []int32{
	2, // 0: kaikosdk.StreamCantonOracleServiceResponseV2.payload:type_name -> kaikosdk.SignedPayloadV2
	1, // 1: kaikosdk.StreamCantonOracleServiceResponseV2.verifier_contract:type_name -> kaikosdk.VerifierContract
	3, // 2: kaikosdk.SignedPayloadV2.cost:type_name -> kaikosdk.CostV2
	4, // 3: kaikosdk.CostV2.instrument:type_name -> kaikosdk.InstrumentIdV2
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sdk_stream_canton_oracle_v2_response_proto_init() }
func file_sdk_stream_canton_oracle_v2_response_proto_init() {
	if File_sdk_stream_canton_oracle_v2_response_proto != nil {
		return
	}
	file_sdk_stream_canton_oracle_v2_response_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_canton_oracle_v2_response_proto_rawDesc), len(file_sdk_stream_canton_oracle_v2_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_canton_oracle_v2_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_canton_oracle_v2_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_canton_oracle_v2_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_canton_oracle_v2_response_proto = out.File
	file_sdk_stream_canton_oracle_v2_response_proto_goTypes = nil
	file_sdk_stream_canton_oracle_v2_response_proto_depIdxs = nil
}
