// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/aggregated_price_v1/request.proto

package aggregated_price_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamAggregatedPriceRequestV1
type StreamAggregatedPriceRequestV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument class. See https://docs.kaiko.com/?python#instruments.
	InstrumentClass string `protobuf:"bytes,1,opt,name=instrument_class,json=instrumentClass,proto3" json:"instrument_class,omitempty"`
	// Instrument code. See https://docs.kaiko.com/?python#instruments.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Data interval. For historical data only.
	Interval      *core.DataInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAggregatedPriceRequestV1) Reset() {
	*x = StreamAggregatedPriceRequestV1{}
	mi := &file_sdk_stream_aggregated_price_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatedPriceRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatedPriceRequestV1) ProtoMessage() {}

func (x *StreamAggregatedPriceRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_aggregated_price_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatedPriceRequestV1.ProtoReflect.Descriptor instead.
func (*StreamAggregatedPriceRequestV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_aggregated_price_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAggregatedPriceRequestV1) GetInstrumentClass() string {
	if x != nil {
		return x.InstrumentClass
	}
	return ""
}

func (x *StreamAggregatedPriceRequestV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamAggregatedPriceRequestV1) GetInterval() *core.DataInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_sdk_stream_aggregated_price_v1_request_proto protoreflect.FileDescriptor

const file_sdk_stream_aggregated_price_v1_request_proto_rawDesc = "" +
	"\n" +
	",sdk/stream/aggregated_price_v1/request.proto\x12\bkaikosdk\x1a\x1csdk/core/data_interval.proto\"\x93\x01\n" +
	"\x1eStreamAggregatedPriceRequestV1\x12)\n" +
	"\x10instrument_class\x18\x01 \x01(\tR\x0finstrumentClass\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x122\n" +
	"\binterval\x18\x03 \x01(\v2\x16.kaikosdk.DataIntervalR\bintervalB\xa2\x01\n" +
	"(com.kaiko.sdk.stream.aggregated_price_v1P\x01ZPgithub.com/kaikodata/kaiko-go-sdk/stream/aggregated_price_v1;aggregated_price_v1\xaa\x02!KaikoSdk.Stream.AggregatedPriceV1b\x06proto3"

var (
	file_sdk_stream_aggregated_price_v1_request_proto_rawDescOnce sync.Once
	file_sdk_stream_aggregated_price_v1_request_proto_rawDescData []byte
)

func file_sdk_stream_aggregated_price_v1_request_proto_rawDescGZIP() []byte {
	file_sdk_stream_aggregated_price_v1_request_proto_rawDescOnce.Do(func() {
		file_sdk_stream_aggregated_price_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregated_price_v1_request_proto_rawDesc), len(file_sdk_stream_aggregated_price_v1_request_proto_rawDesc)))
	})
	return file_sdk_stream_aggregated_price_v1_request_proto_rawDescData
}

var file_sdk_stream_aggregated_price_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_stream_aggregated_price_v1_request_proto_goTypes = []any{
	(*StreamAggregatedPriceRequestV1)(nil), // 0: kaikosdk.StreamAggregatedPriceRequestV1
	(*core.DataInterval)(nil),              // 1: kaikosdk.DataInterval
}
var file_sdk_stream_aggregated_price_v1_request_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamAggregatedPriceRequestV1.interval:type_name -> kaikosdk.DataInterval
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_stream_aggregated_price_v1_request_proto_init() }
func file_sdk_stream_aggregated_price_v1_request_proto_init() {
	if File_sdk_stream_aggregated_price_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregated_price_v1_request_proto_rawDesc), len(file_sdk_stream_aggregated_price_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_aggregated_price_v1_request_proto_goTypes,
		DependencyIndexes: file_sdk_stream_aggregated_price_v1_request_proto_depIdxs,
		MessageInfos:      file_sdk_stream_aggregated_price_v1_request_proto_msgTypes,
	}.Build()
	File_sdk_stream_aggregated_price_v1_request_proto = out.File
	file_sdk_stream_aggregated_price_v1_request_proto_goTypes = nil
	file_sdk_stream_aggregated_price_v1_request_proto_depIdxs = nil
}
