// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/aggregated_price_v1/response.proto

package aggregated_price_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType is event category for a value.
type StreamAggregatedPriceResponseV1_EventType int32

const (
	// Unknown type.
	StreamAggregatedPriceResponseV1_UNKNOWN StreamAggregatedPriceResponseV1_EventType = 0
	// BEST_ASK type.
	StreamAggregatedPriceResponseV1_BEST_ASK StreamAggregatedPriceResponseV1_EventType = 1
	// BEST_BID type.
	StreamAggregatedPriceResponseV1_BEST_BID StreamAggregatedPriceResponseV1_EventType = 2
)

// Enum value maps for StreamAggregatedPriceResponseV1_EventType.
var (
	StreamAggregatedPriceResponseV1_EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "BEST_ASK",
		2: "BEST_BID",
	}
	StreamAggregatedPriceResponseV1_EventType_value = map[string]int32{
		"UNKNOWN":  0,
		"BEST_ASK": 1,
		"BEST_BID": 2,
	}
)

func (x StreamAggregatedPriceResponseV1_EventType) Enum() *StreamAggregatedPriceResponseV1_EventType {
	p := new(StreamAggregatedPriceResponseV1_EventType)
	*p = x
	return p
}

func (x StreamAggregatedPriceResponseV1_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamAggregatedPriceResponseV1_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_aggregated_price_v1_response_proto_enumTypes[0].Descriptor()
}

func (StreamAggregatedPriceResponseV1_EventType) Type() protoreflect.EnumType {
	return &file_sdk_stream_aggregated_price_v1_response_proto_enumTypes[0]
}

func (x StreamAggregatedPriceResponseV1_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamAggregatedPriceResponseV1_EventType.Descriptor instead.
func (StreamAggregatedPriceResponseV1_EventType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_aggregated_price_v1_response_proto_rawDescGZIP(), []int{1, 0}
}

// StreamAggregatedPriceValue is wrapper for update values.
type StreamAggregatedPriceValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price of top of book entry.
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// Volume of top of book entry.
	Volume        string `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAggregatedPriceValue) Reset() {
	*x = StreamAggregatedPriceValue{}
	mi := &file_sdk_stream_aggregated_price_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatedPriceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatedPriceValue) ProtoMessage() {}

func (x *StreamAggregatedPriceValue) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_aggregated_price_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatedPriceValue.ProtoReflect.Descriptor instead.
func (*StreamAggregatedPriceValue) Descriptor() ([]byte, []int) {
	return file_sdk_stream_aggregated_price_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAggregatedPriceValue) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *StreamAggregatedPriceValue) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

// StreamAggregatedPriceResponseV1
type StreamAggregatedPriceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregate (interval).
	Aggregate string `protobuf:"bytes,1,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	// Instrument class. See https://docs.kaiko.com/?python#instruments.
	InstrumentClass string `protobuf:"bytes,2,opt,name=instrument_class,json=instrumentClass,proto3" json:"instrument_class,omitempty"`
	// Instrument code. See https://docs.kaiko.com/?python#instruments.
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// Value is update value (price and volume). Field is absent if the ticker has no update during the aggregate inerval.
	Value *StreamAggregatedPriceValue `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Event type is ASK or BID.
	EventType StreamAggregatedPriceResponseV1_EventType `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=kaikosdk.StreamAggregatedPriceResponseV1_EventType" json:"event_type,omitempty"`
	// Timestamp of event.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAggregatedPriceResponseV1) Reset() {
	*x = StreamAggregatedPriceResponseV1{}
	mi := &file_sdk_stream_aggregated_price_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatedPriceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatedPriceResponseV1) ProtoMessage() {}

func (x *StreamAggregatedPriceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_aggregated_price_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatedPriceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamAggregatedPriceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_aggregated_price_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAggregatedPriceResponseV1) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

func (x *StreamAggregatedPriceResponseV1) GetInstrumentClass() string {
	if x != nil {
		return x.InstrumentClass
	}
	return ""
}

func (x *StreamAggregatedPriceResponseV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamAggregatedPriceResponseV1) GetValue() *StreamAggregatedPriceValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StreamAggregatedPriceResponseV1) GetEventType() StreamAggregatedPriceResponseV1_EventType {
	if x != nil {
		return x.EventType
	}
	return StreamAggregatedPriceResponseV1_UNKNOWN
}

func (x *StreamAggregatedPriceResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

var File_sdk_stream_aggregated_price_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_aggregated_price_v1_response_proto_rawDesc = "" +
	"\n" +
	"-sdk/stream/aggregated_price_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x1aStreamAggregatedPriceValue\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\tR\x06volume\"\xfb\x02\n" +
	"\x1fStreamAggregatedPriceResponseV1\x12\x1c\n" +
	"\taggregate\x18\x01 \x01(\tR\taggregate\x12)\n" +
	"\x10instrument_class\x18\x02 \x01(\tR\x0finstrumentClass\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12:\n" +
	"\x05value\x18\x04 \x01(\v2$.kaikosdk.StreamAggregatedPriceValueR\x05value\x12R\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e23.kaikosdk.StreamAggregatedPriceResponseV1.EventTypeR\teventType\x125\n" +
	"\bts_event\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\"4\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bBEST_ASK\x10\x01\x12\f\n" +
	"\bBEST_BID\x10\x02B\xa2\x01\n" +
	"(com.kaiko.sdk.stream.aggregated_price_v1P\x01ZPgithub.com/kaikodata/kaiko-go-sdk/stream/aggregated_price_v1;aggregated_price_v1\xaa\x02!KaikoSdk.Stream.AggregatedPriceV1b\x06proto3"

var (
	file_sdk_stream_aggregated_price_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_aggregated_price_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_aggregated_price_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_aggregated_price_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_aggregated_price_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregated_price_v1_response_proto_rawDesc), len(file_sdk_stream_aggregated_price_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_aggregated_price_v1_response_proto_rawDescData
}

var file_sdk_stream_aggregated_price_v1_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_aggregated_price_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_stream_aggregated_price_v1_response_proto_goTypes = []any{
	(StreamAggregatedPriceResponseV1_EventType)(0), // 0: kaikosdk.StreamAggregatedPriceResponseV1.EventType
	(*StreamAggregatedPriceValue)(nil),             // 1: kaikosdk.StreamAggregatedPriceValue
	(*StreamAggregatedPriceResponseV1)(nil),        // 2: kaikosdk.StreamAggregatedPriceResponseV1
	(*timestamppb.Timestamp)(nil),                  // 3: google.protobuf.Timestamp
}
var file_sdk_stream_aggregated_price_v1_response_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamAggregatedPriceResponseV1.value:type_name -> kaikosdk.StreamAggregatedPriceValue
	0, // 1: kaikosdk.StreamAggregatedPriceResponseV1.event_type:type_name -> kaikosdk.StreamAggregatedPriceResponseV1.EventType
	3, // 2: kaikosdk.StreamAggregatedPriceResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sdk_stream_aggregated_price_v1_response_proto_init() }
func file_sdk_stream_aggregated_price_v1_response_proto_init() {
	if File_sdk_stream_aggregated_price_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregated_price_v1_response_proto_rawDesc), len(file_sdk_stream_aggregated_price_v1_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_aggregated_price_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_aggregated_price_v1_response_proto_depIdxs,
		EnumInfos:         file_sdk_stream_aggregated_price_v1_response_proto_enumTypes,
		MessageInfos:      file_sdk_stream_aggregated_price_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_aggregated_price_v1_response_proto = out.File
	file_sdk_stream_aggregated_price_v1_response_proto_goTypes = nil
	file_sdk_stream_aggregated_price_v1_response_proto_depIdxs = nil
}
