// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/market_update_v1/request.proto

package market_update_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderbookSnapshotType
type StreamMarketUpdateRequestV1_OrderbookSnapshotType int32

const (
	// UNKNOWN means no snapshot is sent.
	StreamMarketUpdateRequestV1_UNKNOWN StreamMarketUpdateRequestV1_OrderbookSnapshotType = 0
	// TEN_PERCENT is ob10%.
	StreamMarketUpdateRequestV1_TEN_PERCENT StreamMarketUpdateRequestV1_OrderbookSnapshotType = 1
	// FULL is full orderbook.
	StreamMarketUpdateRequestV1_FULL StreamMarketUpdateRequestV1_OrderbookSnapshotType = 2
)

// Enum value maps for StreamMarketUpdateRequestV1_OrderbookSnapshotType.
var (
	StreamMarketUpdateRequestV1_OrderbookSnapshotType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TEN_PERCENT",
		2: "FULL",
	}
	StreamMarketUpdateRequestV1_OrderbookSnapshotType_value = map[string]int32{
		"UNKNOWN":     0,
		"TEN_PERCENT": 1,
		"FULL":        2,
	}
)

func (x StreamMarketUpdateRequestV1_OrderbookSnapshotType) Enum() *StreamMarketUpdateRequestV1_OrderbookSnapshotType {
	p := new(StreamMarketUpdateRequestV1_OrderbookSnapshotType)
	*p = x
	return p
}

func (x StreamMarketUpdateRequestV1_OrderbookSnapshotType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamMarketUpdateRequestV1_OrderbookSnapshotType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_market_update_v1_request_proto_enumTypes[0].Descriptor()
}

func (StreamMarketUpdateRequestV1_OrderbookSnapshotType) Type() protoreflect.EnumType {
	return &file_sdk_stream_market_update_v1_request_proto_enumTypes[0]
}

func (x StreamMarketUpdateRequestV1_OrderbookSnapshotType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamMarketUpdateRequestV1_OrderbookSnapshotType.Descriptor instead.
func (StreamMarketUpdateRequestV1_OrderbookSnapshotType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_market_update_v1_request_proto_rawDescGZIP(), []int{0, 0}
}

// StreamMarketUpdateRequestV1
type StreamMarketUpdateRequestV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InstrumentCriteria is instrument exchange, class and code, wildcard (*) can be used.
	InstrumentCriteria *core.InstrumentCriteria `protobuf:"bytes,1,opt,name=instrument_criteria,json=instrumentCriteria,proto3" json:"instrument_criteria,omitempty"`
	// Enum indicating type of feed. If no commodity is specified, you get all commodities by default, otherwise you get only specified commodities.
	Commodities []StreamMarketUpdateCommodity `protobuf:"varint,2,rep,packed,name=commodities,proto3,enum=kaikosdk.StreamMarketUpdateCommodity" json:"commodities,omitempty"`
	// Data interval. For historical data only.
	Interval *core.DataInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// SnapshotType is the type of snapshot if commodities contains orderbook.
	// This field is deprecated and used anymore, only full snapshot are sent.
	//
	// Deprecated: Marked as deprecated in sdk/stream/market_update_v1/request.proto.
	SnapshotType  StreamMarketUpdateRequestV1_OrderbookSnapshotType `protobuf:"varint,4,opt,name=snapshot_type,json=snapshotType,proto3,enum=kaikosdk.StreamMarketUpdateRequestV1_OrderbookSnapshotType" json:"snapshot_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMarketUpdateRequestV1) Reset() {
	*x = StreamMarketUpdateRequestV1{}
	mi := &file_sdk_stream_market_update_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMarketUpdateRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMarketUpdateRequestV1) ProtoMessage() {}

func (x *StreamMarketUpdateRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_market_update_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMarketUpdateRequestV1.ProtoReflect.Descriptor instead.
func (*StreamMarketUpdateRequestV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_market_update_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *StreamMarketUpdateRequestV1) GetInstrumentCriteria() *core.InstrumentCriteria {
	if x != nil {
		return x.InstrumentCriteria
	}
	return nil
}

func (x *StreamMarketUpdateRequestV1) GetCommodities() []StreamMarketUpdateCommodity {
	if x != nil {
		return x.Commodities
	}
	return nil
}

func (x *StreamMarketUpdateRequestV1) GetInterval() *core.DataInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

// Deprecated: Marked as deprecated in sdk/stream/market_update_v1/request.proto.
func (x *StreamMarketUpdateRequestV1) GetSnapshotType() StreamMarketUpdateRequestV1_OrderbookSnapshotType {
	if x != nil {
		return x.SnapshotType
	}
	return StreamMarketUpdateRequestV1_UNKNOWN
}

var File_sdk_stream_market_update_v1_request_proto protoreflect.FileDescriptor

const file_sdk_stream_market_update_v1_request_proto_rawDesc = "" +
	"\n" +
	")sdk/stream/market_update_v1/request.proto\x12\bkaikosdk\x1a\x1csdk/core/data_interval.proto\x1a\"sdk/core/instrument_criteria.proto\x1a+sdk/stream/market_update_v1/commodity.proto\"\x90\x03\n" +
	"\x1bStreamMarketUpdateRequestV1\x12M\n" +
	"\x13instrument_criteria\x18\x01 \x01(\v2\x1c.kaikosdk.InstrumentCriteriaR\x12instrumentCriteria\x12G\n" +
	"\vcommodities\x18\x02 \x03(\x0e2%.kaikosdk.StreamMarketUpdateCommodityR\vcommodities\x122\n" +
	"\binterval\x18\x03 \x01(\v2\x16.kaikosdk.DataIntervalR\binterval\x12d\n" +
	"\rsnapshot_type\x18\x04 \x01(\x0e2;.kaikosdk.StreamMarketUpdateRequestV1.OrderbookSnapshotTypeB\x02\x18\x01R\fsnapshotType\"?\n" +
	"\x15OrderbookSnapshotType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vTEN_PERCENT\x10\x01\x12\b\n" +
	"\x04FULL\x10\x02B\x96\x01\n" +
	"%com.kaiko.sdk.stream.market_update_v1P\x01ZJgithub.com/kaikodata/kaiko-go-sdk/stream/market_update_v1;market_update_v1\xaa\x02\x1eKaikoSdk.Stream.MarketUpdateV1b\x06proto3"

var (
	file_sdk_stream_market_update_v1_request_proto_rawDescOnce sync.Once
	file_sdk_stream_market_update_v1_request_proto_rawDescData []byte
)

func file_sdk_stream_market_update_v1_request_proto_rawDescGZIP() []byte {
	file_sdk_stream_market_update_v1_request_proto_rawDescOnce.Do(func() {
		file_sdk_stream_market_update_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_market_update_v1_request_proto_rawDesc), len(file_sdk_stream_market_update_v1_request_proto_rawDesc)))
	})
	return file_sdk_stream_market_update_v1_request_proto_rawDescData
}

var file_sdk_stream_market_update_v1_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_market_update_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_stream_market_update_v1_request_proto_goTypes = []any{
	(StreamMarketUpdateRequestV1_OrderbookSnapshotType)(0), // 0: kaikosdk.StreamMarketUpdateRequestV1.OrderbookSnapshotType
	(*StreamMarketUpdateRequestV1)(nil),                    // 1: kaikosdk.StreamMarketUpdateRequestV1
	(*core.InstrumentCriteria)(nil),                        // 2: kaikosdk.InstrumentCriteria
	(StreamMarketUpdateCommodity)(0),                       // 3: kaikosdk.StreamMarketUpdateCommodity
	(*core.DataInterval)(nil),                              // 4: kaikosdk.DataInterval
}
var file_sdk_stream_market_update_v1_request_proto_depIdxs = []int32{
	2, // 0: kaikosdk.StreamMarketUpdateRequestV1.instrument_criteria:type_name -> kaikosdk.InstrumentCriteria
	3, // 1: kaikosdk.StreamMarketUpdateRequestV1.commodities:type_name -> kaikosdk.StreamMarketUpdateCommodity
	4, // 2: kaikosdk.StreamMarketUpdateRequestV1.interval:type_name -> kaikosdk.DataInterval
	0, // 3: kaikosdk.StreamMarketUpdateRequestV1.snapshot_type:type_name -> kaikosdk.StreamMarketUpdateRequestV1.OrderbookSnapshotType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sdk_stream_market_update_v1_request_proto_init() }
func file_sdk_stream_market_update_v1_request_proto_init() {
	if File_sdk_stream_market_update_v1_request_proto != nil {
		return
	}
	file_sdk_stream_market_update_v1_commodity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_market_update_v1_request_proto_rawDesc), len(file_sdk_stream_market_update_v1_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_market_update_v1_request_proto_goTypes,
		DependencyIndexes: file_sdk_stream_market_update_v1_request_proto_depIdxs,
		EnumInfos:         file_sdk_stream_market_update_v1_request_proto_enumTypes,
		MessageInfos:      file_sdk_stream_market_update_v1_request_proto_msgTypes,
	}.Build()
	File_sdk_stream_market_update_v1_request_proto = out.File
	file_sdk_stream_market_update_v1_request_proto_goTypes = nil
	file_sdk_stream_market_update_v1_request_proto_depIdxs = nil
}
