// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/market_update_v1/response.proto

package market_update_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamMarketUpdateType is event category for a market update.
type StreamMarketUpdateResponseV1_StreamMarketUpdateType int32

const (
	// Unknown type.
	StreamMarketUpdateResponseV1_UNKNOWN StreamMarketUpdateResponseV1_StreamMarketUpdateType = 0
	// TRADE_BUY type.
	StreamMarketUpdateResponseV1_TRADE_BUY StreamMarketUpdateResponseV1_StreamMarketUpdateType = 1
	// TRADE_SELL type.
	StreamMarketUpdateResponseV1_TRADE_SELL StreamMarketUpdateResponseV1_StreamMarketUpdateType = 2
	// TRADE_UNKNOWN type.
	StreamMarketUpdateResponseV1_TRADE_UNKNOWN StreamMarketUpdateResponseV1_StreamMarketUpdateType = 9
	// BEST_ASK type.
	StreamMarketUpdateResponseV1_BEST_ASK StreamMarketUpdateResponseV1_StreamMarketUpdateType = 3
	// BEST_BID type.
	StreamMarketUpdateResponseV1_BEST_BID StreamMarketUpdateResponseV1_StreamMarketUpdateType = 4
	// UPDATED_ASK type.
	StreamMarketUpdateResponseV1_UPDATED_ASK StreamMarketUpdateResponseV1_StreamMarketUpdateType = 5
	// UPDATED_BID type.
	StreamMarketUpdateResponseV1_UPDATED_BID StreamMarketUpdateResponseV1_StreamMarketUpdateType = 6
	// SNAPSHOT type.
	StreamMarketUpdateResponseV1_SNAPSHOT StreamMarketUpdateResponseV1_StreamMarketUpdateType = 7
	// FORCE_SNAPSHOT type. Internal use only.
	StreamMarketUpdateResponseV1_FORCE_SNAPSHOT StreamMarketUpdateResponseV1_StreamMarketUpdateType = 8
)

// Enum value maps for StreamMarketUpdateResponseV1_StreamMarketUpdateType.
var (
	StreamMarketUpdateResponseV1_StreamMarketUpdateType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TRADE_BUY",
		2: "TRADE_SELL",
		9: "TRADE_UNKNOWN",
		3: "BEST_ASK",
		4: "BEST_BID",
		5: "UPDATED_ASK",
		6: "UPDATED_BID",
		7: "SNAPSHOT",
		8: "FORCE_SNAPSHOT",
	}
	StreamMarketUpdateResponseV1_StreamMarketUpdateType_value = map[string]int32{
		"UNKNOWN":        0,
		"TRADE_BUY":      1,
		"TRADE_SELL":     2,
		"TRADE_UNKNOWN":  9,
		"BEST_ASK":       3,
		"BEST_BID":       4,
		"UPDATED_ASK":    5,
		"UPDATED_BID":    6,
		"SNAPSHOT":       7,
		"FORCE_SNAPSHOT": 8,
	}
)

func (x StreamMarketUpdateResponseV1_StreamMarketUpdateType) Enum() *StreamMarketUpdateResponseV1_StreamMarketUpdateType {
	p := new(StreamMarketUpdateResponseV1_StreamMarketUpdateType)
	*p = x
	return p
}

func (x StreamMarketUpdateResponseV1_StreamMarketUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamMarketUpdateResponseV1_StreamMarketUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_market_update_v1_response_proto_enumTypes[0].Descriptor()
}

func (StreamMarketUpdateResponseV1_StreamMarketUpdateType) Type() protoreflect.EnumType {
	return &file_sdk_stream_market_update_v1_response_proto_enumTypes[0]
}

func (x StreamMarketUpdateResponseV1_StreamMarketUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamMarketUpdateResponseV1_StreamMarketUpdateType.Descriptor instead.
func (StreamMarketUpdateResponseV1_StreamMarketUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_market_update_v1_response_proto_rawDescGZIP(), []int{0, 0}
}

// StreamMarketUpdateResponseV1
type StreamMarketUpdateResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind of commodity concerned by the market update.
	Commodity StreamMarketUpdateCommodity `protobuf:"varint,1,opt,name=commodity,proto3,enum=kaikosdk.StreamMarketUpdateCommodity" json:"commodity,omitempty"`
	// Amount / quantity of asset bought or sold, displayed in base currency.
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Instrument class, internal Kaiko classification denoting whether an instrument is a spot, future, perpetual future, or option.
	Class string `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	// Instrument code (currency pair), for example btc-usd.
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// Instrument exchange code, for example "cbse" (Coinbase).
	Exchange string `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Sequence ID for event. Sortable in lexicographic order.
	SequenceId string `protobuf:"bytes,6,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	// ID from exchange (trades only), empty string when not present.
	Id string `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	// Price for quote currency.
	Price float64 `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	// Timestamp of the event as provided by the exchange.
	TsExchange *core.TimestampValue `protobuf:"bytes,9,opt,name=ts_exchange,json=tsExchange,proto3" json:"ts_exchange,omitempty"`
	// Timestamp of collection (event entered Kaiko's infrastructure), before nomalization.
	TsCollection *core.TimestampValue `protobuf:"bytes,10,opt,name=ts_collection,json=tsCollection,proto3" json:"ts_collection,omitempty"`
	// Event generation timestamp (event created by Kaiko), after normalization.
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	// Event category for this update.
	UpdateType StreamMarketUpdateResponseV1_StreamMarketUpdateType `protobuf:"varint,12,opt,name=update_type,json=updateType,proto3,enum=kaikosdk.StreamMarketUpdateResponseV1_StreamMarketUpdateType" json:"update_type,omitempty"`
	// Snapshot for this update.
	Snapshot *StreamMarketUpdateResponseV1_Snapshot `protobuf:"bytes,13,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// Additionnal properties, specific to the exchange.
	AdditionalProperties map[string]string `protobuf:"bytes,14,rep,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StreamMarketUpdateResponseV1) Reset() {
	*x = StreamMarketUpdateResponseV1{}
	mi := &file_sdk_stream_market_update_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMarketUpdateResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMarketUpdateResponseV1) ProtoMessage() {}

func (x *StreamMarketUpdateResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_market_update_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMarketUpdateResponseV1.ProtoReflect.Descriptor instead.
func (*StreamMarketUpdateResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_market_update_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamMarketUpdateResponseV1) GetCommodity() StreamMarketUpdateCommodity {
	if x != nil {
		return x.Commodity
	}
	return StreamMarketUpdateCommodity_SMUC_UNKNOWN
}

func (x *StreamMarketUpdateResponseV1) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StreamMarketUpdateResponseV1) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *StreamMarketUpdateResponseV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamMarketUpdateResponseV1) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StreamMarketUpdateResponseV1) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *StreamMarketUpdateResponseV1) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamMarketUpdateResponseV1) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamMarketUpdateResponseV1) GetTsExchange() *core.TimestampValue {
	if x != nil {
		return x.TsExchange
	}
	return nil
}

func (x *StreamMarketUpdateResponseV1) GetTsCollection() *core.TimestampValue {
	if x != nil {
		return x.TsCollection
	}
	return nil
}

func (x *StreamMarketUpdateResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

func (x *StreamMarketUpdateResponseV1) GetUpdateType() StreamMarketUpdateResponseV1_StreamMarketUpdateType {
	if x != nil {
		return x.UpdateType
	}
	return StreamMarketUpdateResponseV1_UNKNOWN
}

func (x *StreamMarketUpdateResponseV1) GetSnapshot() *StreamMarketUpdateResponseV1_Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *StreamMarketUpdateResponseV1) GetAdditionalProperties() map[string]string {
	if x != nil {
		return x.AdditionalProperties
	}
	return nil
}

// Snapshot is an orderbook snapshot.
type StreamMarketUpdateResponseV1_Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Asks is the list of asks of the orderbook.
	Asks []*StreamMarketUpdateResponseV1_Snapshot_Order `protobuf:"bytes,1,rep,name=asks,proto3" json:"asks,omitempty"`
	// Bids is the list of bids of the orderbook.
	Bids          []*StreamMarketUpdateResponseV1_Snapshot_Order `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMarketUpdateResponseV1_Snapshot) Reset() {
	*x = StreamMarketUpdateResponseV1_Snapshot{}
	mi := &file_sdk_stream_market_update_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMarketUpdateResponseV1_Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMarketUpdateResponseV1_Snapshot) ProtoMessage() {}

func (x *StreamMarketUpdateResponseV1_Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_market_update_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMarketUpdateResponseV1_Snapshot.ProtoReflect.Descriptor instead.
func (*StreamMarketUpdateResponseV1_Snapshot) Descriptor() ([]byte, []int) {
	return file_sdk_stream_market_update_v1_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StreamMarketUpdateResponseV1_Snapshot) GetAsks() []*StreamMarketUpdateResponseV1_Snapshot_Order {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *StreamMarketUpdateResponseV1_Snapshot) GetBids() []*StreamMarketUpdateResponseV1_Snapshot_Order {
	if x != nil {
		return x.Bids
	}
	return nil
}

// Order is a amount at a price level.
type StreamMarketUpdateResponseV1_Snapshot_Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount / quantity of asset bought or sold, displayed in base currency.
	Amount float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Price for quote currency.
	Price         float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMarketUpdateResponseV1_Snapshot_Order) Reset() {
	*x = StreamMarketUpdateResponseV1_Snapshot_Order{}
	mi := &file_sdk_stream_market_update_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMarketUpdateResponseV1_Snapshot_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMarketUpdateResponseV1_Snapshot_Order) ProtoMessage() {}

func (x *StreamMarketUpdateResponseV1_Snapshot_Order) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_market_update_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMarketUpdateResponseV1_Snapshot_Order.ProtoReflect.Descriptor instead.
func (*StreamMarketUpdateResponseV1_Snapshot_Order) Descriptor() ([]byte, []int) {
	return file_sdk_stream_market_update_v1_response_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *StreamMarketUpdateResponseV1_Snapshot_Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StreamMarketUpdateResponseV1_Snapshot_Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_sdk_stream_market_update_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_market_update_v1_response_proto_rawDesc = "" +
	"\n" +
	"*sdk/stream/market_update_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17sdk/core/wrappers.proto\x1a+sdk/stream/market_update_v1/commodity.proto\"\xba\t\n" +
	"\x1cStreamMarketUpdateResponseV1\x12C\n" +
	"\tcommodity\x18\x01 \x01(\x0e2%.kaikosdk.StreamMarketUpdateCommodityR\tcommodity\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12\x1f\n" +
	"\vsequence_id\x18\x06 \x01(\tR\n" +
	"sequenceId\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x129\n" +
	"\vts_exchange\x18\t \x01(\v2\x18.kaikosdk.TimestampValueR\n" +
	"tsExchange\x12=\n" +
	"\rts_collection\x18\n" +
	" \x01(\v2\x18.kaikosdk.TimestampValueR\ftsCollection\x125\n" +
	"\bts_event\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x12^\n" +
	"\vupdate_type\x18\f \x01(\x0e2=.kaikosdk.StreamMarketUpdateResponseV1.StreamMarketUpdateTypeR\n" +
	"updateType\x12K\n" +
	"\bsnapshot\x18\r \x01(\v2/.kaikosdk.StreamMarketUpdateResponseV1.SnapshotR\bsnapshot\x12u\n" +
	"\x15additional_properties\x18\x0e \x03(\v2@.kaikosdk.StreamMarketUpdateResponseV1.AdditionalPropertiesEntryR\x14additionalProperties\x1a\xd7\x01\n" +
	"\bSnapshot\x12I\n" +
	"\x04asks\x18\x01 \x03(\v25.kaikosdk.StreamMarketUpdateResponseV1.Snapshot.OrderR\x04asks\x12I\n" +
	"\x04bids\x18\x02 \x03(\v25.kaikosdk.StreamMarketUpdateResponseV1.Snapshot.OrderR\x04bids\x1a5\n" +
	"\x05Order\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x1aG\n" +
	"\x19AdditionalPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x16StreamMarketUpdateType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tTRADE_BUY\x10\x01\x12\x0e\n" +
	"\n" +
	"TRADE_SELL\x10\x02\x12\x11\n" +
	"\rTRADE_UNKNOWN\x10\t\x12\f\n" +
	"\bBEST_ASK\x10\x03\x12\f\n" +
	"\bBEST_BID\x10\x04\x12\x0f\n" +
	"\vUPDATED_ASK\x10\x05\x12\x0f\n" +
	"\vUPDATED_BID\x10\x06\x12\f\n" +
	"\bSNAPSHOT\x10\a\x12\x12\n" +
	"\x0eFORCE_SNAPSHOT\x10\bB\x96\x01\n" +
	"%com.kaiko.sdk.stream.market_update_v1P\x01ZJgithub.com/kaikodata/kaiko-go-sdk/stream/market_update_v1;market_update_v1\xaa\x02\x1eKaikoSdk.Stream.MarketUpdateV1b\x06proto3"

var (
	file_sdk_stream_market_update_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_market_update_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_market_update_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_market_update_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_market_update_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_market_update_v1_response_proto_rawDesc), len(file_sdk_stream_market_update_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_market_update_v1_response_proto_rawDescData
}

var file_sdk_stream_market_update_v1_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_market_update_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sdk_stream_market_update_v1_response_proto_goTypes = []any{
	(StreamMarketUpdateResponseV1_StreamMarketUpdateType)(0), // 0: kaikosdk.StreamMarketUpdateResponseV1.StreamMarketUpdateType
	(*StreamMarketUpdateResponseV1)(nil),                     // 1: kaikosdk.StreamMarketUpdateResponseV1
	(*StreamMarketUpdateResponseV1_Snapshot)(nil),            // 2: kaikosdk.StreamMarketUpdateResponseV1.Snapshot
	nil, // 3: kaikosdk.StreamMarketUpdateResponseV1.AdditionalPropertiesEntry
	(*StreamMarketUpdateResponseV1_Snapshot_Order)(nil), // 4: kaikosdk.StreamMarketUpdateResponseV1.Snapshot.Order
	(StreamMarketUpdateCommodity)(0),                    // 5: kaikosdk.StreamMarketUpdateCommodity
	(*core.TimestampValue)(nil),                         // 6: kaikosdk.TimestampValue
	(*timestamppb.Timestamp)(nil),                       // 7: google.protobuf.Timestamp
}
var file_sdk_stream_market_update_v1_response_proto_depIdxs = []int32{
	5, // 0: kaikosdk.StreamMarketUpdateResponseV1.commodity:type_name -> kaikosdk.StreamMarketUpdateCommodity
	6, // 1: kaikosdk.StreamMarketUpdateResponseV1.ts_exchange:type_name -> kaikosdk.TimestampValue
	6, // 2: kaikosdk.StreamMarketUpdateResponseV1.ts_collection:type_name -> kaikosdk.TimestampValue
	7, // 3: kaikosdk.StreamMarketUpdateResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	0, // 4: kaikosdk.StreamMarketUpdateResponseV1.update_type:type_name -> kaikosdk.StreamMarketUpdateResponseV1.StreamMarketUpdateType
	2, // 5: kaikosdk.StreamMarketUpdateResponseV1.snapshot:type_name -> kaikosdk.StreamMarketUpdateResponseV1.Snapshot
	3, // 6: kaikosdk.StreamMarketUpdateResponseV1.additional_properties:type_name -> kaikosdk.StreamMarketUpdateResponseV1.AdditionalPropertiesEntry
	4, // 7: kaikosdk.StreamMarketUpdateResponseV1.Snapshot.asks:type_name -> kaikosdk.StreamMarketUpdateResponseV1.Snapshot.Order
	4, // 8: kaikosdk.StreamMarketUpdateResponseV1.Snapshot.bids:type_name -> kaikosdk.StreamMarketUpdateResponseV1.Snapshot.Order
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_sdk_stream_market_update_v1_response_proto_init() }
func file_sdk_stream_market_update_v1_response_proto_init() {
	if File_sdk_stream_market_update_v1_response_proto != nil {
		return
	}
	file_sdk_stream_market_update_v1_commodity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_market_update_v1_response_proto_rawDesc), len(file_sdk_stream_market_update_v1_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_market_update_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_market_update_v1_response_proto_depIdxs,
		EnumInfos:         file_sdk_stream_market_update_v1_response_proto_enumTypes,
		MessageInfos:      file_sdk_stream_market_update_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_market_update_v1_response_proto = out.File
	file_sdk_stream_market_update_v1_response_proto_goTypes = nil
	file_sdk_stream_market_update_v1_response_proto_depIdxs = nil
}
