// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/evm_oracle_v1/response.proto

package evm_oracle_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamEvmOracleServiceResponseV1 is one EIP-712 signed price update for exactly one instrument.
// The fields are the exact values covered by the signature.
type StreamEvmOracleServiceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset_class of the instrument (e.g. "crypto", "equity", "fx"), bound into the signature.
	AssetClass *string `protobuf:"bytes,1,opt,name=asset_class,json=assetClass,proto3,oneof" json:"asset_class,omitempty"`
	// instrument_id the price is for.
	InstrumentId string `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	// price as a scaled integer: actual value = price * 10^-decimal. Always set — a no-price
	// upstream tick (market closed) is never emitted.
	Price *int64 `protobuf:"varint,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	// decimal is the scaling exponent applied to price.
	Decimal int32 `protobuf:"varint,4,opt,name=decimal,proto3" json:"decimal,omitempty"`
	// timestamp of the upstream observation in unix seconds (UTC), the value on-chain verifiers
	// compare to block.timestamp.
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// signature is the 65-byte secp256k1 signature (r||s||v), hex-encoded with a "0x" prefix, over
	// the EIP-712 typed-data digest bound to the requested blockchain's signing domain.
	Signature     string `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvmOracleServiceResponseV1) Reset() {
	*x = StreamEvmOracleServiceResponseV1{}
	mi := &file_sdk_stream_evm_oracle_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvmOracleServiceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvmOracleServiceResponseV1) ProtoMessage() {}

func (x *StreamEvmOracleServiceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_evm_oracle_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvmOracleServiceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamEvmOracleServiceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_evm_oracle_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamEvmOracleServiceResponseV1) GetAssetClass() string {
	if x != nil && x.AssetClass != nil {
		return *x.AssetClass
	}
	return ""
}

func (x *StreamEvmOracleServiceResponseV1) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *StreamEvmOracleServiceResponseV1) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *StreamEvmOracleServiceResponseV1) GetDecimal() int32 {
	if x != nil {
		return x.Decimal
	}
	return 0
}

func (x *StreamEvmOracleServiceResponseV1) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamEvmOracleServiceResponseV1) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_sdk_stream_evm_oracle_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_evm_oracle_v1_response_proto_rawDesc = "" +
	"\n" +
	"'sdk/stream/evm_oracle_v1/response.proto\x12\bkaikosdk\"\xf8\x01\n" +
	" StreamEvmOracleServiceResponseV1\x12$\n" +
	"\vasset_class\x18\x01 \x01(\tH\x00R\n" +
	"assetClass\x88\x01\x01\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x03H\x01R\x05price\x88\x01\x01\x12\x18\n" +
	"\adecimal\x18\x04 \x01(\x05R\adecimal\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignatureB\x0e\n" +
	"\f_asset_classB\b\n" +
	"\x06_priceB\x8a\x01\n" +
	"\"com.kaiko.sdk.stream.evm_oracle_v1P\x01ZDgithub.com/kaikodata/kaiko-go-sdk/stream/evm_oracle_v1;evm_oracle_v1\xaa\x02\x1bKaikoSdk.Stream.EvmOracleV1b\x06proto3"

var (
	file_sdk_stream_evm_oracle_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_evm_oracle_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_evm_oracle_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_evm_oracle_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_evm_oracle_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_evm_oracle_v1_response_proto_rawDesc), len(file_sdk_stream_evm_oracle_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_evm_oracle_v1_response_proto_rawDescData
}

var file_sdk_stream_evm_oracle_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_stream_evm_oracle_v1_response_proto_goTypes = []any{
	(*StreamEvmOracleServiceResponseV1)(nil), // 0: kaikosdk.StreamEvmOracleServiceResponseV1
}
var file_sdk_stream_evm_oracle_v1_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_stream_evm_oracle_v1_response_proto_init() }
func file_sdk_stream_evm_oracle_v1_response_proto_init() {
	if File_sdk_stream_evm_oracle_v1_response_proto != nil {
		return
	}
	file_sdk_stream_evm_oracle_v1_response_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_evm_oracle_v1_response_proto_rawDesc), len(file_sdk_stream_evm_oracle_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_evm_oracle_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_evm_oracle_v1_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_evm_oracle_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_evm_oracle_v1_response_proto = out.File
	file_sdk_stream_evm_oracle_v1_response_proto_goTypes = nil
	file_sdk_stream_evm_oracle_v1_response_proto_depIdxs = nil
}
