// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/exotic_indices_v1/response.proto

package exotic_indices_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	index_v1 "github.com/kaikodata/kaiko-go-sdk/stream/index_v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Position is the position of the indice
type StreamExoticIndicesPosition int32

const (
	// Position unknown.
	StreamExoticIndicesPosition_SEIP_POSITION_UNKNOWN StreamExoticIndicesPosition = 0
	// Long position.
	StreamExoticIndicesPosition_SEIP_LONG StreamExoticIndicesPosition = 1
	// Short position.
	StreamExoticIndicesPosition_SEIP_SHORT StreamExoticIndicesPosition = 2
)

// Enum value maps for StreamExoticIndicesPosition.
var (
	StreamExoticIndicesPosition_name = map[int32]string{
		0: "SEIP_POSITION_UNKNOWN",
		1: "SEIP_LONG",
		2: "SEIP_SHORT",
	}
	StreamExoticIndicesPosition_value = map[string]int32{
		"SEIP_POSITION_UNKNOWN": 0,
		"SEIP_LONG":             1,
		"SEIP_SHORT":            2,
	}
)

func (x StreamExoticIndicesPosition) Enum() *StreamExoticIndicesPosition {
	p := new(StreamExoticIndicesPosition)
	*p = x
	return p
}

func (x StreamExoticIndicesPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamExoticIndicesPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_exotic_indices_v1_response_proto_enumTypes[0].Descriptor()
}

func (StreamExoticIndicesPosition) Type() protoreflect.EnumType {
	return &file_sdk_stream_exotic_indices_v1_response_proto_enumTypes[0]
}

func (x StreamExoticIndicesPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamExoticIndicesPosition.Descriptor instead.
func (StreamExoticIndicesPosition) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_exotic_indices_v1_response_proto_rawDescGZIP(), []int{0}
}

// StreamExoticIndicesServiceResponseComposition is the composition used to compute the index.
type StreamExoticIndicesServiceResponseComposition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Underlying rate of the indices.
	UnderlyingInstrument string `protobuf:"bytes,1,opt,name=underlying_instrument,json=underlyingInstrument,proto3" json:"underlying_instrument,omitempty"`
	// Base.
	Base string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	// Quote.
	Quote string `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	// Currency conversion.
	CurrencyConversion string `protobuf:"bytes,6,opt,name=currency_conversion,json=currencyConversion,proto3" json:"currency_conversion,omitempty"`
	// Timestamp (tick) of underlying rate ts.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExoticIndicesServiceResponseComposition) Reset() {
	*x = StreamExoticIndicesServiceResponseComposition{}
	mi := &file_sdk_stream_exotic_indices_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExoticIndicesServiceResponseComposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExoticIndicesServiceResponseComposition) ProtoMessage() {}

func (x *StreamExoticIndicesServiceResponseComposition) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_exotic_indices_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExoticIndicesServiceResponseComposition.ProtoReflect.Descriptor instead.
func (*StreamExoticIndicesServiceResponseComposition) Descriptor() ([]byte, []int) {
	return file_sdk_stream_exotic_indices_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamExoticIndicesServiceResponseComposition) GetUnderlyingInstrument() string {
	if x != nil {
		return x.UnderlyingInstrument
	}
	return ""
}

func (x *StreamExoticIndicesServiceResponseComposition) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *StreamExoticIndicesServiceResponseComposition) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *StreamExoticIndicesServiceResponseComposition) GetCurrencyConversion() string {
	if x != nil {
		return x.CurrencyConversion
	}
	return ""
}

func (x *StreamExoticIndicesServiceResponseComposition) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

// StreamExoticIndicesServiceResponsePair is the pair information for the rates used
type StreamExoticIndicesServiceResponsePair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Underlying instrument of the indices.
	UnderlyingInstrument string `protobuf:"bytes,1,opt,name=underlying_instrument,json=underlyingInstrument,proto3" json:"underlying_instrument,omitempty"`
	// Underlying price of the instrument.
	UnderlyingPrice *wrapperspb.DoubleValue `protobuf:"bytes,2,opt,name=underlying_price,json=underlyingPrice,proto3" json:"underlying_price,omitempty"`
	// Weighting factor of the instrument.
	WeightingFactor float64 `protobuf:"fixed64,3,opt,name=weighting_factor,json=weightingFactor,proto3" json:"weighting_factor,omitempty"`
	// Capping factor of the instrument.
	CappingFactor float64 `protobuf:"fixed64,4,opt,name=capping_factor,json=cappingFactor,proto3" json:"capping_factor,omitempty"`
	// Currency conversion factor of the instrument.
	CurrencyConversionFactor float64 `protobuf:"fixed64,5,opt,name=currency_conversion_factor,json=currencyConversionFactor,proto3" json:"currency_conversion_factor,omitempty"`
	// Position of the instrument.
	Position      StreamExoticIndicesPosition `protobuf:"varint,6,opt,name=position,proto3,enum=kaikosdk.StreamExoticIndicesPosition" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExoticIndicesServiceResponsePair) Reset() {
	*x = StreamExoticIndicesServiceResponsePair{}
	mi := &file_sdk_stream_exotic_indices_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExoticIndicesServiceResponsePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExoticIndicesServiceResponsePair) ProtoMessage() {}

func (x *StreamExoticIndicesServiceResponsePair) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_exotic_indices_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExoticIndicesServiceResponsePair.ProtoReflect.Descriptor instead.
func (*StreamExoticIndicesServiceResponsePair) Descriptor() ([]byte, []int) {
	return file_sdk_stream_exotic_indices_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *StreamExoticIndicesServiceResponsePair) GetUnderlyingInstrument() string {
	if x != nil {
		return x.UnderlyingInstrument
	}
	return ""
}

func (x *StreamExoticIndicesServiceResponsePair) GetUnderlyingPrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UnderlyingPrice
	}
	return nil
}

func (x *StreamExoticIndicesServiceResponsePair) GetWeightingFactor() float64 {
	if x != nil {
		return x.WeightingFactor
	}
	return 0
}

func (x *StreamExoticIndicesServiceResponsePair) GetCappingFactor() float64 {
	if x != nil {
		return x.CappingFactor
	}
	return 0
}

func (x *StreamExoticIndicesServiceResponsePair) GetCurrencyConversionFactor() float64 {
	if x != nil {
		return x.CurrencyConversionFactor
	}
	return 0
}

func (x *StreamExoticIndicesServiceResponsePair) GetPosition() StreamExoticIndicesPosition {
	if x != nil {
		return x.Position
	}
	return StreamExoticIndicesPosition_SEIP_POSITION_UNKNOWN
}

// StreamExoticIndicesServiceResponsePrices is the prices informations on the pair used
type StreamExoticIndicesServiceResponsePrices struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index value.
	IndexValue float64 `protobuf:"fixed64,1,opt,name=index_value,json=indexValue,proto3" json:"index_value,omitempty"`
	// Divisor.
	Divisor float64 `protobuf:"fixed64,2,opt,name=divisor,proto3" json:"divisor,omitempty"`
	// StreamExoticIndicesServiceResponsePair is the pair information.
	Pairs         []*StreamExoticIndicesServiceResponsePair `protobuf:"bytes,3,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExoticIndicesServiceResponsePrices) Reset() {
	*x = StreamExoticIndicesServiceResponsePrices{}
	mi := &file_sdk_stream_exotic_indices_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExoticIndicesServiceResponsePrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExoticIndicesServiceResponsePrices) ProtoMessage() {}

func (x *StreamExoticIndicesServiceResponsePrices) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_exotic_indices_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExoticIndicesServiceResponsePrices.ProtoReflect.Descriptor instead.
func (*StreamExoticIndicesServiceResponsePrices) Descriptor() ([]byte, []int) {
	return file_sdk_stream_exotic_indices_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *StreamExoticIndicesServiceResponsePrices) GetIndexValue() float64 {
	if x != nil {
		return x.IndexValue
	}
	return 0
}

func (x *StreamExoticIndicesServiceResponsePrices) GetDivisor() float64 {
	if x != nil {
		return x.Divisor
	}
	return 0
}

func (x *StreamExoticIndicesServiceResponsePrices) GetPairs() []*StreamExoticIndicesServiceResponsePair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

// StreamIndexServiceResponseV1 is the response for the exotic indices.
type StreamExoticIndicesServiceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type.
	Commodity index_v1.StreamIndexCommodity `protobuf:"varint,1,opt,name=commodity,proto3,enum=kaikosdk.StreamIndexCommodity" json:"commodity,omitempty"`
	// Index code.
	IndexCode string `protobuf:"bytes,2,opt,name=index_code,json=indexCode,proto3" json:"index_code,omitempty"`
	// Data interval.
	Interval *core.DataInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// Quote.
	MainQuote string `protobuf:"bytes,4,opt,name=main_quote,json=mainQuote,proto3" json:"main_quote,omitempty"`
	// List of indices compositions.
	Compositions []*StreamExoticIndicesServiceResponseComposition `protobuf:"bytes,5,rep,name=compositions,proto3" json:"compositions,omitempty"`
	// Price of the indice.
	Price *StreamExoticIndicesServiceResponsePrices `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	// Event generation timestamp (event created by Kaiko).
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	// Timestamp of computation.
	TsCompute     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ts_compute,json=tsCompute,proto3" json:"ts_compute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExoticIndicesServiceResponseV1) Reset() {
	*x = StreamExoticIndicesServiceResponseV1{}
	mi := &file_sdk_stream_exotic_indices_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExoticIndicesServiceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExoticIndicesServiceResponseV1) ProtoMessage() {}

func (x *StreamExoticIndicesServiceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_exotic_indices_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExoticIndicesServiceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamExoticIndicesServiceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_exotic_indices_v1_response_proto_rawDescGZIP(), []int{3}
}

func (x *StreamExoticIndicesServiceResponseV1) GetCommodity() index_v1.StreamIndexCommodity {
	if x != nil {
		return x.Commodity
	}
	return index_v1.StreamIndexCommodity(0)
}

func (x *StreamExoticIndicesServiceResponseV1) GetIndexCode() string {
	if x != nil {
		return x.IndexCode
	}
	return ""
}

func (x *StreamExoticIndicesServiceResponseV1) GetInterval() *core.DataInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *StreamExoticIndicesServiceResponseV1) GetMainQuote() string {
	if x != nil {
		return x.MainQuote
	}
	return ""
}

func (x *StreamExoticIndicesServiceResponseV1) GetCompositions() []*StreamExoticIndicesServiceResponseComposition {
	if x != nil {
		return x.Compositions
	}
	return nil
}

func (x *StreamExoticIndicesServiceResponseV1) GetPrice() *StreamExoticIndicesServiceResponsePrices {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *StreamExoticIndicesServiceResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

func (x *StreamExoticIndicesServiceResponseV1) GetTsCompute() *timestamppb.Timestamp {
	if x != nil {
		return x.TsCompute
	}
	return nil
}

var File_sdk_stream_exotic_indices_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_exotic_indices_v1_response_proto_rawDesc = "" +
	"\n" +
	"+sdk/stream/exotic_indices_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1csdk/core/data_interval.proto\x1a#sdk/stream/index_v1/commodity.proto\"\xf6\x01\n" +
	"-StreamExoticIndicesServiceResponseComposition\x123\n" +
	"\x15underlying_instrument\x18\x01 \x01(\tR\x14underlyingInstrument\x12\x12\n" +
	"\x04base\x18\x02 \x01(\tR\x04base\x12\x14\n" +
	"\x05quote\x18\x03 \x01(\tR\x05quote\x12/\n" +
	"\x13currency_conversion\x18\x06 \x01(\tR\x12currencyConversion\x125\n" +
	"\bts_event\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\"\xf9\x02\n" +
	"&StreamExoticIndicesServiceResponsePair\x123\n" +
	"\x15underlying_instrument\x18\x01 \x01(\tR\x14underlyingInstrument\x12G\n" +
	"\x10underlying_price\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x0funderlyingPrice\x12)\n" +
	"\x10weighting_factor\x18\x03 \x01(\x01R\x0fweightingFactor\x12%\n" +
	"\x0ecapping_factor\x18\x04 \x01(\x01R\rcappingFactor\x12<\n" +
	"\x1acurrency_conversion_factor\x18\x05 \x01(\x01R\x18currencyConversionFactor\x12A\n" +
	"\bposition\x18\x06 \x01(\x0e2%.kaikosdk.StreamExoticIndicesPositionR\bposition\"\xad\x01\n" +
	"(StreamExoticIndicesServiceResponsePrices\x12\x1f\n" +
	"\vindex_value\x18\x01 \x01(\x01R\n" +
	"indexValue\x12\x18\n" +
	"\adivisor\x18\x02 \x01(\x01R\adivisor\x12F\n" +
	"\x05pairs\x18\x03 \x03(\v20.kaikosdk.StreamExoticIndicesServiceResponsePairR\x05pairs\"\xef\x03\n" +
	"$StreamExoticIndicesServiceResponseV1\x12<\n" +
	"\tcommodity\x18\x01 \x01(\x0e2\x1e.kaikosdk.StreamIndexCommodityR\tcommodity\x12\x1d\n" +
	"\n" +
	"index_code\x18\x02 \x01(\tR\tindexCode\x122\n" +
	"\binterval\x18\x03 \x01(\v2\x16.kaikosdk.DataIntervalR\binterval\x12\x1d\n" +
	"\n" +
	"main_quote\x18\x04 \x01(\tR\tmainQuote\x12[\n" +
	"\fcompositions\x18\x05 \x03(\v27.kaikosdk.StreamExoticIndicesServiceResponseCompositionR\fcompositions\x12H\n" +
	"\x05price\x18\x06 \x01(\v22.kaikosdk.StreamExoticIndicesServiceResponsePricesR\x05price\x125\n" +
	"\bts_event\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x129\n" +
	"\n" +
	"ts_compute\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttsCompute*W\n" +
	"\x1bStreamExoticIndicesPosition\x12\x19\n" +
	"\x15SEIP_POSITION_UNKNOWN\x10\x00\x12\r\n" +
	"\tSEIP_LONG\x10\x01\x12\x0e\n" +
	"\n" +
	"SEIP_SHORT\x10\x02B\x9a\x01\n" +
	"&com.kaiko.sdk.stream.exotic_indices_v1P\x01ZLgithub.com/kaikodata/kaiko-go-sdk/stream/exotic_indices_v1;exotic_indices_v1\xaa\x02\x1fKaikoSdk.Stream.ExoticIndicesV1b\x06proto3"

var (
	file_sdk_stream_exotic_indices_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_exotic_indices_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_exotic_indices_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_exotic_indices_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_exotic_indices_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_exotic_indices_v1_response_proto_rawDesc), len(file_sdk_stream_exotic_indices_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_exotic_indices_v1_response_proto_rawDescData
}

var file_sdk_stream_exotic_indices_v1_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_exotic_indices_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sdk_stream_exotic_indices_v1_response_proto_goTypes = []any{
	(StreamExoticIndicesPosition)(0),                      // 0: kaikosdk.StreamExoticIndicesPosition
	(*StreamExoticIndicesServiceResponseComposition)(nil), // 1: kaikosdk.StreamExoticIndicesServiceResponseComposition
	(*StreamExoticIndicesServiceResponsePair)(nil),        // 2: kaikosdk.StreamExoticIndicesServiceResponsePair
	(*StreamExoticIndicesServiceResponsePrices)(nil),      // 3: kaikosdk.StreamExoticIndicesServiceResponsePrices
	(*StreamExoticIndicesServiceResponseV1)(nil),          // 4: kaikosdk.StreamExoticIndicesServiceResponseV1
	(*timestamppb.Timestamp)(nil),                         // 5: google.protobuf.Timestamp
	(*wrapperspb.DoubleValue)(nil),                        // 6: google.protobuf.DoubleValue
	(index_v1.StreamIndexCommodity)(0),                    // 7: kaikosdk.StreamIndexCommodity
	(*core.DataInterval)(nil),                             // 8: kaikosdk.DataInterval
}
var file_sdk_stream_exotic_indices_v1_response_proto_depIdxs = []int32{
	5,  // 0: kaikosdk.StreamExoticIndicesServiceResponseComposition.ts_event:type_name -> google.protobuf.Timestamp
	6,  // 1: kaikosdk.StreamExoticIndicesServiceResponsePair.underlying_price:type_name -> google.protobuf.DoubleValue
	0,  // 2: kaikosdk.StreamExoticIndicesServiceResponsePair.position:type_name -> kaikosdk.StreamExoticIndicesPosition
	2,  // 3: kaikosdk.StreamExoticIndicesServiceResponsePrices.pairs:type_name -> kaikosdk.StreamExoticIndicesServiceResponsePair
	7,  // 4: kaikosdk.StreamExoticIndicesServiceResponseV1.commodity:type_name -> kaikosdk.StreamIndexCommodity
	8,  // 5: kaikosdk.StreamExoticIndicesServiceResponseV1.interval:type_name -> kaikosdk.DataInterval
	1,  // 6: kaikosdk.StreamExoticIndicesServiceResponseV1.compositions:type_name -> kaikosdk.StreamExoticIndicesServiceResponseComposition
	3,  // 7: kaikosdk.StreamExoticIndicesServiceResponseV1.price:type_name -> kaikosdk.StreamExoticIndicesServiceResponsePrices
	5,  // 8: kaikosdk.StreamExoticIndicesServiceResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	5,  // 9: kaikosdk.StreamExoticIndicesServiceResponseV1.ts_compute:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sdk_stream_exotic_indices_v1_response_proto_init() }
func file_sdk_stream_exotic_indices_v1_response_proto_init() {
	if File_sdk_stream_exotic_indices_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_exotic_indices_v1_response_proto_rawDesc), len(file_sdk_stream_exotic_indices_v1_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_exotic_indices_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_exotic_indices_v1_response_proto_depIdxs,
		EnumInfos:         file_sdk_stream_exotic_indices_v1_response_proto_enumTypes,
		MessageInfos:      file_sdk_stream_exotic_indices_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_exotic_indices_v1_response_proto = out.File
	file_sdk_stream_exotic_indices_v1_response_proto_goTypes = nil
	file_sdk_stream_exotic_indices_v1_response_proto_depIdxs = nil
}
