// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/core/assets.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Assets
type Assets struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base asset.
	Base string `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Quote asset.
	Quote         string `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assets) Reset() {
	*x = Assets{}
	mi := &file_sdk_core_assets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assets) ProtoMessage() {}

func (x *Assets) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_core_assets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assets.ProtoReflect.Descriptor instead.
func (*Assets) Descriptor() ([]byte, []int) {
	return file_sdk_core_assets_proto_rawDescGZIP(), []int{0}
}

func (x *Assets) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Assets) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

var File_sdk_core_assets_proto protoreflect.FileDescriptor

const file_sdk_core_assets_proto_rawDesc = "" +
	"\n" +
	"\x15sdk/core/assets.proto\x12\bkaikosdk\"2\n" +
	"\x06Assets\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quoteBS\n" +
	"\x12com.kaiko.sdk.coreP\x01Z+github.com/kaikodata/kaiko-go-sdk/core;core\xaa\x02\rKaikoSdk.Coreb\x06proto3"

var (
	file_sdk_core_assets_proto_rawDescOnce sync.Once
	file_sdk_core_assets_proto_rawDescData []byte
)

func file_sdk_core_assets_proto_rawDescGZIP() []byte {
	file_sdk_core_assets_proto_rawDescOnce.Do(func() {
		file_sdk_core_assets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_core_assets_proto_rawDesc), len(file_sdk_core_assets_proto_rawDesc)))
	})
	return file_sdk_core_assets_proto_rawDescData
}

var file_sdk_core_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_core_assets_proto_goTypes = []any{
	(*Assets)(nil), // 0: kaikosdk.Assets
}
var file_sdk_core_assets_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_core_assets_proto_init() }
func file_sdk_core_assets_proto_init() {
	if File_sdk_core_assets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_core_assets_proto_rawDesc), len(file_sdk_core_assets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_core_assets_proto_goTypes,
		DependencyIndexes: file_sdk_core_assets_proto_depIdxs,
		MessageInfos:      file_sdk_core_assets_proto_msgTypes,
	}.Build()
	File_sdk_core_assets_proto = out.File
	file_sdk_core_assets_proto_goTypes = nil
	file_sdk_core_assets_proto_depIdxs = nil
}
