// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/core/instrument_criteria.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstrumentCriteria
type InstrumentCriteria struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument exchange code, for example "cbse" (Coinbase).
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Instrument class. See https://docs.kaiko.com/?python#instruments.
	InstrumentClass string `protobuf:"bytes,2,opt,name=instrument_class,json=instrumentClass,proto3" json:"instrument_class,omitempty"`
	// Instrument code. See https://docs.kaiko.com/?python#instruments.
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentCriteria) Reset() {
	*x = InstrumentCriteria{}
	mi := &file_sdk_core_instrument_criteria_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentCriteria) ProtoMessage() {}

func (x *InstrumentCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_core_instrument_criteria_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentCriteria.ProtoReflect.Descriptor instead.
func (*InstrumentCriteria) Descriptor() ([]byte, []int) {
	return file_sdk_core_instrument_criteria_proto_rawDescGZIP(), []int{0}
}

func (x *InstrumentCriteria) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *InstrumentCriteria) GetInstrumentClass() string {
	if x != nil {
		return x.InstrumentClass
	}
	return ""
}

func (x *InstrumentCriteria) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_sdk_core_instrument_criteria_proto protoreflect.FileDescriptor

const file_sdk_core_instrument_criteria_proto_rawDesc = "" +
	"\n" +
	"\"sdk/core/instrument_criteria.proto\x12\bkaikosdk\"o\n" +
	"\x12InstrumentCriteria\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12)\n" +
	"\x10instrument_class\x18\x02 \x01(\tR\x0finstrumentClass\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04codeBS\n" +
	"\x12com.kaiko.sdk.coreP\x01Z+github.com/kaikodata/kaiko-go-sdk/core;core\xaa\x02\rKaikoSdk.Coreb\x06proto3"

var (
	file_sdk_core_instrument_criteria_proto_rawDescOnce sync.Once
	file_sdk_core_instrument_criteria_proto_rawDescData []byte
)

func file_sdk_core_instrument_criteria_proto_rawDescGZIP() []byte {
	file_sdk_core_instrument_criteria_proto_rawDescOnce.Do(func() {
		file_sdk_core_instrument_criteria_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_core_instrument_criteria_proto_rawDesc), len(file_sdk_core_instrument_criteria_proto_rawDesc)))
	})
	return file_sdk_core_instrument_criteria_proto_rawDescData
}

var file_sdk_core_instrument_criteria_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_core_instrument_criteria_proto_goTypes = []any{
	(*InstrumentCriteria)(nil), // 0: kaikosdk.InstrumentCriteria
}
var file_sdk_core_instrument_criteria_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_core_instrument_criteria_proto_init() }
func file_sdk_core_instrument_criteria_proto_init() {
	if File_sdk_core_instrument_criteria_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_core_instrument_criteria_proto_rawDesc), len(file_sdk_core_instrument_criteria_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_core_instrument_criteria_proto_goTypes,
		DependencyIndexes: file_sdk_core_instrument_criteria_proto_depIdxs,
		MessageInfos:      file_sdk_core_instrument_criteria_proto_msgTypes,
	}.Build()
	File_sdk_core_instrument_criteria_proto = out.File
	file_sdk_core_instrument_criteria_proto_goTypes = nil
	file_sdk_core_instrument_criteria_proto_depIdxs = nil
}
