// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/core/sort_criteria.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortCriteria
type SortCriteria int32

const (
	// SORT_UNKNOWN (sorting not specified).
	SortCriteria_SORT_UNKNOWN SortCriteria = 0
	// ASC (ascendant).
	SortCriteria_ASC SortCriteria = 1
	// DESC (descendant).
	SortCriteria_DESC SortCriteria = 2
)

// Enum value maps for SortCriteria.
var (
	SortCriteria_name = map[int32]string{
		0: "SORT_UNKNOWN",
		1: "ASC",
		2: "DESC",
	}
	SortCriteria_value = map[string]int32{
		"SORT_UNKNOWN": 0,
		"ASC":          1,
		"DESC":         2,
	}
)

func (x SortCriteria) Enum() *SortCriteria {
	p := new(SortCriteria)
	*p = x
	return p
}

func (x SortCriteria) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortCriteria) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_core_sort_criteria_proto_enumTypes[0].Descriptor()
}

func (SortCriteria) Type() protoreflect.EnumType {
	return &file_sdk_core_sort_criteria_proto_enumTypes[0]
}

func (x SortCriteria) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortCriteria.Descriptor instead.
func (SortCriteria) EnumDescriptor() ([]byte, []int) {
	return file_sdk_core_sort_criteria_proto_rawDescGZIP(), []int{0}
}

var File_sdk_core_sort_criteria_proto protoreflect.FileDescriptor

const file_sdk_core_sort_criteria_proto_rawDesc = "" +
	"\n" +
	"\x1csdk/core/sort_criteria.proto\x12\bkaikosdk*3\n" +
	"\fSortCriteria\x12\x10\n" +
	"\fSORT_UNKNOWN\x10\x00\x12\a\n" +
	"\x03ASC\x10\x01\x12\b\n" +
	"\x04DESC\x10\x02BS\n" +
	"\x12com.kaiko.sdk.coreP\x01Z+github.com/kaikodata/kaiko-go-sdk/core;core\xaa\x02\rKaikoSdk.Coreb\x06proto3"

var (
	file_sdk_core_sort_criteria_proto_rawDescOnce sync.Once
	file_sdk_core_sort_criteria_proto_rawDescData []byte
)

func file_sdk_core_sort_criteria_proto_rawDescGZIP() []byte {
	file_sdk_core_sort_criteria_proto_rawDescOnce.Do(func() {
		file_sdk_core_sort_criteria_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_core_sort_criteria_proto_rawDesc), len(file_sdk_core_sort_criteria_proto_rawDesc)))
	})
	return file_sdk_core_sort_criteria_proto_rawDescData
}

var file_sdk_core_sort_criteria_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_core_sort_criteria_proto_goTypes = []any{
	(SortCriteria)(0), // 0: kaikosdk.SortCriteria
}
var file_sdk_core_sort_criteria_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_core_sort_criteria_proto_init() }
func file_sdk_core_sort_criteria_proto_init() {
	if File_sdk_core_sort_criteria_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_core_sort_criteria_proto_rawDesc), len(file_sdk_core_sort_criteria_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_core_sort_criteria_proto_goTypes,
		DependencyIndexes: file_sdk_core_sort_criteria_proto_depIdxs,
		EnumInfos:         file_sdk_core_sort_criteria_proto_enumTypes,
	}.Build()
	File_sdk_core_sort_criteria_proto = out.File
	file_sdk_core_sort_criteria_proto_goTypes = nil
	file_sdk_core_sort_criteria_proto_depIdxs = nil
}
