// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: sdk/core/sort_criteria.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortCriteria
type SortCriteria int32

const (
	// SORT_UNKNOWN (sorting not specified).
	SortCriteria_SORT_UNKNOWN SortCriteria = 0
	// ASC (ascendant).
	SortCriteria_ASC SortCriteria = 1
	// DESC (descendant).
	SortCriteria_DESC SortCriteria = 2
)

// Enum value maps for SortCriteria.
var (
	SortCriteria_name = map[int32]string{
		0: "SORT_UNKNOWN",
		1: "ASC",
		2: "DESC",
	}
	SortCriteria_value = map[string]int32{
		"SORT_UNKNOWN": 0,
		"ASC":          1,
		"DESC":         2,
	}
)

func (x SortCriteria) Enum() *SortCriteria {
	p := new(SortCriteria)
	*p = x
	return p
}

func (x SortCriteria) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortCriteria) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_core_sort_criteria_proto_enumTypes[0].Descriptor()
}

func (SortCriteria) Type() protoreflect.EnumType {
	return &file_sdk_core_sort_criteria_proto_enumTypes[0]
}

func (x SortCriteria) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortCriteria.Descriptor instead.
func (SortCriteria) EnumDescriptor() ([]byte, []int) {
	return file_sdk_core_sort_criteria_proto_rawDescGZIP(), []int{0}
}

var File_sdk_core_sort_criteria_proto protoreflect.FileDescriptor

var file_sdk_core_sort_criteria_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x73, 0x64, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x6f, 0x72, 0x74, 0x5f,
	0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x73, 0x64, 0x6b, 0x2a, 0x33, 0x0a, 0x0c, 0x53, 0x6f, 0x72, 0x74,
	0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x4f, 0x52, 0x54,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53,
	0x43, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x53, 0x43, 0x10, 0x02, 0x42, 0x53, 0x0a,
	0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6b, 0x61, 0x69, 0x6b,
	0x6f, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f,
	0x72, 0x65, 0xaa, 0x02, 0x0d, 0x4b, 0x61, 0x69, 0x6b, 0x6f, 0x53, 0x64, 0x6b, 0x2e, 0x43, 0x6f,
	0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sdk_core_sort_criteria_proto_rawDescOnce sync.Once
	file_sdk_core_sort_criteria_proto_rawDescData []byte
)

func file_sdk_core_sort_criteria_proto_rawDescGZIP() []byte {
	file_sdk_core_sort_criteria_proto_rawDescOnce.Do(func() {
		file_sdk_core_sort_criteria_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_core_sort_criteria_proto_rawDesc), len(file_sdk_core_sort_criteria_proto_rawDesc)))
	})
	return file_sdk_core_sort_criteria_proto_rawDescData
}

var file_sdk_core_sort_criteria_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_core_sort_criteria_proto_goTypes = []any{
	(SortCriteria)(0), // 0: kaikosdk.SortCriteria
}
var file_sdk_core_sort_criteria_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_core_sort_criteria_proto_init() }
func file_sdk_core_sort_criteria_proto_init() {
	if File_sdk_core_sort_criteria_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_core_sort_criteria_proto_rawDesc), len(file_sdk_core_sort_criteria_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_core_sort_criteria_proto_goTypes,
		DependencyIndexes: file_sdk_core_sort_criteria_proto_depIdxs,
		EnumInfos:         file_sdk_core_sort_criteria_proto_enumTypes,
	}.Build()
	File_sdk_core_sort_criteria_proto = out.File
	file_sdk_core_sort_criteria_proto_goTypes = nil
	file_sdk_core_sort_criteria_proto_depIdxs = nil
}
