// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/core/source_data.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SourceData
type SourceData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument exchange code, for example "cbse" (Coinbase).
	ExchangeCode string `protobuf:"bytes,1,opt,name=exchange_code,json=exchangeCode,proto3" json:"exchange_code,omitempty"`
	// Number of trades for the given instrument code and aggregate.
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Price for the instrument code on the exchange and interval.
	Price string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// Volume for the instrument code on the exchange and interval.
	Volume        string `protobuf:"bytes,4,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceData) Reset() {
	*x = SourceData{}
	mi := &file_sdk_core_source_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceData) ProtoMessage() {}

func (x *SourceData) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_core_source_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceData.ProtoReflect.Descriptor instead.
func (*SourceData) Descriptor() ([]byte, []int) {
	return file_sdk_core_source_data_proto_rawDescGZIP(), []int{0}
}

func (x *SourceData) GetExchangeCode() string {
	if x != nil {
		return x.ExchangeCode
	}
	return ""
}

func (x *SourceData) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SourceData) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SourceData) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

var File_sdk_core_source_data_proto protoreflect.FileDescriptor

const file_sdk_core_source_data_proto_rawDesc = "" +
	"\n" +
	"\x1asdk/core/source_data.proto\x12\bkaikosdk\"u\n" +
	"\n" +
	"SourceData\x12#\n" +
	"\rexchange_code\x18\x01 \x01(\tR\fexchangeCode\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\tR\x06volumeBS\n" +
	"\x12com.kaiko.sdk.coreP\x01Z+github.com/kaikodata/kaiko-go-sdk/core;core\xaa\x02\rKaikoSdk.Coreb\x06proto3"

var (
	file_sdk_core_source_data_proto_rawDescOnce sync.Once
	file_sdk_core_source_data_proto_rawDescData []byte
)

func file_sdk_core_source_data_proto_rawDescGZIP() []byte {
	file_sdk_core_source_data_proto_rawDescOnce.Do(func() {
		file_sdk_core_source_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_core_source_data_proto_rawDesc), len(file_sdk_core_source_data_proto_rawDesc)))
	})
	return file_sdk_core_source_data_proto_rawDescData
}

var file_sdk_core_source_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_core_source_data_proto_goTypes = []any{
	(*SourceData)(nil), // 0: kaikosdk.SourceData
}
var file_sdk_core_source_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_core_source_data_proto_init() }
func file_sdk_core_source_data_proto_init() {
	if File_sdk_core_source_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_core_source_data_proto_rawDesc), len(file_sdk_core_source_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_core_source_data_proto_goTypes,
		DependencyIndexes: file_sdk_core_source_data_proto_depIdxs,
		MessageInfos:      file_sdk_core_source_data_proto_msgTypes,
	}.Build()
	File_sdk_core_source_data_proto = out.File
	file_sdk_core_source_data_proto_goTypes = nil
	file_sdk_core_source_data_proto_depIdxs = nil
}
