// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/core/window.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Window information.
type Window struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start  time of the aggregation window.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time of the aggregation window.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// duration
	Duration      *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Window) Reset() {
	*x = Window{}
	mi := &file_sdk_core_window_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Window) ProtoMessage() {}

func (x *Window) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_core_window_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Window.ProtoReflect.Descriptor instead.
func (*Window) Descriptor() ([]byte, []int) {
	return file_sdk_core_window_proto_rawDescGZIP(), []int{0}
}

func (x *Window) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Window) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Window) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_sdk_core_window_proto protoreflect.FileDescriptor

const file_sdk_core_window_proto_rawDesc = "" +
	"\n" +
	"\x15sdk/core/window.proto\x12\bkaikosdk\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\x06Window\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bdurationBS\n" +
	"\x12com.kaiko.sdk.coreP\x01Z+github.com/kaikodata/kaiko-go-sdk/core;core\xaa\x02\rKaikoSdk.Coreb\x06proto3"

var (
	file_sdk_core_window_proto_rawDescOnce sync.Once
	file_sdk_core_window_proto_rawDescData []byte
)

func file_sdk_core_window_proto_rawDescGZIP() []byte {
	file_sdk_core_window_proto_rawDescOnce.Do(func() {
		file_sdk_core_window_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_core_window_proto_rawDesc), len(file_sdk_core_window_proto_rawDesc)))
	})
	return file_sdk_core_window_proto_rawDescData
}

var file_sdk_core_window_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_core_window_proto_goTypes = []any{
	(*Window)(nil),                // 0: kaikosdk.Window
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 2: google.protobuf.Duration
}
var file_sdk_core_window_proto_depIdxs = []int32{
	1, // 0: kaikosdk.Window.start_time:type_name -> google.protobuf.Timestamp
	1, // 1: kaikosdk.Window.end_time:type_name -> google.protobuf.Timestamp
	2, // 2: kaikosdk.Window.duration:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sdk_core_window_proto_init() }
func file_sdk_core_window_proto_init() {
	if File_sdk_core_window_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_core_window_proto_rawDesc), len(file_sdk_core_window_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_core_window_proto_goTypes,
		DependencyIndexes: file_sdk_core_window_proto_depIdxs,
		MessageInfos:      file_sdk_core_window_proto_msgTypes,
	}.Build()
	File_sdk_core_window_proto = out.File
	file_sdk_core_window_proto_goTypes = nil
	file_sdk_core_window_proto_depIdxs = nil
}
