// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/staking_rates_v1/response.proto

package staking_rates_v1

import (
	index_v1 "github.com/kaikodata/kaiko-go-sdk/stream/index_v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StakingRatesInterval is the interval of the staking rate.
type StakingRatesInterval struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start time.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time.
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakingRatesInterval) Reset() {
	*x = StakingRatesInterval{}
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakingRatesInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakingRatesInterval) ProtoMessage() {}

func (x *StakingRatesInterval) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakingRatesInterval.ProtoReflect.Descriptor instead.
func (*StakingRatesInterval) Descriptor() ([]byte, []int) {
	return file_sdk_stream_staking_rates_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StakingRatesInterval) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StakingRatesInterval) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// StakingRatesQuantity is the quantity of the staking rate.
type StakingRatesQuantity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value is the value of the quantity.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// Base quantity is the base quantity of the staking rate.
	BaseQuantity float64 `protobuf:"fixed64,2,opt,name=base_quantity,json=baseQuantity,proto3" json:"base_quantity,omitempty"`
	// Utilization rate is the utilization rate of the staking rate.
	UtilizationRate float64 `protobuf:"fixed64,3,opt,name=utilization_rate,json=utilizationRate,proto3" json:"utilization_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StakingRatesQuantity) Reset() {
	*x = StakingRatesQuantity{}
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakingRatesQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakingRatesQuantity) ProtoMessage() {}

func (x *StakingRatesQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakingRatesQuantity.ProtoReflect.Descriptor instead.
func (*StakingRatesQuantity) Descriptor() ([]byte, []int) {
	return file_sdk_stream_staking_rates_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *StakingRatesQuantity) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StakingRatesQuantity) GetBaseQuantity() float64 {
	if x != nil {
		return x.BaseQuantity
	}
	return 0
}

func (x *StakingRatesQuantity) GetUtilizationRate() float64 {
	if x != nil {
		return x.UtilizationRate
	}
	return 0
}

// StakingRatesUnderlyingPrice is the underlying price of the staking rate.
type StakingRatesUnderlyingPrice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the name of the underlying price.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Price is the price of the underlying price.
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// Ts event.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakingRatesUnderlyingPrice) Reset() {
	*x = StakingRatesUnderlyingPrice{}
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakingRatesUnderlyingPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakingRatesUnderlyingPrice) ProtoMessage() {}

func (x *StakingRatesUnderlyingPrice) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakingRatesUnderlyingPrice.ProtoReflect.Descriptor instead.
func (*StakingRatesUnderlyingPrice) Descriptor() ([]byte, []int) {
	return file_sdk_stream_staking_rates_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *StakingRatesUnderlyingPrice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StakingRatesUnderlyingPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StakingRatesUnderlyingPrice) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

// StakingRatesApr is the apr rate of the staking rate.
type StakingRatesApr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the name of the apr rate.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Value is the value of the apr rate.
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	// Forward filled is a boolean indicating whether the apr rate is forward filled or not.
	ForwardFilled bool `protobuf:"varint,3,opt,name=forward_filled,json=forwardFilled,proto3" json:"forward_filled,omitempty"`
	// Ts event.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakingRatesApr) Reset() {
	*x = StakingRatesApr{}
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakingRatesApr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakingRatesApr) ProtoMessage() {}

func (x *StakingRatesApr) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakingRatesApr.ProtoReflect.Descriptor instead.
func (*StakingRatesApr) Descriptor() ([]byte, []int) {
	return file_sdk_stream_staking_rates_v1_response_proto_rawDescGZIP(), []int{3}
}

func (x *StakingRatesApr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StakingRatesApr) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StakingRatesApr) GetForwardFilled() bool {
	if x != nil {
		return x.ForwardFilled
	}
	return false
}

func (x *StakingRatesApr) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

// StakingRatesComposition is the composition of the staking rates.
type StakingRatesComposition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quantity is the quantity of the staking rate.
	Quantity *StakingRatesQuantity `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Underlying price is the underlying price of the staking rate.
	UnderlyingPrice *StakingRatesUnderlyingPrice `protobuf:"bytes,2,opt,name=underlying_price,json=underlyingPrice,proto3" json:"underlying_price,omitempty"`
	// Apr is the apr rate of the staking rate.
	Apr           *StakingRatesApr `protobuf:"bytes,3,opt,name=apr,proto3" json:"apr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakingRatesComposition) Reset() {
	*x = StakingRatesComposition{}
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakingRatesComposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakingRatesComposition) ProtoMessage() {}

func (x *StakingRatesComposition) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakingRatesComposition.ProtoReflect.Descriptor instead.
func (*StakingRatesComposition) Descriptor() ([]byte, []int) {
	return file_sdk_stream_staking_rates_v1_response_proto_rawDescGZIP(), []int{4}
}

func (x *StakingRatesComposition) GetQuantity() *StakingRatesQuantity {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *StakingRatesComposition) GetUnderlyingPrice() *StakingRatesUnderlyingPrice {
	if x != nil {
		return x.UnderlyingPrice
	}
	return nil
}

func (x *StakingRatesComposition) GetApr() *StakingRatesApr {
	if x != nil {
		return x.Apr
	}
	return nil
}

// StreamStakingRatesServiceResponseV1 is the response for the staking rates.
type StreamStakingRatesServiceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Staking yield name.
	IndexCode string `protobuf:"bytes,1,opt,name=index_code,json=indexCode,proto3" json:"index_code,omitempty"`
	// Event type.
	Commodity index_v1.StreamIndexCommodity `protobuf:"varint,2,opt,name=commodity,proto3,enum=kaikosdk.StreamIndexCommodity" json:"commodity,omitempty"`
	// Data interval. For historical data only.
	Interval *StakingRatesInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// price is the price of the staking rate.
	Composition *StakingRatesComposition `protobuf:"bytes,4,opt,name=composition,proto3" json:"composition,omitempty"`
	// Price is the price of the staking rate.
	Price float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	// Ts event.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStakingRatesServiceResponseV1) Reset() {
	*x = StreamStakingRatesServiceResponseV1{}
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStakingRatesServiceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStakingRatesServiceResponseV1) ProtoMessage() {}

func (x *StreamStakingRatesServiceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_staking_rates_v1_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStakingRatesServiceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamStakingRatesServiceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_staking_rates_v1_response_proto_rawDescGZIP(), []int{5}
}

func (x *StreamStakingRatesServiceResponseV1) GetIndexCode() string {
	if x != nil {
		return x.IndexCode
	}
	return ""
}

func (x *StreamStakingRatesServiceResponseV1) GetCommodity() index_v1.StreamIndexCommodity {
	if x != nil {
		return x.Commodity
	}
	return index_v1.StreamIndexCommodity(0)
}

func (x *StreamStakingRatesServiceResponseV1) GetInterval() *StakingRatesInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *StreamStakingRatesServiceResponseV1) GetComposition() *StakingRatesComposition {
	if x != nil {
		return x.Composition
	}
	return nil
}

func (x *StreamStakingRatesServiceResponseV1) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamStakingRatesServiceResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

var File_sdk_stream_staking_rates_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_staking_rates_v1_response_proto_rawDesc = "" +
	"\n" +
	"*sdk/stream/staking_rates_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#sdk/stream/index_v1/commodity.proto\"\x88\x01\n" +
	"\x14StakingRatesInterval\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"|\n" +
	"\x14StakingRatesQuantity\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12#\n" +
	"\rbase_quantity\x18\x02 \x01(\x01R\fbaseQuantity\x12)\n" +
	"\x10utilization_rate\x18\x03 \x01(\x01R\x0futilizationRate\"~\n" +
	"\x1bStakingRatesUnderlyingPrice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x125\n" +
	"\bts_event\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\"\x99\x01\n" +
	"\x0fStakingRatesApr\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12%\n" +
	"\x0eforward_filled\x18\x03 \x01(\bR\rforwardFilled\x125\n" +
	"\bts_event\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\"\xd4\x01\n" +
	"\x17StakingRatesComposition\x12:\n" +
	"\bquantity\x18\x01 \x01(\v2\x1e.kaikosdk.StakingRatesQuantityR\bquantity\x12P\n" +
	"\x10underlying_price\x18\x02 \x01(\v2%.kaikosdk.StakingRatesUnderlyingPriceR\x0funderlyingPrice\x12+\n" +
	"\x03apr\x18\x03 \x01(\v2\x19.kaikosdk.StakingRatesAprR\x03apr\"\xd0\x02\n" +
	"#StreamStakingRatesServiceResponseV1\x12\x1d\n" +
	"\n" +
	"index_code\x18\x01 \x01(\tR\tindexCode\x12<\n" +
	"\tcommodity\x18\x02 \x01(\x0e2\x1e.kaikosdk.StreamIndexCommodityR\tcommodity\x12:\n" +
	"\binterval\x18\x03 \x01(\v2\x1e.kaikosdk.StakingRatesIntervalR\binterval\x12C\n" +
	"\vcomposition\x18\x04 \x01(\v2!.kaikosdk.StakingRatesCompositionR\vcomposition\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x125\n" +
	"\bts_event\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\atsEventB\x96\x01\n" +
	"%com.kaiko.sdk.stream.staking_rates_v1P\x01ZJgithub.com/kaikodata/kaiko-go-sdk/stream/staking_rates_v1;staking_rates_v1\xaa\x02\x1eKaikoSdk.Stream.StakingRatesV1b\x06proto3"

var (
	file_sdk_stream_staking_rates_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_staking_rates_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_staking_rates_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_staking_rates_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_staking_rates_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_staking_rates_v1_response_proto_rawDesc), len(file_sdk_stream_staking_rates_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_staking_rates_v1_response_proto_rawDescData
}

var file_sdk_stream_staking_rates_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sdk_stream_staking_rates_v1_response_proto_goTypes = []any{
	(*StakingRatesInterval)(nil),                // 0: kaikosdk.StakingRatesInterval
	(*StakingRatesQuantity)(nil),                // 1: kaikosdk.StakingRatesQuantity
	(*StakingRatesUnderlyingPrice)(nil),         // 2: kaikosdk.StakingRatesUnderlyingPrice
	(*StakingRatesApr)(nil),                     // 3: kaikosdk.StakingRatesApr
	(*StakingRatesComposition)(nil),             // 4: kaikosdk.StakingRatesComposition
	(*StreamStakingRatesServiceResponseV1)(nil), // 5: kaikosdk.StreamStakingRatesServiceResponseV1
	(*timestamppb.Timestamp)(nil),               // 6: google.protobuf.Timestamp
	(index_v1.StreamIndexCommodity)(0),          // 7: kaikosdk.StreamIndexCommodity
}
var file_sdk_stream_staking_rates_v1_response_proto_depIdxs = []int32{
	6,  // 0: kaikosdk.StakingRatesInterval.start_time:type_name -> google.protobuf.Timestamp
	6,  // 1: kaikosdk.StakingRatesInterval.end_time:type_name -> google.protobuf.Timestamp
	6,  // 2: kaikosdk.StakingRatesUnderlyingPrice.ts_event:type_name -> google.protobuf.Timestamp
	6,  // 3: kaikosdk.StakingRatesApr.ts_event:type_name -> google.protobuf.Timestamp
	1,  // 4: kaikosdk.StakingRatesComposition.quantity:type_name -> kaikosdk.StakingRatesQuantity
	2,  // 5: kaikosdk.StakingRatesComposition.underlying_price:type_name -> kaikosdk.StakingRatesUnderlyingPrice
	3,  // 6: kaikosdk.StakingRatesComposition.apr:type_name -> kaikosdk.StakingRatesApr
	7,  // 7: kaikosdk.StreamStakingRatesServiceResponseV1.commodity:type_name -> kaikosdk.StreamIndexCommodity
	0,  // 8: kaikosdk.StreamStakingRatesServiceResponseV1.interval:type_name -> kaikosdk.StakingRatesInterval
	4,  // 9: kaikosdk.StreamStakingRatesServiceResponseV1.composition:type_name -> kaikosdk.StakingRatesComposition
	6,  // 10: kaikosdk.StreamStakingRatesServiceResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sdk_stream_staking_rates_v1_response_proto_init() }
func file_sdk_stream_staking_rates_v1_response_proto_init() {
	if File_sdk_stream_staking_rates_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_staking_rates_v1_response_proto_rawDesc), len(file_sdk_stream_staking_rates_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_staking_rates_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_staking_rates_v1_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_staking_rates_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_staking_rates_v1_response_proto = out.File
	file_sdk_stream_staking_rates_v1_response_proto_goTypes = nil
	file_sdk_stream_staking_rates_v1_response_proto_depIdxs = nil
}
