// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/derivatives_instrument_metrics_v1/response.proto

package derivatives_instrument_metrics_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamDerivativesInstrumentMetricsResponseV1 derivatives v1 response.
type StreamDerivativesInstrumentMetricsResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value of the commodity.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Legacy symbol.
	LegacySymbol string `protobuf:"bytes,2,opt,name=legacy_symbol,json=legacySymbol,proto3" json:"legacy_symbol,omitempty"`
	// Exchange.
	Exchange string `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Commodity.
	// See https://docs.kaiko.com/v/kaiko-rest-api/market-data/derivatives/derivatives-metrics/risk#fields
	// and https://docs.kaiko.com/v/kaiko-rest-api/market-data/derivatives/derivatives-metrics/price#fields.
	Commodity string `protobuf:"bytes,4,opt,name=commodity,proto3" json:"commodity,omitempty"`
	// Kind of commodity (price of risk).
	CommodityKind StreamDerivativesInstrumentCommodityKindV1 `protobuf:"varint,5,opt,name=commodity_kind,json=commodityKind,proto3,enum=kaikosdk.StreamDerivativesInstrumentCommodityKindV1" json:"commodity_kind,omitempty"`
	// Timestamp of collection (event entered Kaiko's infrastructure), before nomalization.
	TsCollection *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts_collection,json=tsCollection,proto3" json:"ts_collection,omitempty"`
	// Event generation timestamp (event created by Kaiko), after normalization.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) Reset() {
	*x = StreamDerivativesInstrumentMetricsResponseV1{}
	mi := &file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDerivativesInstrumentMetricsResponseV1) ProtoMessage() {}

func (x *StreamDerivativesInstrumentMetricsResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDerivativesInstrumentMetricsResponseV1.ProtoReflect.Descriptor instead.
func (*StreamDerivativesInstrumentMetricsResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) GetLegacySymbol() string {
	if x != nil {
		return x.LegacySymbol
	}
	return ""
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) GetCommodity() string {
	if x != nil {
		return x.Commodity
	}
	return ""
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) GetCommodityKind() StreamDerivativesInstrumentCommodityKindV1 {
	if x != nil {
		return x.CommodityKind
	}
	return StreamDerivativesInstrumentCommodityKindV1_SDICK_UNKNOWN
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) GetTsCollection() *timestamppb.Timestamp {
	if x != nil {
		return x.TsCollection
	}
	return nil
}

func (x *StreamDerivativesInstrumentMetricsResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

var File_sdk_stream_derivatives_instrument_metrics_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDesc = "" +
	"\n" +
	";sdk/stream/derivatives_instrument_metrics_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1aAsdk/stream/derivatives_instrument_metrics_v1/commodity_kind.proto\"\xf8\x02\n" +
	",StreamDerivativesInstrumentMetricsResponseV1\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12#\n" +
	"\rlegacy_symbol\x18\x02 \x01(\tR\flegacySymbol\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x1c\n" +
	"\tcommodity\x18\x04 \x01(\tR\tcommodity\x12[\n" +
	"\x0ecommodity_kind\x18\x05 \x01(\x0e24.kaikosdk.StreamDerivativesInstrumentCommodityKindV1R\rcommodityKind\x12?\n" +
	"\rts_collection\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ftsCollection\x125\n" +
	"\bts_event\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\atsEventB\xd9\x01\n" +
	"6com.kaiko.sdk.stream.derivatives_instrument_metrics_v1P\x01Zlgithub.com/kaikodata/kaiko-go-sdk/stream/derivatives_instrument_metrics_v1;derivatives_instrument_metrics_v1\xaa\x02.KaikoSdk.Stream.DerivativesInstrumentMetricsV1b\x06proto3"

var (
	file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDesc), len(file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDescData
}

var file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_goTypes = []any{
	(*StreamDerivativesInstrumentMetricsResponseV1)(nil), // 0: kaikosdk.StreamDerivativesInstrumentMetricsResponseV1
	(StreamDerivativesInstrumentCommodityKindV1)(0),      // 1: kaikosdk.StreamDerivativesInstrumentCommodityKindV1
	(*timestamppb.Timestamp)(nil),                        // 2: google.protobuf.Timestamp
}
var file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamDerivativesInstrumentMetricsResponseV1.commodity_kind:type_name -> kaikosdk.StreamDerivativesInstrumentCommodityKindV1
	2, // 1: kaikosdk.StreamDerivativesInstrumentMetricsResponseV1.ts_collection:type_name -> google.protobuf.Timestamp
	2, // 2: kaikosdk.StreamDerivativesInstrumentMetricsResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_init() }
func file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_init() {
	if File_sdk_stream_derivatives_instrument_metrics_v1_response_proto != nil {
		return
	}
	file_sdk_stream_derivatives_instrument_metrics_v1_commodity_kind_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDesc), len(file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_derivatives_instrument_metrics_v1_response_proto = out.File
	file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_goTypes = nil
	file_sdk_stream_derivatives_instrument_metrics_v1_response_proto_depIdxs = nil
}
