// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/aggregated_state_price_v1/response.proto

package aggregated_state_price_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamAggregatedStatePriceResponseV1
type StreamAggregatedStatePriceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// datetime is the timestamp of the datapoint
	Datetime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	// base is the base currency of the pair
	Base string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	// aggregated_price_usd is the aggregated price in USD
	AggregatedPriceUsd string `protobuf:"bytes,3,opt,name=aggregated_price_usd,json=aggregatedPriceUsd,proto3" json:"aggregated_price_usd,omitempty"`
	// aggregated_price_lst is the aggregated price in LST quote token
	AggregatedPriceLst string `protobuf:"bytes,4,opt,name=aggregated_price_lst,json=aggregatedPriceLst,proto3" json:"aggregated_price_lst,omitempty"`
	// ts_event is the timestamp of the event
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	// lst_quote is the lst quote currency
	LstQuote string `protobuf:"bytes,6,opt,name=lst_quote,json=lstQuote,proto3" json:"lst_quote,omitempty"`
	// aggregated_market_depth_m1_usd is the aggregated market depth in USD -1%
	AggregatedMarketDepthM1Usd string `protobuf:"bytes,7,opt,name=aggregated_market_depth_m1_usd,json=aggregatedMarketDepthM1Usd,proto3" json:"aggregated_market_depth_m1_usd,omitempty"`
	// aggregated_market_depth_p1_usd is the aggregated market depth in USD +1%
	AggregatedMarketDepthP1Usd string `protobuf:"bytes,8,opt,name=aggregated_market_depth_p1_usd,json=aggregatedMarketDepthP1Usd,proto3" json:"aggregated_market_depth_p1_usd,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StreamAggregatedStatePriceResponseV1) Reset() {
	*x = StreamAggregatedStatePriceResponseV1{}
	mi := &file_sdk_stream_aggregated_state_price_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatedStatePriceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatedStatePriceResponseV1) ProtoMessage() {}

func (x *StreamAggregatedStatePriceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_aggregated_state_price_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatedStatePriceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamAggregatedStatePriceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_aggregated_state_price_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAggregatedStatePriceResponseV1) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *StreamAggregatedStatePriceResponseV1) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *StreamAggregatedStatePriceResponseV1) GetAggregatedPriceUsd() string {
	if x != nil {
		return x.AggregatedPriceUsd
	}
	return ""
}

func (x *StreamAggregatedStatePriceResponseV1) GetAggregatedPriceLst() string {
	if x != nil {
		return x.AggregatedPriceLst
	}
	return ""
}

func (x *StreamAggregatedStatePriceResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

func (x *StreamAggregatedStatePriceResponseV1) GetLstQuote() string {
	if x != nil {
		return x.LstQuote
	}
	return ""
}

func (x *StreamAggregatedStatePriceResponseV1) GetAggregatedMarketDepthM1Usd() string {
	if x != nil {
		return x.AggregatedMarketDepthM1Usd
	}
	return ""
}

func (x *StreamAggregatedStatePriceResponseV1) GetAggregatedMarketDepthP1Usd() string {
	if x != nil {
		return x.AggregatedMarketDepthP1Usd
	}
	return ""
}

var File_sdk_stream_aggregated_state_price_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_aggregated_state_price_v1_response_proto_rawDesc = "" +
	"\n" +
	"3sdk/stream/aggregated_state_price_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x03\n" +
	"$StreamAggregatedStatePriceResponseV1\x126\n" +
	"\bdatetime\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x12\n" +
	"\x04base\x18\x02 \x01(\tR\x04base\x120\n" +
	"\x14aggregated_price_usd\x18\x03 \x01(\tR\x12aggregatedPriceUsd\x120\n" +
	"\x14aggregated_price_lst\x18\x04 \x01(\tR\x12aggregatedPriceLst\x125\n" +
	"\bts_event\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x12\x1b\n" +
	"\tlst_quote\x18\x06 \x01(\tR\blstQuote\x12B\n" +
	"\x1eaggregated_market_depth_m1_usd\x18\a \x01(\tR\x1aaggregatedMarketDepthM1Usd\x12B\n" +
	"\x1eaggregated_market_depth_p1_usd\x18\b \x01(\tR\x1aaggregatedMarketDepthP1UsdB\xb9\x01\n" +
	".com.kaiko.sdk.stream.aggregated_state_price_v1P\x01Z\\github.com/kaikodata/kaiko-go-sdk/stream/aggregated_state_price_v1;aggregated_state_price_v1\xaa\x02&KaikoSdk.Stream.AggregatedStatePriceV1b\x06proto3"

var (
	file_sdk_stream_aggregated_state_price_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_aggregated_state_price_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_aggregated_state_price_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_aggregated_state_price_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_aggregated_state_price_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregated_state_price_v1_response_proto_rawDesc), len(file_sdk_stream_aggregated_state_price_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_aggregated_state_price_v1_response_proto_rawDescData
}

var file_sdk_stream_aggregated_state_price_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_stream_aggregated_state_price_v1_response_proto_goTypes = []any{
	(*StreamAggregatedStatePriceResponseV1)(nil), // 0: kaikosdk.StreamAggregatedStatePriceResponseV1
	(*timestamppb.Timestamp)(nil),                // 1: google.protobuf.Timestamp
}
var file_sdk_stream_aggregated_state_price_v1_response_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamAggregatedStatePriceResponseV1.datetime:type_name -> google.protobuf.Timestamp
	1, // 1: kaikosdk.StreamAggregatedStatePriceResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sdk_stream_aggregated_state_price_v1_response_proto_init() }
func file_sdk_stream_aggregated_state_price_v1_response_proto_init() {
	if File_sdk_stream_aggregated_state_price_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregated_state_price_v1_response_proto_rawDesc), len(file_sdk_stream_aggregated_state_price_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_aggregated_state_price_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_aggregated_state_price_v1_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_aggregated_state_price_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_aggregated_state_price_v1_response_proto = out.File
	file_sdk_stream_aggregated_state_price_v1_response_proto_goTypes = nil
	file_sdk_stream_aggregated_state_price_v1_response_proto_depIdxs = nil
}
