// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/aggregated_quote_v2/response.proto

package aggregated_quote_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType is event category for a value.
type StreamAggregatedQuoteResponseV2_EventType int32

const (
	// Unknown type.
	StreamAggregatedQuoteResponseV2_UNKNOWN StreamAggregatedQuoteResponseV2_EventType = 0
	// BEST_ASK type.
	StreamAggregatedQuoteResponseV2_BEST_ASK StreamAggregatedQuoteResponseV2_EventType = 1
	// BEST_BID type.
	StreamAggregatedQuoteResponseV2_BEST_BID StreamAggregatedQuoteResponseV2_EventType = 2
)

// Enum value maps for StreamAggregatedQuoteResponseV2_EventType.
var (
	StreamAggregatedQuoteResponseV2_EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "BEST_ASK",
		2: "BEST_BID",
	}
	StreamAggregatedQuoteResponseV2_EventType_value = map[string]int32{
		"UNKNOWN":  0,
		"BEST_ASK": 1,
		"BEST_BID": 2,
	}
)

func (x StreamAggregatedQuoteResponseV2_EventType) Enum() *StreamAggregatedQuoteResponseV2_EventType {
	p := new(StreamAggregatedQuoteResponseV2_EventType)
	*p = x
	return p
}

func (x StreamAggregatedQuoteResponseV2_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamAggregatedQuoteResponseV2_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_aggregated_quote_v2_response_proto_enumTypes[0].Descriptor()
}

func (StreamAggregatedQuoteResponseV2_EventType) Type() protoreflect.EnumType {
	return &file_sdk_stream_aggregated_quote_v2_response_proto_enumTypes[0]
}

func (x StreamAggregatedQuoteResponseV2_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamAggregatedQuoteResponseV2_EventType.Descriptor instead.
func (StreamAggregatedQuoteResponseV2_EventType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_aggregated_quote_v2_response_proto_rawDescGZIP(), []int{1, 0}
}

// StreamAggregatedQuoteValue is wrapper for update values.
type StreamAggregatedQuoteValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price of top of book entry.
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// Volume of top of book entry.
	Volume        string `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAggregatedQuoteValue) Reset() {
	*x = StreamAggregatedQuoteValue{}
	mi := &file_sdk_stream_aggregated_quote_v2_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatedQuoteValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatedQuoteValue) ProtoMessage() {}

func (x *StreamAggregatedQuoteValue) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_aggregated_quote_v2_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatedQuoteValue.ProtoReflect.Descriptor instead.
func (*StreamAggregatedQuoteValue) Descriptor() ([]byte, []int) {
	return file_sdk_stream_aggregated_quote_v2_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAggregatedQuoteValue) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *StreamAggregatedQuoteValue) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

// StreamAggregatedQuoteResponseV2
type StreamAggregatedQuoteResponseV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregate (interval).
	Aggregate string `protobuf:"bytes,1,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	// Instrument class. See https://docs.kaiko.com/?python#instruments.
	InstrumentClass string `protobuf:"bytes,2,opt,name=instrument_class,json=instrumentClass,proto3" json:"instrument_class,omitempty"`
	// Instrument code. See https://docs.kaiko.com/?python#instruments.
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// Event type is ASK or BID.
	EventType StreamAggregatedQuoteResponseV2_EventType `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=kaikosdk.StreamAggregatedQuoteResponseV2_EventType" json:"event_type,omitempty"`
	// Timestamp of event.
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	// Vetted is update value (price and volume) using Kaiko vetted exchanges list.
	// Field is absent if the ticker has no update during the aggregate inerval or asset is not covered by vetted exchange list.
	Vetted *StreamAggregatedQuoteValue `protobuf:"bytes,6,opt,name=vetted,proto3" json:"vetted,omitempty"`
	// Unvetted value is same as value, but includes all exchanges covered by Kaiko Top Of Book Stream for computation.
	// This should be used whenever an asset is not part of the vetted list.
	Unvetted      *StreamAggregatedQuoteValue `protobuf:"bytes,7,opt,name=unvetted,proto3" json:"unvetted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAggregatedQuoteResponseV2) Reset() {
	*x = StreamAggregatedQuoteResponseV2{}
	mi := &file_sdk_stream_aggregated_quote_v2_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatedQuoteResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatedQuoteResponseV2) ProtoMessage() {}

func (x *StreamAggregatedQuoteResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_aggregated_quote_v2_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatedQuoteResponseV2.ProtoReflect.Descriptor instead.
func (*StreamAggregatedQuoteResponseV2) Descriptor() ([]byte, []int) {
	return file_sdk_stream_aggregated_quote_v2_response_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAggregatedQuoteResponseV2) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

func (x *StreamAggregatedQuoteResponseV2) GetInstrumentClass() string {
	if x != nil {
		return x.InstrumentClass
	}
	return ""
}

func (x *StreamAggregatedQuoteResponseV2) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamAggregatedQuoteResponseV2) GetEventType() StreamAggregatedQuoteResponseV2_EventType {
	if x != nil {
		return x.EventType
	}
	return StreamAggregatedQuoteResponseV2_UNKNOWN
}

func (x *StreamAggregatedQuoteResponseV2) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

func (x *StreamAggregatedQuoteResponseV2) GetVetted() *StreamAggregatedQuoteValue {
	if x != nil {
		return x.Vetted
	}
	return nil
}

func (x *StreamAggregatedQuoteResponseV2) GetUnvetted() *StreamAggregatedQuoteValue {
	if x != nil {
		return x.Unvetted
	}
	return nil
}

var File_sdk_stream_aggregated_quote_v2_response_proto protoreflect.FileDescriptor

const file_sdk_stream_aggregated_quote_v2_response_proto_rawDesc = "" +
	"\n" +
	"-sdk/stream/aggregated_quote_v2/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x1aStreamAggregatedQuoteValue\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\tR\x06volume\"\xbf\x03\n" +
	"\x1fStreamAggregatedQuoteResponseV2\x12\x1c\n" +
	"\taggregate\x18\x01 \x01(\tR\taggregate\x12)\n" +
	"\x10instrument_class\x18\x02 \x01(\tR\x0finstrumentClass\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12R\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e23.kaikosdk.StreamAggregatedQuoteResponseV2.EventTypeR\teventType\x125\n" +
	"\bts_event\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x12<\n" +
	"\x06vetted\x18\x06 \x01(\v2$.kaikosdk.StreamAggregatedQuoteValueR\x06vetted\x12@\n" +
	"\bunvetted\x18\a \x01(\v2$.kaikosdk.StreamAggregatedQuoteValueR\bunvetted\"4\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bBEST_ASK\x10\x01\x12\f\n" +
	"\bBEST_BID\x10\x02B\xa2\x01\n" +
	"(com.kaiko.sdk.stream.aggregated_quote_v2P\x01ZPgithub.com/kaikodata/kaiko-go-sdk/stream/aggregated_quote_v2;aggregated_quote_v2\xaa\x02!KaikoSdk.Stream.AggregatedQuoteV2b\x06proto3"

var (
	file_sdk_stream_aggregated_quote_v2_response_proto_rawDescOnce sync.Once
	file_sdk_stream_aggregated_quote_v2_response_proto_rawDescData []byte
)

func file_sdk_stream_aggregated_quote_v2_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_aggregated_quote_v2_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_aggregated_quote_v2_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregated_quote_v2_response_proto_rawDesc), len(file_sdk_stream_aggregated_quote_v2_response_proto_rawDesc)))
	})
	return file_sdk_stream_aggregated_quote_v2_response_proto_rawDescData
}

var file_sdk_stream_aggregated_quote_v2_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_aggregated_quote_v2_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_stream_aggregated_quote_v2_response_proto_goTypes = []any{
	(StreamAggregatedQuoteResponseV2_EventType)(0), // 0: kaikosdk.StreamAggregatedQuoteResponseV2.EventType
	(*StreamAggregatedQuoteValue)(nil),             // 1: kaikosdk.StreamAggregatedQuoteValue
	(*StreamAggregatedQuoteResponseV2)(nil),        // 2: kaikosdk.StreamAggregatedQuoteResponseV2
	(*timestamppb.Timestamp)(nil),                  // 3: google.protobuf.Timestamp
}
var file_sdk_stream_aggregated_quote_v2_response_proto_depIdxs = []int32{
	0, // 0: kaikosdk.StreamAggregatedQuoteResponseV2.event_type:type_name -> kaikosdk.StreamAggregatedQuoteResponseV2.EventType
	3, // 1: kaikosdk.StreamAggregatedQuoteResponseV2.ts_event:type_name -> google.protobuf.Timestamp
	1, // 2: kaikosdk.StreamAggregatedQuoteResponseV2.vetted:type_name -> kaikosdk.StreamAggregatedQuoteValue
	1, // 3: kaikosdk.StreamAggregatedQuoteResponseV2.unvetted:type_name -> kaikosdk.StreamAggregatedQuoteValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sdk_stream_aggregated_quote_v2_response_proto_init() }
func file_sdk_stream_aggregated_quote_v2_response_proto_init() {
	if File_sdk_stream_aggregated_quote_v2_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregated_quote_v2_response_proto_rawDesc), len(file_sdk_stream_aggregated_quote_v2_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_aggregated_quote_v2_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_aggregated_quote_v2_response_proto_depIdxs,
		EnumInfos:         file_sdk_stream_aggregated_quote_v2_response_proto_enumTypes,
		MessageInfos:      file_sdk_stream_aggregated_quote_v2_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_aggregated_quote_v2_response_proto = out.File
	file_sdk_stream_aggregated_quote_v2_response_proto_goTypes = nil
	file_sdk_stream_aggregated_quote_v2_response_proto_depIdxs = nil
}
