// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/index_v1/commodity.proto

package index_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamIndexCommodity allows selecting kind of index update wanted.
type StreamIndexCommodity int32

const (
	// Unknown commodity.
	StreamIndexCommodity_SIC_UNKNOWN StreamIndexCommodity = 0
	// REAL_TIME commodity.
	StreamIndexCommodity_SIC_REAL_TIME StreamIndexCommodity = 1
	// DAILY_FIXING commodity.
	StreamIndexCommodity_SIC_DAILY_FIXING StreamIndexCommodity = 2
)

// Enum value maps for StreamIndexCommodity.
var (
	StreamIndexCommodity_name = map[int32]string{
		0: "SIC_UNKNOWN",
		1: "SIC_REAL_TIME",
		2: "SIC_DAILY_FIXING",
	}
	StreamIndexCommodity_value = map[string]int32{
		"SIC_UNKNOWN":      0,
		"SIC_REAL_TIME":    1,
		"SIC_DAILY_FIXING": 2,
	}
)

func (x StreamIndexCommodity) Enum() *StreamIndexCommodity {
	p := new(StreamIndexCommodity)
	*p = x
	return p
}

func (x StreamIndexCommodity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamIndexCommodity) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_index_v1_commodity_proto_enumTypes[0].Descriptor()
}

func (StreamIndexCommodity) Type() protoreflect.EnumType {
	return &file_sdk_stream_index_v1_commodity_proto_enumTypes[0]
}

func (x StreamIndexCommodity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamIndexCommodity.Descriptor instead.
func (StreamIndexCommodity) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_commodity_proto_rawDescGZIP(), []int{0}
}

var File_sdk_stream_index_v1_commodity_proto protoreflect.FileDescriptor

const file_sdk_stream_index_v1_commodity_proto_rawDesc = "" +
	"\n" +
	"#sdk/stream/index_v1/commodity.proto\x12\bkaikosdk*P\n" +
	"\x14StreamIndexCommodity\x12\x0f\n" +
	"\vSIC_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSIC_REAL_TIME\x10\x01\x12\x14\n" +
	"\x10SIC_DAILY_FIXING\x10\x02Bw\n" +
	"\x1dcom.kaiko.sdk.stream.index_v1P\x01Z:github.com/kaikodata/kaiko-go-sdk/stream/index_v1;index_v1\xaa\x02\x17KaikoSdk.Stream.IndexV1b\x06proto3"

var (
	file_sdk_stream_index_v1_commodity_proto_rawDescOnce sync.Once
	file_sdk_stream_index_v1_commodity_proto_rawDescData []byte
)

func file_sdk_stream_index_v1_commodity_proto_rawDescGZIP() []byte {
	file_sdk_stream_index_v1_commodity_proto_rawDescOnce.Do(func() {
		file_sdk_stream_index_v1_commodity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_index_v1_commodity_proto_rawDesc), len(file_sdk_stream_index_v1_commodity_proto_rawDesc)))
	})
	return file_sdk_stream_index_v1_commodity_proto_rawDescData
}

var file_sdk_stream_index_v1_commodity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_index_v1_commodity_proto_goTypes = []any{
	(StreamIndexCommodity)(0), // 0: kaikosdk.StreamIndexCommodity
}
var file_sdk_stream_index_v1_commodity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_stream_index_v1_commodity_proto_init() }
func file_sdk_stream_index_v1_commodity_proto_init() {
	if File_sdk_stream_index_v1_commodity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_index_v1_commodity_proto_rawDesc), len(file_sdk_stream_index_v1_commodity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_index_v1_commodity_proto_goTypes,
		DependencyIndexes: file_sdk_stream_index_v1_commodity_proto_depIdxs,
		EnumInfos:         file_sdk_stream_index_v1_commodity_proto_enumTypes,
	}.Build()
	File_sdk_stream_index_v1_commodity_proto = out.File
	file_sdk_stream_index_v1_commodity_proto_goTypes = nil
	file_sdk_stream_index_v1_commodity_proto_depIdxs = nil
}
