// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/index_v1/response.proto

package index_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamIndexServiceResponsePercentage is computation result by percentage.
type StreamIndexServiceResponsePercentage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Percentage.
	Percentage float64 `protobuf:"fixed64,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	// Price computed for the whole percentage.
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// Detailed computation by pairs.
	Pairs         []*StreamIndexServiceResponsePairs `protobuf:"bytes,3,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIndexServiceResponsePercentage) Reset() {
	*x = StreamIndexServiceResponsePercentage{}
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexServiceResponsePercentage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexServiceResponsePercentage) ProtoMessage() {}

func (x *StreamIndexServiceResponsePercentage) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexServiceResponsePercentage.ProtoReflect.Descriptor instead.
func (*StreamIndexServiceResponsePercentage) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamIndexServiceResponsePercentage) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *StreamIndexServiceResponsePercentage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamIndexServiceResponsePercentage) GetPairs() []*StreamIndexServiceResponsePairs {
	if x != nil {
		return x.Pairs
	}
	return nil
}

// StreamIndexServiceResponsePairs is computation result by pairs.
type StreamIndexServiceResponsePairs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pair.
	Pair string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	// Weight (for multiple assets indices).
	Weight float64 `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// Detailed computation by instruments.
	Instruments   []*StreamIndexServiceResponseInstruments `protobuf:"bytes,3,rep,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIndexServiceResponsePairs) Reset() {
	*x = StreamIndexServiceResponsePairs{}
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexServiceResponsePairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexServiceResponsePairs) ProtoMessage() {}

func (x *StreamIndexServiceResponsePairs) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexServiceResponsePairs.ProtoReflect.Descriptor instead.
func (*StreamIndexServiceResponsePairs) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *StreamIndexServiceResponsePairs) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *StreamIndexServiceResponsePairs) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *StreamIndexServiceResponsePairs) GetInstruments() []*StreamIndexServiceResponseInstruments {
	if x != nil {
		return x.Instruments
	}
	return nil
}

// StreamIndexServiceUnderlyingTrade is underlying trade information for a partition.
type StreamIndexServiceUnderlyingTrade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount / quantity of asset bought or sold, displayed in base currency.
	Volume float64 `protobuf:"fixed64,1,opt,name=volume,proto3" json:"volume,omitempty"`
	// Instrument exchange code, for example "cbse" (Coinbase).
	Exchange string `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Trade ID, empty string when not present.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Date of trade.
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIndexServiceUnderlyingTrade) Reset() {
	*x = StreamIndexServiceUnderlyingTrade{}
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexServiceUnderlyingTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexServiceUnderlyingTrade) ProtoMessage() {}

func (x *StreamIndexServiceUnderlyingTrade) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexServiceUnderlyingTrade.ProtoReflect.Descriptor instead.
func (*StreamIndexServiceUnderlyingTrade) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *StreamIndexServiceUnderlyingTrade) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StreamIndexServiceUnderlyingTrade) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StreamIndexServiceUnderlyingTrade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamIndexServiceUnderlyingTrade) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

// StreamIndexServiceResponseInstruments is computation result by instruments.
type StreamIndexServiceResponseInstruments struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Partition.
	Partition string `protobuf:"bytes,1,opt,name=partition,proto3" json:"partition,omitempty"`
	// Price.
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// Volume.
	Volume float64 `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	// Count.
	Count uint64 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// Underlying trade for the partition.
	UnderlyingTrade *StreamIndexServiceUnderlyingTrade `protobuf:"bytes,5,opt,name=underlying_trade,json=underlyingTrade,proto3" json:"underlying_trade,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamIndexServiceResponseInstruments) Reset() {
	*x = StreamIndexServiceResponseInstruments{}
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexServiceResponseInstruments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexServiceResponseInstruments) ProtoMessage() {}

func (x *StreamIndexServiceResponseInstruments) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexServiceResponseInstruments.ProtoReflect.Descriptor instead.
func (*StreamIndexServiceResponseInstruments) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_response_proto_rawDescGZIP(), []int{3}
}

func (x *StreamIndexServiceResponseInstruments) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *StreamIndexServiceResponseInstruments) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamIndexServiceResponseInstruments) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StreamIndexServiceResponseInstruments) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StreamIndexServiceResponseInstruments) GetUnderlyingTrade() *StreamIndexServiceUnderlyingTrade {
	if x != nil {
		return x.UnderlyingTrade
	}
	return nil
}

// StreamIndexServiceLastMicroPrice is the most recent microprice (last trade by
// datetime) observed in the computation. Populated only when VWM_TWAP
// forward-fill is enabled. The live consumer caches it and feeds it back as the
// next publication's seed so quiet-session leading gaps carry forward.
type StreamIndexServiceLastMicroPrice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price of the last trade.
	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	// Date of the last trade.
	LastTradeTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_trade_time,json=lastTradeTime,proto3" json:"last_trade_time,omitempty"`
	// Volume of the last trade.
	Volume float64 `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	// Instrument exchange code of the last trade.
	Exchange      string `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIndexServiceLastMicroPrice) Reset() {
	*x = StreamIndexServiceLastMicroPrice{}
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexServiceLastMicroPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexServiceLastMicroPrice) ProtoMessage() {}

func (x *StreamIndexServiceLastMicroPrice) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexServiceLastMicroPrice.ProtoReflect.Descriptor instead.
func (*StreamIndexServiceLastMicroPrice) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_response_proto_rawDescGZIP(), []int{4}
}

func (x *StreamIndexServiceLastMicroPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamIndexServiceLastMicroPrice) GetLastTradeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTradeTime
	}
	return nil
}

func (x *StreamIndexServiceLastMicroPrice) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StreamIndexServiceLastMicroPrice) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

// StreamIndexServiceResponseBaseAsset is base asset involved in computation.
type StreamIndexServiceResponseBaseAsset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Asset.
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Weight.
	Weight        float64 `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIndexServiceResponseBaseAsset) Reset() {
	*x = StreamIndexServiceResponseBaseAsset{}
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexServiceResponseBaseAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexServiceResponseBaseAsset) ProtoMessage() {}

func (x *StreamIndexServiceResponseBaseAsset) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexServiceResponseBaseAsset.ProtoReflect.Descriptor instead.
func (*StreamIndexServiceResponseBaseAsset) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_response_proto_rawDescGZIP(), []int{5}
}

func (x *StreamIndexServiceResponseBaseAsset) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *StreamIndexServiceResponseBaseAsset) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// FallbackInfo provides information about a fallback rate being used
type FallbackInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fallback used indicates whether a fallback rate was used (true) or not (false)
	FallbackUsed *bool `protobuf:"varint,1,opt,name=fallback_used,json=fallbackUsed,proto3,oneof" json:"fallback_used,omitempty"`
	// fallback source is the rate symbol that is used in case of fallback
	FallbackSource *string `protobuf:"bytes,2,opt,name=fallback_source,json=fallbackSource,proto3,oneof" json:"fallback_source,omitempty"`
	// fallback timestamp is the timestamp of the price that is used in the case of fallback
	FallbackTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=fallback_timestamp,json=fallbackTimestamp,proto3,oneof" json:"fallback_timestamp,omitempty"`
	// fallback interval is the computation window of the fallback source rate
	FallbackInterval *core.DataInterval `protobuf:"bytes,4,opt,name=fallback_interval,json=fallbackInterval,proto3" json:"fallback_interval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FallbackInfo) Reset() {
	*x = FallbackInfo{}
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FallbackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FallbackInfo) ProtoMessage() {}

func (x *FallbackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FallbackInfo.ProtoReflect.Descriptor instead.
func (*FallbackInfo) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_response_proto_rawDescGZIP(), []int{6}
}

func (x *FallbackInfo) GetFallbackUsed() bool {
	if x != nil && x.FallbackUsed != nil {
		return *x.FallbackUsed
	}
	return false
}

func (x *FallbackInfo) GetFallbackSource() string {
	if x != nil && x.FallbackSource != nil {
		return *x.FallbackSource
	}
	return ""
}

func (x *FallbackInfo) GetFallbackTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FallbackTimestamp
	}
	return nil
}

func (x *FallbackInfo) GetFallbackInterval() *core.DataInterval {
	if x != nil {
		return x.FallbackInterval
	}
	return nil
}

// StreamIndexServiceResponseV1
type StreamIndexServiceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index code.
	IndexCode string `protobuf:"bytes,1,opt,name=index_code,json=indexCode,proto3" json:"index_code,omitempty"`
	// Event type.
	Commodity StreamIndexCommodity `protobuf:"varint,2,opt,name=commodity,proto3,enum=kaikosdk.StreamIndexCommodity" json:"commodity,omitempty"`
	// Data interval.
	Interval *core.DataInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// Quote.
	Quote string `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	// Bases.
	Bases []*StreamIndexServiceResponseBaseAsset `protobuf:"bytes,5,rep,name=bases,proto3" json:"bases,omitempty"`
	// Exchanges.
	Exchanges []string `protobuf:"bytes,6,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	// Detailed computation by percentage.
	Percentages []*StreamIndexServiceResponsePercentage `protobuf:"bytes,7,rep,name=percentages,proto3" json:"percentages,omitempty"`
	// Event generation timestamp (event created by Kaiko), after normalization.
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	// Sequence ID for event. Sortable in lexicographic order.
	SequenceId string `protobuf:"bytes,9,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	// Last internal ingest date used for computation. Useful for replication purposes.
	LastIngestTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_ingest_time,json=lastIngestTime,proto3" json:"last_ingest_time,omitempty"`
	// Last internal anomaly detection ingest date used for computation. Useful for replication purposes.
	LastAnomalyIngestTime *core.TimestampValue `protobuf:"bytes,12,opt,name=last_anomaly_ingest_time,json=lastAnomalyIngestTime,proto3" json:"last_anomaly_ingest_time,omitempty"`
	// Describe fallback rate
	FallbackInfo *FallbackInfo `protobuf:"bytes,13,opt,name=fallback_info,json=fallbackInfo,proto3" json:"fallback_info,omitempty"`
	// Most recent microprice (last trade by datetime); set only when VWM_TWAP
	// forward-fill is enabled. Cached by the live consumer and fed back as the
	// next publication's forward-fill seed.
	LastMicroPrice *StreamIndexServiceLastMicroPrice `protobuf:"bytes,14,opt,name=last_micro_price,json=lastMicroPrice,proto3,oneof" json:"last_micro_price,omitempty"`
	// True when this publication is a restatement correcting a previously
	// published value.
	RestatementStatus *bool `protobuf:"varint,15,opt,name=restatement_status,json=restatementStatus,proto3,oneof" json:"restatement_status,omitempty"`
	// Identifier of the correction, shared by all publications restated together.
	CorrectionId *string `protobuf:"bytes,16,opt,name=correction_id,json=correctionId,proto3,oneof" json:"correction_id,omitempty"`
	// Publication time of the original, incorrect value being corrected.
	InitialPublicationTs *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=initial_publication_ts,json=initialPublicationTs,proto3,oneof" json:"initial_publication_ts,omitempty"`
	// Identifier of the incident that triggered the restatement.
	IncidentId    *string `protobuf:"bytes,18,opt,name=incident_id,json=incidentId,proto3,oneof" json:"incident_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIndexServiceResponseV1) Reset() {
	*x = StreamIndexServiceResponseV1{}
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexServiceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexServiceResponseV1) ProtoMessage() {}

func (x *StreamIndexServiceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_v1_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexServiceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamIndexServiceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_v1_response_proto_rawDescGZIP(), []int{7}
}

func (x *StreamIndexServiceResponseV1) GetIndexCode() string {
	if x != nil {
		return x.IndexCode
	}
	return ""
}

func (x *StreamIndexServiceResponseV1) GetCommodity() StreamIndexCommodity {
	if x != nil {
		return x.Commodity
	}
	return StreamIndexCommodity_SIC_UNKNOWN
}

func (x *StreamIndexServiceResponseV1) GetInterval() *core.DataInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *StreamIndexServiceResponseV1) GetBases() []*StreamIndexServiceResponseBaseAsset {
	if x != nil {
		return x.Bases
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetExchanges() []string {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetPercentages() []*StreamIndexServiceResponsePercentage {
	if x != nil {
		return x.Percentages
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *StreamIndexServiceResponseV1) GetLastIngestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastIngestTime
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetLastAnomalyIngestTime() *core.TimestampValue {
	if x != nil {
		return x.LastAnomalyIngestTime
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetFallbackInfo() *FallbackInfo {
	if x != nil {
		return x.FallbackInfo
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetLastMicroPrice() *StreamIndexServiceLastMicroPrice {
	if x != nil {
		return x.LastMicroPrice
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetRestatementStatus() bool {
	if x != nil && x.RestatementStatus != nil {
		return *x.RestatementStatus
	}
	return false
}

func (x *StreamIndexServiceResponseV1) GetCorrectionId() string {
	if x != nil && x.CorrectionId != nil {
		return *x.CorrectionId
	}
	return ""
}

func (x *StreamIndexServiceResponseV1) GetInitialPublicationTs() *timestamppb.Timestamp {
	if x != nil {
		return x.InitialPublicationTs
	}
	return nil
}

func (x *StreamIndexServiceResponseV1) GetIncidentId() string {
	if x != nil && x.IncidentId != nil {
		return *x.IncidentId
	}
	return ""
}

var File_sdk_stream_index_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_index_v1_response_proto_rawDesc = "" +
	"\n" +
	"\"sdk/stream/index_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1csdk/core/data_interval.proto\x1a\x17sdk/core/wrappers.proto\x1a#sdk/stream/index_v1/commodity.proto\"\x9d\x01\n" +
	"$StreamIndexServiceResponsePercentage\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x01R\n" +
	"percentage\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12?\n" +
	"\x05pairs\x18\x03 \x03(\v2).kaikosdk.StreamIndexServiceResponsePairsR\x05pairs\"\xa0\x01\n" +
	"\x1fStreamIndexServiceResponsePairs\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12Q\n" +
	"\vinstruments\x18\x03 \x03(\v2/.kaikosdk.StreamIndexServiceResponseInstrumentsR\vinstruments\"\x9f\x01\n" +
	"!StreamIndexServiceUnderlyingTrade\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\x01R\x06volume\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x126\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\"\xe1\x01\n" +
	"%StreamIndexServiceResponseInstruments\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\tR\tpartition\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\x12V\n" +
	"\x10underlying_trade\x18\x05 \x01(\v2+.kaikosdk.StreamIndexServiceUnderlyingTradeR\x0funderlyingTrade\"\xb0\x01\n" +
	" StreamIndexServiceLastMicroPrice\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12B\n" +
	"\x0flast_trade_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rlastTradeTime\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\"S\n" +
	"#StreamIndexServiceResponseBaseAsset\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"\xb8\x02\n" +
	"\fFallbackInfo\x12(\n" +
	"\rfallback_used\x18\x01 \x01(\bH\x00R\ffallbackUsed\x88\x01\x01\x12,\n" +
	"\x0ffallback_source\x18\x02 \x01(\tH\x01R\x0efallbackSource\x88\x01\x01\x12N\n" +
	"\x12fallback_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x11fallbackTimestamp\x88\x01\x01\x12C\n" +
	"\x11fallback_interval\x18\x04 \x01(\v2\x16.kaikosdk.DataIntervalR\x10fallbackIntervalB\x10\n" +
	"\x0e_fallback_usedB\x12\n" +
	"\x10_fallback_sourceB\x15\n" +
	"\x13_fallback_timestamp\"\xcd\b\n" +
	"\x1cStreamIndexServiceResponseV1\x12\x1d\n" +
	"\n" +
	"index_code\x18\x01 \x01(\tR\tindexCode\x12<\n" +
	"\tcommodity\x18\x02 \x01(\x0e2\x1e.kaikosdk.StreamIndexCommodityR\tcommodity\x122\n" +
	"\binterval\x18\x03 \x01(\v2\x16.kaikosdk.DataIntervalR\binterval\x12\x14\n" +
	"\x05quote\x18\x04 \x01(\tR\x05quote\x12C\n" +
	"\x05bases\x18\x05 \x03(\v2-.kaikosdk.StreamIndexServiceResponseBaseAssetR\x05bases\x12\x1c\n" +
	"\texchanges\x18\x06 \x03(\tR\texchanges\x12P\n" +
	"\vpercentages\x18\a \x03(\v2..kaikosdk.StreamIndexServiceResponsePercentageR\vpercentages\x125\n" +
	"\bts_event\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x12\x1f\n" +
	"\vsequence_id\x18\t \x01(\tR\n" +
	"sequenceId\x12D\n" +
	"\x10last_ingest_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0elastIngestTime\x12Q\n" +
	"\x18last_anomaly_ingest_time\x18\f \x01(\v2\x18.kaikosdk.TimestampValueR\x15lastAnomalyIngestTime\x12;\n" +
	"\rfallback_info\x18\r \x01(\v2\x16.kaikosdk.FallbackInfoR\ffallbackInfo\x12Y\n" +
	"\x10last_micro_price\x18\x0e \x01(\v2*.kaikosdk.StreamIndexServiceLastMicroPriceH\x00R\x0elastMicroPrice\x88\x01\x01\x122\n" +
	"\x12restatement_status\x18\x0f \x01(\bH\x01R\x11restatementStatus\x88\x01\x01\x12(\n" +
	"\rcorrection_id\x18\x10 \x01(\tH\x02R\fcorrectionId\x88\x01\x01\x12U\n" +
	"\x16initial_publication_ts\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x14initialPublicationTs\x88\x01\x01\x12$\n" +
	"\vincident_id\x18\x12 \x01(\tH\x04R\n" +
	"incidentId\x88\x01\x01B\x13\n" +
	"\x11_last_micro_priceB\x15\n" +
	"\x13_restatement_statusB\x10\n" +
	"\x0e_correction_idB\x19\n" +
	"\x17_initial_publication_tsB\x0e\n" +
	"\f_incident_idJ\x04\b\v\x10\fBw\n" +
	"\x1dcom.kaiko.sdk.stream.index_v1P\x01Z:github.com/kaikodata/kaiko-go-sdk/stream/index_v1;index_v1\xaa\x02\x17KaikoSdk.Stream.IndexV1b\x06proto3"

var (
	file_sdk_stream_index_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_index_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_index_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_index_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_index_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_index_v1_response_proto_rawDesc), len(file_sdk_stream_index_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_index_v1_response_proto_rawDescData
}

var file_sdk_stream_index_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sdk_stream_index_v1_response_proto_goTypes = []any{
	(*StreamIndexServiceResponsePercentage)(nil),  // 0: kaikosdk.StreamIndexServiceResponsePercentage
	(*StreamIndexServiceResponsePairs)(nil),       // 1: kaikosdk.StreamIndexServiceResponsePairs
	(*StreamIndexServiceUnderlyingTrade)(nil),     // 2: kaikosdk.StreamIndexServiceUnderlyingTrade
	(*StreamIndexServiceResponseInstruments)(nil), // 3: kaikosdk.StreamIndexServiceResponseInstruments
	(*StreamIndexServiceLastMicroPrice)(nil),      // 4: kaikosdk.StreamIndexServiceLastMicroPrice
	(*StreamIndexServiceResponseBaseAsset)(nil),   // 5: kaikosdk.StreamIndexServiceResponseBaseAsset
	(*FallbackInfo)(nil),                          // 6: kaikosdk.FallbackInfo
	(*StreamIndexServiceResponseV1)(nil),          // 7: kaikosdk.StreamIndexServiceResponseV1
	(*timestamppb.Timestamp)(nil),                 // 8: google.protobuf.Timestamp
	(*core.DataInterval)(nil),                     // 9: kaikosdk.DataInterval
	(StreamIndexCommodity)(0),                     // 10: kaikosdk.StreamIndexCommodity
	(*core.TimestampValue)(nil),                   // 11: kaikosdk.TimestampValue
}
var file_sdk_stream_index_v1_response_proto_depIdxs = []int32{
	1,  // 0: kaikosdk.StreamIndexServiceResponsePercentage.pairs:type_name -> kaikosdk.StreamIndexServiceResponsePairs
	3,  // 1: kaikosdk.StreamIndexServiceResponsePairs.instruments:type_name -> kaikosdk.StreamIndexServiceResponseInstruments
	8,  // 2: kaikosdk.StreamIndexServiceUnderlyingTrade.datetime:type_name -> google.protobuf.Timestamp
	2,  // 3: kaikosdk.StreamIndexServiceResponseInstruments.underlying_trade:type_name -> kaikosdk.StreamIndexServiceUnderlyingTrade
	8,  // 4: kaikosdk.StreamIndexServiceLastMicroPrice.last_trade_time:type_name -> google.protobuf.Timestamp
	8,  // 5: kaikosdk.FallbackInfo.fallback_timestamp:type_name -> google.protobuf.Timestamp
	9,  // 6: kaikosdk.FallbackInfo.fallback_interval:type_name -> kaikosdk.DataInterval
	10, // 7: kaikosdk.StreamIndexServiceResponseV1.commodity:type_name -> kaikosdk.StreamIndexCommodity
	9,  // 8: kaikosdk.StreamIndexServiceResponseV1.interval:type_name -> kaikosdk.DataInterval
	5,  // 9: kaikosdk.StreamIndexServiceResponseV1.bases:type_name -> kaikosdk.StreamIndexServiceResponseBaseAsset
	0,  // 10: kaikosdk.StreamIndexServiceResponseV1.percentages:type_name -> kaikosdk.StreamIndexServiceResponsePercentage
	8,  // 11: kaikosdk.StreamIndexServiceResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	8,  // 12: kaikosdk.StreamIndexServiceResponseV1.last_ingest_time:type_name -> google.protobuf.Timestamp
	11, // 13: kaikosdk.StreamIndexServiceResponseV1.last_anomaly_ingest_time:type_name -> kaikosdk.TimestampValue
	6,  // 14: kaikosdk.StreamIndexServiceResponseV1.fallback_info:type_name -> kaikosdk.FallbackInfo
	4,  // 15: kaikosdk.StreamIndexServiceResponseV1.last_micro_price:type_name -> kaikosdk.StreamIndexServiceLastMicroPrice
	8,  // 16: kaikosdk.StreamIndexServiceResponseV1.initial_publication_ts:type_name -> google.protobuf.Timestamp
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_sdk_stream_index_v1_response_proto_init() }
func file_sdk_stream_index_v1_response_proto_init() {
	if File_sdk_stream_index_v1_response_proto != nil {
		return
	}
	file_sdk_stream_index_v1_commodity_proto_init()
	file_sdk_stream_index_v1_response_proto_msgTypes[6].OneofWrappers = []any{}
	file_sdk_stream_index_v1_response_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_index_v1_response_proto_rawDesc), len(file_sdk_stream_index_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_index_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_index_v1_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_index_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_index_v1_response_proto = out.File
	file_sdk_stream_index_v1_response_proto_goTypes = nil
	file_sdk_stream_index_v1_response_proto_depIdxs = nil
}
