// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/compute_index_v1/response.proto

package compute_index_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Commodity is the publication type of a compute-index datapoint. Nested in the
// message so its value names (SIC_*) scope to this message and don't collide
// with the crypto StreamIndexCommodity's SIC_* values in the shared kaikosdk
// package.
type StreamComputeIndexServiceResponseV1_Commodity int32

const (
	// Unknown commodity.
	StreamComputeIndexServiceResponseV1_SIC_UNKNOWN StreamComputeIndexServiceResponseV1_Commodity = 0
	// Real-time commodity.
	StreamComputeIndexServiceResponseV1_SIC_REAL_TIME StreamComputeIndexServiceResponseV1_Commodity = 1
	// Hourly fixing commodity (reserved for the fixing work; not yet emitted).
	StreamComputeIndexServiceResponseV1_SIC_HOURLY_FIXING StreamComputeIndexServiceResponseV1_Commodity = 2
)

// Enum value maps for StreamComputeIndexServiceResponseV1_Commodity.
var (
	StreamComputeIndexServiceResponseV1_Commodity_name = map[int32]string{
		0: "SIC_UNKNOWN",
		1: "SIC_REAL_TIME",
		2: "SIC_HOURLY_FIXING",
	}
	StreamComputeIndexServiceResponseV1_Commodity_value = map[string]int32{
		"SIC_UNKNOWN":       0,
		"SIC_REAL_TIME":     1,
		"SIC_HOURLY_FIXING": 2,
	}
)

func (x StreamComputeIndexServiceResponseV1_Commodity) Enum() *StreamComputeIndexServiceResponseV1_Commodity {
	p := new(StreamComputeIndexServiceResponseV1_Commodity)
	*p = x
	return p
}

func (x StreamComputeIndexServiceResponseV1_Commodity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamComputeIndexServiceResponseV1_Commodity) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_compute_index_v1_response_proto_enumTypes[0].Descriptor()
}

func (StreamComputeIndexServiceResponseV1_Commodity) Type() protoreflect.EnumType {
	return &file_sdk_stream_compute_index_v1_response_proto_enumTypes[0]
}

func (x StreamComputeIndexServiceResponseV1_Commodity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamComputeIndexServiceResponseV1_Commodity.Descriptor instead.
func (StreamComputeIndexServiceResponseV1_Commodity) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_compute_index_v1_response_proto_rawDescGZIP(), []int{4, 0}
}

// ComputeIndexBaseAsset is a base asset in the computation. Compute indices are
// single-asset (one entry, weight 1); the list mirrors the crypto shape.
type ComputeIndexBaseAsset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Asset, for example "h100_st".
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Weight (always 1 for single-asset compute indices).
	Weight        float64 `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeIndexBaseAsset) Reset() {
	*x = ComputeIndexBaseAsset{}
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeIndexBaseAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeIndexBaseAsset) ProtoMessage() {}

func (x *ComputeIndexBaseAsset) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeIndexBaseAsset.ProtoReflect.Descriptor instead.
func (*ComputeIndexBaseAsset) Descriptor() ([]byte, []int) {
	return file_sdk_stream_compute_index_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeIndexBaseAsset) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *ComputeIndexBaseAsset) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// ComputeIndexBucket is one partition's contribution to the value: its
// volume-weighted median price, summed volume and observation count. This is the
// crypto per-partition breakdown flattened to the top level (compute is
// single-asset, so the percentages[]/pairs[] wrappers are dropped).
type ComputeIndexBucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Partition index within the window (0 = oldest).
	Partition uint32 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	// The partition's volume-weighted median price.
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// Summed volume (amount) of the partition's observations.
	Volume float64 `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	// Number of observations in the partition.
	Count uint32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// The underlying trade this partition's volume-weighted median resolves to.
	UnderlyingTrade *ComputeIndexUnderlyingTrade `protobuf:"bytes,5,opt,name=underlying_trade,json=underlyingTrade,proto3" json:"underlying_trade,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComputeIndexBucket) Reset() {
	*x = ComputeIndexBucket{}
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeIndexBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeIndexBucket) ProtoMessage() {}

func (x *ComputeIndexBucket) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeIndexBucket.ProtoReflect.Descriptor instead.
func (*ComputeIndexBucket) Descriptor() ([]byte, []int) {
	return file_sdk_stream_compute_index_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeIndexBucket) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ComputeIndexBucket) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ComputeIndexBucket) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *ComputeIndexBucket) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ComputeIndexBucket) GetUnderlyingTrade() *ComputeIndexUnderlyingTrade {
	if x != nil {
		return x.UnderlyingTrade
	}
	return nil
}

// ComputeIndexUnderlyingTrade is the provenance of the single underlying tick a
// partition's volume-weighted median resolves to.
type ComputeIndexUnderlyingTrade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The underlying data provider the tick was aggregated from (provider_id).
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// The tick's volume (amount / weight).
	Volume float64 `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	// The tick's synthetic id.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// The tick's observation time (the raw observed_at, presented as datetime for
	// JSON-shape parity with the other endpoints).
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeIndexUnderlyingTrade) Reset() {
	*x = ComputeIndexUnderlyingTrade{}
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeIndexUnderlyingTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeIndexUnderlyingTrade) ProtoMessage() {}

func (x *ComputeIndexUnderlyingTrade) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeIndexUnderlyingTrade.ProtoReflect.Descriptor instead.
func (*ComputeIndexUnderlyingTrade) Descriptor() ([]byte, []int) {
	return file_sdk_stream_compute_index_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *ComputeIndexUnderlyingTrade) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ComputeIndexUnderlyingTrade) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *ComputeIndexUnderlyingTrade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComputeIndexUnderlyingTrade) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

// ComputeIndexFallbackInfo describes whether the value is a forward-filled
// (fallback) value.
type ComputeIndexFallbackInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the value was carried forward because the window had no observations
	// (true) or freshly computed from live data (false).
	FallbackUsed bool `protobuf:"varint,1,opt,name=fallback_used,json=fallbackUsed,proto3" json:"fallback_used,omitempty"`
	// fallback_timestamp is the ts_event of the last-good datapoint whose value is
	// being carried forward. Set only when fallback_used is true.
	FallbackTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=fallback_timestamp,json=fallbackTimestamp,proto3" json:"fallback_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ComputeIndexFallbackInfo) Reset() {
	*x = ComputeIndexFallbackInfo{}
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeIndexFallbackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeIndexFallbackInfo) ProtoMessage() {}

func (x *ComputeIndexFallbackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeIndexFallbackInfo.ProtoReflect.Descriptor instead.
func (*ComputeIndexFallbackInfo) Descriptor() ([]byte, []int) {
	return file_sdk_stream_compute_index_v1_response_proto_rawDescGZIP(), []int{3}
}

func (x *ComputeIndexFallbackInfo) GetFallbackUsed() bool {
	if x != nil {
		return x.FallbackUsed
	}
	return false
}

func (x *ComputeIndexFallbackInfo) GetFallbackTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FallbackTimestamp
	}
	return nil
}

// StreamComputeIndexServiceResponseV1 is one computed compute-index datapoint,
// aligned to the Kaiko crypto single-asset rate output (index_v1).
type StreamComputeIndexServiceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index code, for example "KK_CMP_H100_ST_2SECTICK".
	IndexCode string `protobuf:"bytes,1,opt,name=index_code,json=indexCode,proto3" json:"index_code,omitempty"`
	// Publication type.
	Commodity StreamComputeIndexServiceResponseV1_Commodity `protobuf:"varint,2,opt,name=commodity,proto3,enum=kaikosdk.StreamComputeIndexServiceResponseV1_Commodity" json:"commodity,omitempty"`
	// Calculation window.
	Interval *core.DataInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// Quote currency; always "usd" for compute.
	Quote string `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	// Base asset(s); always a single asset at weight 1.
	Bases []*ComputeIndexBaseAsset `protobuf:"bytes,5,rep,name=bases,proto3" json:"bases,omitempty"`
	// Source exchange code(s), for example "sqrt" (Squaretower).
	Exchanges []string `protobuf:"bytes,6,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	// The index value (VWM + TWAP over the window). optional: omitted on a
	// sentinel (no value this window); present on real datapoints and fallbacks.
	Price *float64 `protobuf:"fixed64,7,opt,name=price,proto3,oneof" json:"price,omitempty"`
	// Methodology used, for example "vwm_twap".
	Methodology string `protobuf:"bytes,8,opt,name=methodology,proto3" json:"methodology,omitempty"`
	// Per-partition breakdown, most-recent partition first.
	Buckets []*ComputeIndexBucket `protobuf:"bytes,9,rep,name=buckets,proto3" json:"buckets,omitempty"`
	// Whether the value is a forward-filled/fallback value.
	FallbackInfo *ComputeIndexFallbackInfo `protobuf:"bytes,10,opt,name=fallback_info,json=fallbackInfo,proto3" json:"fallback_info,omitempty"`
	// Event generation timestamp: the datapoint's canonical time (end of the
	// calculation window).
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	// Sequence ID for the event, sortable in lexicographic order. Empty in preprod.
	SequenceId string `protobuf:"bytes,12,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	// Last internal ingest date used for the computation (data-freshness marker).
	LastIngestTime *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_ingest_time,json=lastIngestTime,proto3" json:"last_ingest_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamComputeIndexServiceResponseV1) Reset() {
	*x = StreamComputeIndexServiceResponseV1{}
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamComputeIndexServiceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamComputeIndexServiceResponseV1) ProtoMessage() {}

func (x *StreamComputeIndexServiceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_compute_index_v1_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamComputeIndexServiceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamComputeIndexServiceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_compute_index_v1_response_proto_rawDescGZIP(), []int{4}
}

func (x *StreamComputeIndexServiceResponseV1) GetIndexCode() string {
	if x != nil {
		return x.IndexCode
	}
	return ""
}

func (x *StreamComputeIndexServiceResponseV1) GetCommodity() StreamComputeIndexServiceResponseV1_Commodity {
	if x != nil {
		return x.Commodity
	}
	return StreamComputeIndexServiceResponseV1_SIC_UNKNOWN
}

func (x *StreamComputeIndexServiceResponseV1) GetInterval() *core.DataInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *StreamComputeIndexServiceResponseV1) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *StreamComputeIndexServiceResponseV1) GetBases() []*ComputeIndexBaseAsset {
	if x != nil {
		return x.Bases
	}
	return nil
}

func (x *StreamComputeIndexServiceResponseV1) GetExchanges() []string {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *StreamComputeIndexServiceResponseV1) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *StreamComputeIndexServiceResponseV1) GetMethodology() string {
	if x != nil {
		return x.Methodology
	}
	return ""
}

func (x *StreamComputeIndexServiceResponseV1) GetBuckets() []*ComputeIndexBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *StreamComputeIndexServiceResponseV1) GetFallbackInfo() *ComputeIndexFallbackInfo {
	if x != nil {
		return x.FallbackInfo
	}
	return nil
}

func (x *StreamComputeIndexServiceResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

func (x *StreamComputeIndexServiceResponseV1) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *StreamComputeIndexServiceResponseV1) GetLastIngestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastIngestTime
	}
	return nil
}

var File_sdk_stream_compute_index_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_compute_index_v1_response_proto_rawDesc = "" +
	"\n" +
	"*sdk/stream/compute_index_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1csdk/core/data_interval.proto\"E\n" +
	"\x15ComputeIndexBaseAsset\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"\xc8\x01\n" +
	"\x12ComputeIndexBucket\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x12P\n" +
	"\x10underlying_trade\x18\x05 \x01(\v2%.kaikosdk.ComputeIndexUnderlyingTradeR\x0funderlyingTrade\"\x99\x01\n" +
	"\x1bComputeIndexUnderlyingTrade\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x01R\x06volume\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x126\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\"\x8a\x01\n" +
	"\x18ComputeIndexFallbackInfo\x12#\n" +
	"\rfallback_used\x18\x01 \x01(\bR\ffallbackUsed\x12I\n" +
	"\x12fallback_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x11fallbackTimestamp\"\xe8\x05\n" +
	"#StreamComputeIndexServiceResponseV1\x12\x1d\n" +
	"\n" +
	"index_code\x18\x01 \x01(\tR\tindexCode\x12U\n" +
	"\tcommodity\x18\x02 \x01(\x0e27.kaikosdk.StreamComputeIndexServiceResponseV1.CommodityR\tcommodity\x122\n" +
	"\binterval\x18\x03 \x01(\v2\x16.kaikosdk.DataIntervalR\binterval\x12\x14\n" +
	"\x05quote\x18\x04 \x01(\tR\x05quote\x125\n" +
	"\x05bases\x18\x05 \x03(\v2\x1f.kaikosdk.ComputeIndexBaseAssetR\x05bases\x12\x1c\n" +
	"\texchanges\x18\x06 \x03(\tR\texchanges\x12\x19\n" +
	"\x05price\x18\a \x01(\x01H\x00R\x05price\x88\x01\x01\x12 \n" +
	"\vmethodology\x18\b \x01(\tR\vmethodology\x126\n" +
	"\abuckets\x18\t \x03(\v2\x1c.kaikosdk.ComputeIndexBucketR\abuckets\x12G\n" +
	"\rfallback_info\x18\n" +
	" \x01(\v2\".kaikosdk.ComputeIndexFallbackInfoR\ffallbackInfo\x125\n" +
	"\bts_event\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x12\x1f\n" +
	"\vsequence_id\x18\f \x01(\tR\n" +
	"sequenceId\x12D\n" +
	"\x10last_ingest_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0elastIngestTime\"F\n" +
	"\tCommodity\x12\x0f\n" +
	"\vSIC_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSIC_REAL_TIME\x10\x01\x12\x15\n" +
	"\x11SIC_HOURLY_FIXING\x10\x02B\b\n" +
	"\x06_priceB\x96\x01\n" +
	"%com.kaiko.sdk.stream.compute_index_v1P\x01ZJgithub.com/kaikodata/kaiko-go-sdk/stream/compute_index_v1;compute_index_v1\xaa\x02\x1eKaikoSdk.Stream.ComputeIndexV1b\x06proto3"

var (
	file_sdk_stream_compute_index_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_compute_index_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_compute_index_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_compute_index_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_compute_index_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_compute_index_v1_response_proto_rawDesc), len(file_sdk_stream_compute_index_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_compute_index_v1_response_proto_rawDescData
}

var file_sdk_stream_compute_index_v1_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_compute_index_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sdk_stream_compute_index_v1_response_proto_goTypes = []any{
	(StreamComputeIndexServiceResponseV1_Commodity)(0), // 0: kaikosdk.StreamComputeIndexServiceResponseV1.Commodity
	(*ComputeIndexBaseAsset)(nil),                      // 1: kaikosdk.ComputeIndexBaseAsset
	(*ComputeIndexBucket)(nil),                         // 2: kaikosdk.ComputeIndexBucket
	(*ComputeIndexUnderlyingTrade)(nil),                // 3: kaikosdk.ComputeIndexUnderlyingTrade
	(*ComputeIndexFallbackInfo)(nil),                   // 4: kaikosdk.ComputeIndexFallbackInfo
	(*StreamComputeIndexServiceResponseV1)(nil),        // 5: kaikosdk.StreamComputeIndexServiceResponseV1
	(*timestamppb.Timestamp)(nil),                      // 6: google.protobuf.Timestamp
	(*core.DataInterval)(nil),                          // 7: kaikosdk.DataInterval
}
var file_sdk_stream_compute_index_v1_response_proto_depIdxs = []int32{
	3,  // 0: kaikosdk.ComputeIndexBucket.underlying_trade:type_name -> kaikosdk.ComputeIndexUnderlyingTrade
	6,  // 1: kaikosdk.ComputeIndexUnderlyingTrade.datetime:type_name -> google.protobuf.Timestamp
	6,  // 2: kaikosdk.ComputeIndexFallbackInfo.fallback_timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: kaikosdk.StreamComputeIndexServiceResponseV1.commodity:type_name -> kaikosdk.StreamComputeIndexServiceResponseV1.Commodity
	7,  // 4: kaikosdk.StreamComputeIndexServiceResponseV1.interval:type_name -> kaikosdk.DataInterval
	1,  // 5: kaikosdk.StreamComputeIndexServiceResponseV1.bases:type_name -> kaikosdk.ComputeIndexBaseAsset
	2,  // 6: kaikosdk.StreamComputeIndexServiceResponseV1.buckets:type_name -> kaikosdk.ComputeIndexBucket
	4,  // 7: kaikosdk.StreamComputeIndexServiceResponseV1.fallback_info:type_name -> kaikosdk.ComputeIndexFallbackInfo
	6,  // 8: kaikosdk.StreamComputeIndexServiceResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	6,  // 9: kaikosdk.StreamComputeIndexServiceResponseV1.last_ingest_time:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sdk_stream_compute_index_v1_response_proto_init() }
func file_sdk_stream_compute_index_v1_response_proto_init() {
	if File_sdk_stream_compute_index_v1_response_proto != nil {
		return
	}
	file_sdk_stream_compute_index_v1_response_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_compute_index_v1_response_proto_rawDesc), len(file_sdk_stream_compute_index_v1_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_compute_index_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_compute_index_v1_response_proto_depIdxs,
		EnumInfos:         file_sdk_stream_compute_index_v1_response_proto_enumTypes,
		MessageInfos:      file_sdk_stream_compute_index_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_compute_index_v1_response_proto = out.File
	file_sdk_stream_compute_index_v1_response_proto_goTypes = nil
	file_sdk_stream_compute_index_v1_response_proto_depIdxs = nil
}
