// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/index_forex_rate_v1/response.proto

package index_forex_rate_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	index_v1 "github.com/kaikodata/kaiko-go-sdk/stream/index_v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamForexIndexPublic is public property involved in computation.
type StreamForexIndexPublic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// TSEvent.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamForexIndexPublic) Reset() {
	*x = StreamForexIndexPublic{}
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamForexIndexPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamForexIndexPublic) ProtoMessage() {}

func (x *StreamForexIndexPublic) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamForexIndexPublic.ProtoReflect.Descriptor instead.
func (*StreamForexIndexPublic) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_forex_rate_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamForexIndexPublic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamForexIndexPublic) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

// StreamForexIndexDetail is detail property involved in computation.
type StreamForexIndexDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Price
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// TSEvent.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamForexIndexDetail) Reset() {
	*x = StreamForexIndexDetail{}
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamForexIndexDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamForexIndexDetail) ProtoMessage() {}

func (x *StreamForexIndexDetail) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamForexIndexDetail.ProtoReflect.Descriptor instead.
func (*StreamForexIndexDetail) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_forex_rate_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *StreamForexIndexDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamForexIndexDetail) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamForexIndexDetail) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

// StreamForexIndexServiceResponseDetail is detail property involved in computation.
type StreamForexIndexServiceResponseDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Underlying.
	Underlying *StreamForexIndexDetail `protobuf:"bytes,1,opt,name=underlying,proto3" json:"underlying,omitempty"`
	// FxRate.
	Fxrate        *StreamForexIndexDetail `protobuf:"bytes,2,opt,name=fxrate,proto3" json:"fxrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamForexIndexServiceResponseDetail) Reset() {
	*x = StreamForexIndexServiceResponseDetail{}
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamForexIndexServiceResponseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamForexIndexServiceResponseDetail) ProtoMessage() {}

func (x *StreamForexIndexServiceResponseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamForexIndexServiceResponseDetail.ProtoReflect.Descriptor instead.
func (*StreamForexIndexServiceResponseDetail) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_forex_rate_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *StreamForexIndexServiceResponseDetail) GetUnderlying() *StreamForexIndexDetail {
	if x != nil {
		return x.Underlying
	}
	return nil
}

func (x *StreamForexIndexServiceResponseDetail) GetFxrate() *StreamForexIndexDetail {
	if x != nil {
		return x.Fxrate
	}
	return nil
}

// StreamForexIndexServiceResponsePublic is public property involved in computation.
type StreamForexIndexServiceResponsePublic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Underlying.
	Underlying *StreamForexIndexPublic `protobuf:"bytes,1,opt,name=underlying,proto3" json:"underlying,omitempty"`
	// FxRate.
	Fxrate        *StreamForexIndexPublic `protobuf:"bytes,2,opt,name=fxrate,proto3" json:"fxrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamForexIndexServiceResponsePublic) Reset() {
	*x = StreamForexIndexServiceResponsePublic{}
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamForexIndexServiceResponsePublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamForexIndexServiceResponsePublic) ProtoMessage() {}

func (x *StreamForexIndexServiceResponsePublic) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamForexIndexServiceResponsePublic.ProtoReflect.Descriptor instead.
func (*StreamForexIndexServiceResponsePublic) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_forex_rate_v1_response_proto_rawDescGZIP(), []int{3}
}

func (x *StreamForexIndexServiceResponsePublic) GetUnderlying() *StreamForexIndexPublic {
	if x != nil {
		return x.Underlying
	}
	return nil
}

func (x *StreamForexIndexServiceResponsePublic) GetFxrate() *StreamForexIndexPublic {
	if x != nil {
		return x.Fxrate
	}
	return nil
}

// StreamIndexForexRateServiceResponseV1
type StreamIndexForexRateServiceResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index code.
	IndexCode string `protobuf:"bytes,1,opt,name=index_code,json=indexCode,proto3" json:"index_code,omitempty"`
	// Event type.
	Commodity index_v1.StreamIndexCommodity `protobuf:"varint,2,opt,name=commodity,proto3,enum=kaikosdk.StreamIndexCommodity" json:"commodity,omitempty"`
	// Data interval.
	Interval *core.DataInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// Coimposition of the forex rate.
	Composition *StreamForexIndexServiceResponsePublic `protobuf:"bytes,4,opt,name=composition,proto3" json:"composition,omitempty"`
	// Price.
	Price float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	// TSEvent
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	// Detail property.
	Detail        *StreamForexIndexServiceResponseDetail `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIndexForexRateServiceResponseV1) Reset() {
	*x = StreamIndexForexRateServiceResponseV1{}
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexForexRateServiceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexForexRateServiceResponseV1) ProtoMessage() {}

func (x *StreamIndexForexRateServiceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexForexRateServiceResponseV1.ProtoReflect.Descriptor instead.
func (*StreamIndexForexRateServiceResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_index_forex_rate_v1_response_proto_rawDescGZIP(), []int{4}
}

func (x *StreamIndexForexRateServiceResponseV1) GetIndexCode() string {
	if x != nil {
		return x.IndexCode
	}
	return ""
}

func (x *StreamIndexForexRateServiceResponseV1) GetCommodity() index_v1.StreamIndexCommodity {
	if x != nil {
		return x.Commodity
	}
	return index_v1.StreamIndexCommodity(0)
}

func (x *StreamIndexForexRateServiceResponseV1) GetInterval() *core.DataInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *StreamIndexForexRateServiceResponseV1) GetComposition() *StreamForexIndexServiceResponsePublic {
	if x != nil {
		return x.Composition
	}
	return nil
}

func (x *StreamIndexForexRateServiceResponseV1) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamIndexForexRateServiceResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

func (x *StreamIndexForexRateServiceResponseV1) GetDetail() *StreamForexIndexServiceResponseDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

var File_sdk_stream_index_forex_rate_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_index_forex_rate_v1_response_proto_rawDesc = "" +
	"\n" +
	"-sdk/stream/index_forex_rate_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1csdk/core/data_interval.proto\x1a#sdk/stream/index_v1/commodity.proto\"c\n" +
	"\x16StreamForexIndexPublic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\bts_event\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\"y\n" +
	"\x16StreamForexIndexDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x125\n" +
	"\bts_event\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\"\xa3\x01\n" +
	"%StreamForexIndexServiceResponseDetail\x12@\n" +
	"\n" +
	"underlying\x18\x01 \x01(\v2 .kaikosdk.StreamForexIndexDetailR\n" +
	"underlying\x128\n" +
	"\x06fxrate\x18\x02 \x01(\v2 .kaikosdk.StreamForexIndexDetailR\x06fxrate\"\xa3\x01\n" +
	"%StreamForexIndexServiceResponsePublic\x12@\n" +
	"\n" +
	"underlying\x18\x01 \x01(\v2 .kaikosdk.StreamForexIndexPublicR\n" +
	"underlying\x128\n" +
	"\x06fxrate\x18\x02 \x01(\v2 .kaikosdk.StreamForexIndexPublicR\x06fxrate\"\xa1\x03\n" +
	"%StreamIndexForexRateServiceResponseV1\x12\x1d\n" +
	"\n" +
	"index_code\x18\x01 \x01(\tR\tindexCode\x12<\n" +
	"\tcommodity\x18\x02 \x01(\x0e2\x1e.kaikosdk.StreamIndexCommodityR\tcommodity\x122\n" +
	"\binterval\x18\x03 \x01(\v2\x16.kaikosdk.DataIntervalR\binterval\x12Q\n" +
	"\vcomposition\x18\x04 \x01(\v2/.kaikosdk.StreamForexIndexServiceResponsePublicR\vcomposition\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x125\n" +
	"\bts_event\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x12G\n" +
	"\x06detail\x18\a \x01(\v2/.kaikosdk.StreamForexIndexServiceResponseDetailR\x06detailB\xa1\x01\n" +
	"(com.kaiko.sdk.stream.index_forex_rate_v1P\x01ZPgithub.com/kaikodata/kaiko-go-sdk/stream/index_forex_rate_v1;index_forex_rate_v1\xaa\x02 KaikoSdk.Stream.IndexForexRateV1b\x06proto3"

var (
	file_sdk_stream_index_forex_rate_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_index_forex_rate_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_index_forex_rate_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_index_forex_rate_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_index_forex_rate_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_index_forex_rate_v1_response_proto_rawDesc), len(file_sdk_stream_index_forex_rate_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_index_forex_rate_v1_response_proto_rawDescData
}

var file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sdk_stream_index_forex_rate_v1_response_proto_goTypes = []any{
	(*StreamForexIndexPublic)(nil),                // 0: kaikosdk.StreamForexIndexPublic
	(*StreamForexIndexDetail)(nil),                // 1: kaikosdk.StreamForexIndexDetail
	(*StreamForexIndexServiceResponseDetail)(nil), // 2: kaikosdk.StreamForexIndexServiceResponseDetail
	(*StreamForexIndexServiceResponsePublic)(nil), // 3: kaikosdk.StreamForexIndexServiceResponsePublic
	(*StreamIndexForexRateServiceResponseV1)(nil), // 4: kaikosdk.StreamIndexForexRateServiceResponseV1
	(*timestamppb.Timestamp)(nil),                 // 5: google.protobuf.Timestamp
	(index_v1.StreamIndexCommodity)(0),            // 6: kaikosdk.StreamIndexCommodity
	(*core.DataInterval)(nil),                     // 7: kaikosdk.DataInterval
}
var file_sdk_stream_index_forex_rate_v1_response_proto_depIdxs = []int32{
	5,  // 0: kaikosdk.StreamForexIndexPublic.ts_event:type_name -> google.protobuf.Timestamp
	5,  // 1: kaikosdk.StreamForexIndexDetail.ts_event:type_name -> google.protobuf.Timestamp
	1,  // 2: kaikosdk.StreamForexIndexServiceResponseDetail.underlying:type_name -> kaikosdk.StreamForexIndexDetail
	1,  // 3: kaikosdk.StreamForexIndexServiceResponseDetail.fxrate:type_name -> kaikosdk.StreamForexIndexDetail
	0,  // 4: kaikosdk.StreamForexIndexServiceResponsePublic.underlying:type_name -> kaikosdk.StreamForexIndexPublic
	0,  // 5: kaikosdk.StreamForexIndexServiceResponsePublic.fxrate:type_name -> kaikosdk.StreamForexIndexPublic
	6,  // 6: kaikosdk.StreamIndexForexRateServiceResponseV1.commodity:type_name -> kaikosdk.StreamIndexCommodity
	7,  // 7: kaikosdk.StreamIndexForexRateServiceResponseV1.interval:type_name -> kaikosdk.DataInterval
	3,  // 8: kaikosdk.StreamIndexForexRateServiceResponseV1.composition:type_name -> kaikosdk.StreamForexIndexServiceResponsePublic
	5,  // 9: kaikosdk.StreamIndexForexRateServiceResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	2,  // 10: kaikosdk.StreamIndexForexRateServiceResponseV1.detail:type_name -> kaikosdk.StreamForexIndexServiceResponseDetail
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sdk_stream_index_forex_rate_v1_response_proto_init() }
func file_sdk_stream_index_forex_rate_v1_response_proto_init() {
	if File_sdk_stream_index_forex_rate_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_index_forex_rate_v1_response_proto_rawDesc), len(file_sdk_stream_index_forex_rate_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_index_forex_rate_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_index_forex_rate_v1_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_index_forex_rate_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_index_forex_rate_v1_response_proto = out.File
	file_sdk_stream_index_forex_rate_v1_response_proto_goTypes = nil
	file_sdk_stream_index_forex_rate_v1_response_proto_depIdxs = nil
}
