// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/aggregates_spot_exchange_rate_v2/response.proto

package aggregates_spot_exchange_rate_v2

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamAggregatesSpotExchangeRateV2ResponseV1
type StreamAggregatesSpotExchangeRateV2ResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sliding Window (duration string, ex: 1m).
	Assets *core.Assets `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
	// Price for the trade.
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// Timestamp of event.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Window information.
	Window *core.Window `protobuf:"bytes,4,opt,name=window,proto3" json:"window,omitempty"`
	// NoTrade: no trade happened during the window.
	NoTrade       bool `protobuf:"varint,5,opt,name=no_trade,json=noTrade,proto3" json:"no_trade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAggregatesSpotExchangeRateV2ResponseV1) Reset() {
	*x = StreamAggregatesSpotExchangeRateV2ResponseV1{}
	mi := &file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatesSpotExchangeRateV2ResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatesSpotExchangeRateV2ResponseV1) ProtoMessage() {}

func (x *StreamAggregatesSpotExchangeRateV2ResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatesSpotExchangeRateV2ResponseV1.ProtoReflect.Descriptor instead.
func (*StreamAggregatesSpotExchangeRateV2ResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAggregatesSpotExchangeRateV2ResponseV1) GetAssets() *core.Assets {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *StreamAggregatesSpotExchangeRateV2ResponseV1) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamAggregatesSpotExchangeRateV2ResponseV1) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StreamAggregatesSpotExchangeRateV2ResponseV1) GetWindow() *core.Window {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *StreamAggregatesSpotExchangeRateV2ResponseV1) GetNoTrade() bool {
	if x != nil {
		return x.NoTrade
	}
	return false
}

var File_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto protoreflect.FileDescriptor

const file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDesc = "" +
	"\n" +
	":sdk/stream/aggregates_spot_exchange_rate_v2/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15sdk/core/assets.proto\x1a\x15sdk/core/window.proto\"\xed\x01\n" +
	",StreamAggregatesSpotExchangeRateV2ResponseV1\x12(\n" +
	"\x06assets\x18\x01 \x01(\v2\x10.kaikosdk.AssetsR\x06assets\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\x06window\x18\x04 \x01(\v2\x10.kaikosdk.WindowR\x06window\x12\x19\n" +
	"\bno_trade\x18\x05 \x01(\bR\anoTradeB\xd4\x01\n" +
	"5com.kaiko.sdk.stream.aggregates_spot_exchange_rate_v2P\x01Zjgithub.com/kaikodata/kaiko-go-sdk/stream/aggregates_spot_exchange_rate_v2;aggregates_spot_exchange_rate_v2\xaa\x02,KaikoSdk.Stream.AggregatesSpotExchangeRateV2b\x06proto3"

var (
	file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDescOnce sync.Once
	file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDescData []byte
)

func file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDesc), len(file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDesc)))
	})
	return file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDescData
}

var file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_goTypes = []any{
	(*StreamAggregatesSpotExchangeRateV2ResponseV1)(nil), // 0: kaikosdk.StreamAggregatesSpotExchangeRateV2ResponseV1
	(*core.Assets)(nil),           // 1: kaikosdk.Assets
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*core.Window)(nil),           // 3: kaikosdk.Window
}
var file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamAggregatesSpotExchangeRateV2ResponseV1.assets:type_name -> kaikosdk.Assets
	2, // 1: kaikosdk.StreamAggregatesSpotExchangeRateV2ResponseV1.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: kaikosdk.StreamAggregatesSpotExchangeRateV2ResponseV1.window:type_name -> kaikosdk.Window
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_init() }
func file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_init() {
	if File_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDesc), len(file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto = out.File
	file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_goTypes = nil
	file_sdk_stream_aggregates_spot_exchange_rate_v2_response_proto_depIdxs = nil
}
