// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/orderbookl2_v1/request.proto

package orderbookl2_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamOrderBookL2RequestV1 is the request message for the orderbook L2 stream.
type StreamOrderBookL2RequestV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InstrumentCriteria is instrument exchange, class and code, wildcard (*) can be used.
	InstrumentCriteria *core.InstrumentCriteria `protobuf:"bytes,1,opt,name=instrument_criteria,json=instrumentCriteria,proto3" json:"instrument_criteria,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamOrderBookL2RequestV1) Reset() {
	*x = StreamOrderBookL2RequestV1{}
	mi := &file_sdk_stream_orderbookl2_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderBookL2RequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderBookL2RequestV1) ProtoMessage() {}

func (x *StreamOrderBookL2RequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_orderbookl2_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderBookL2RequestV1.ProtoReflect.Descriptor instead.
func (*StreamOrderBookL2RequestV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_orderbookl2_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *StreamOrderBookL2RequestV1) GetInstrumentCriteria() *core.InstrumentCriteria {
	if x != nil {
		return x.InstrumentCriteria
	}
	return nil
}

// StreamOrderBookL2ReplayRequestV1 is the request message for the orderbook L2 stream.
type StreamOrderBookL2ReplayRequestV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InstrumentCriteria is instrument exchange, class and code, wildcard (*) can be used.
	InstrumentCriteria *core.InstrumentCriteria `protobuf:"bytes,1,opt,name=instrument_criteria,json=instrumentCriteria,proto3" json:"instrument_criteria,omitempty"`
	// Data interval for replay data.
	Interval      *core.DataInterval `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderBookL2ReplayRequestV1) Reset() {
	*x = StreamOrderBookL2ReplayRequestV1{}
	mi := &file_sdk_stream_orderbookl2_v1_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderBookL2ReplayRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderBookL2ReplayRequestV1) ProtoMessage() {}

func (x *StreamOrderBookL2ReplayRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_orderbookl2_v1_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderBookL2ReplayRequestV1.ProtoReflect.Descriptor instead.
func (*StreamOrderBookL2ReplayRequestV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_orderbookl2_v1_request_proto_rawDescGZIP(), []int{1}
}

func (x *StreamOrderBookL2ReplayRequestV1) GetInstrumentCriteria() *core.InstrumentCriteria {
	if x != nil {
		return x.InstrumentCriteria
	}
	return nil
}

func (x *StreamOrderBookL2ReplayRequestV1) GetInterval() *core.DataInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_sdk_stream_orderbookl2_v1_request_proto protoreflect.FileDescriptor

const file_sdk_stream_orderbookl2_v1_request_proto_rawDesc = "" +
	"\n" +
	"'sdk/stream/orderbookl2_v1/request.proto\x12\bkaikosdk\x1a\x1csdk/core/data_interval.proto\x1a\"sdk/core/instrument_criteria.proto\"k\n" +
	"\x1aStreamOrderBookL2RequestV1\x12M\n" +
	"\x13instrument_criteria\x18\x01 \x01(\v2\x1c.kaikosdk.InstrumentCriteriaR\x12instrumentCriteria\"\xa5\x01\n" +
	" StreamOrderBookL2ReplayRequestV1\x12M\n" +
	"\x13instrument_criteria\x18\x01 \x01(\v2\x1c.kaikosdk.InstrumentCriteriaR\x12instrumentCriteria\x122\n" +
	"\binterval\x18\x02 \x01(\v2\x16.kaikosdk.DataIntervalR\bintervalB\x8d\x01\n" +
	"#com.kaiko.sdk.stream.orderbookl2_v1P\x01ZFgithub.com/kaikodata/kaiko-go-sdk/stream/orderbookl2_v1;orderbookl2_v1\xaa\x02\x1bKaikoSdk.Stream.OrderBookL2b\x06proto3"

var (
	file_sdk_stream_orderbookl2_v1_request_proto_rawDescOnce sync.Once
	file_sdk_stream_orderbookl2_v1_request_proto_rawDescData []byte
)

func file_sdk_stream_orderbookl2_v1_request_proto_rawDescGZIP() []byte {
	file_sdk_stream_orderbookl2_v1_request_proto_rawDescOnce.Do(func() {
		file_sdk_stream_orderbookl2_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_orderbookl2_v1_request_proto_rawDesc), len(file_sdk_stream_orderbookl2_v1_request_proto_rawDesc)))
	})
	return file_sdk_stream_orderbookl2_v1_request_proto_rawDescData
}

var file_sdk_stream_orderbookl2_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_stream_orderbookl2_v1_request_proto_goTypes = []any{
	(*StreamOrderBookL2RequestV1)(nil),       // 0: kaikosdk.StreamOrderBookL2RequestV1
	(*StreamOrderBookL2ReplayRequestV1)(nil), // 1: kaikosdk.StreamOrderBookL2ReplayRequestV1
	(*core.InstrumentCriteria)(nil),          // 2: kaikosdk.InstrumentCriteria
	(*core.DataInterval)(nil),                // 3: kaikosdk.DataInterval
}
var file_sdk_stream_orderbookl2_v1_request_proto_depIdxs = []int32{
	2, // 0: kaikosdk.StreamOrderBookL2RequestV1.instrument_criteria:type_name -> kaikosdk.InstrumentCriteria
	2, // 1: kaikosdk.StreamOrderBookL2ReplayRequestV1.instrument_criteria:type_name -> kaikosdk.InstrumentCriteria
	3, // 2: kaikosdk.StreamOrderBookL2ReplayRequestV1.interval:type_name -> kaikosdk.DataInterval
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sdk_stream_orderbookl2_v1_request_proto_init() }
func file_sdk_stream_orderbookl2_v1_request_proto_init() {
	if File_sdk_stream_orderbookl2_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_orderbookl2_v1_request_proto_rawDesc), len(file_sdk_stream_orderbookl2_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_orderbookl2_v1_request_proto_goTypes,
		DependencyIndexes: file_sdk_stream_orderbookl2_v1_request_proto_depIdxs,
		MessageInfos:      file_sdk_stream_orderbookl2_v1_request_proto_msgTypes,
	}.Build()
	File_sdk_stream_orderbookl2_v1_request_proto = out.File
	file_sdk_stream_orderbookl2_v1_request_proto_goTypes = nil
	file_sdk_stream_orderbookl2_v1_request_proto_depIdxs = nil
}
