// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/orderbookl2_v1/response.proto

package orderbookl2_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamOrderBookL2UpdateType is the type of an order book event.
type StreamOrderBookL2UpdateType int32

const (
	// Unknown type.
	StreamOrderBookL2UpdateType_UNKNOWN StreamOrderBookL2UpdateType = 0
	// Order book snapshot.
	StreamOrderBookL2UpdateType_SNAPSHOT StreamOrderBookL2UpdateType = 1
	// Order book update.
	StreamOrderBookL2UpdateType_UPDATE StreamOrderBookL2UpdateType = 2
)

// Enum value maps for StreamOrderBookL2UpdateType.
var (
	StreamOrderBookL2UpdateType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SNAPSHOT",
		2: "UPDATE",
	}
	StreamOrderBookL2UpdateType_value = map[string]int32{
		"UNKNOWN":  0,
		"SNAPSHOT": 1,
		"UPDATE":   2,
	}
)

func (x StreamOrderBookL2UpdateType) Enum() *StreamOrderBookL2UpdateType {
	p := new(StreamOrderBookL2UpdateType)
	*p = x
	return p
}

func (x StreamOrderBookL2UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamOrderBookL2UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_orderbookl2_v1_response_proto_enumTypes[0].Descriptor()
}

func (StreamOrderBookL2UpdateType) Type() protoreflect.EnumType {
	return &file_sdk_stream_orderbookl2_v1_response_proto_enumTypes[0]
}

func (x StreamOrderBookL2UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamOrderBookL2UpdateType.Descriptor instead.
func (StreamOrderBookL2UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_orderbookl2_v1_response_proto_rawDescGZIP(), []int{0}
}

// StreamOrderBookL2ResponseV1 is the response of a Level 2 order book event.
type StreamOrderBookL2ResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument class, for example "spot".
	Class string `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	// Instrument code (currency pair), for example btc-usd.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Instrument exchange code, for example "cbse" (Coinbase).
	Exchange string `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Sequence ID for event. Sortable in lexicographic order.
	SequenceId string `protobuf:"bytes,4,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	// Event type.
	UpdateType StreamOrderBookL2UpdateType `protobuf:"varint,5,opt,name=update_type,json=updateType,proto3,enum=kaikosdk.StreamOrderBookL2UpdateType" json:"update_type,omitempty"`
	// Asks is the list of asks of the orderbook.
	Asks []*Order `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
	// Bids is the list of bids of the orderbook.
	Bids []*Order `protobuf:"bytes,7,rep,name=bids,proto3" json:"bids,omitempty"`
	// Timestamp of the event as provided by the exchange.
	TsExchange *core.TimestampValue `protobuf:"bytes,8,opt,name=ts_exchange,json=tsExchange,proto3" json:"ts_exchange,omitempty"`
	// Timestamp of collection (event entered Kaiko's infrastructure), before nomalization.
	TsCollection *core.TimestampValue `protobuf:"bytes,9,opt,name=ts_collection,json=tsCollection,proto3" json:"ts_collection,omitempty"`
	// Event generation timestamp (event created by Kaiko), after normalization.
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	// Additionnal properties, specific to the exchange.
	AdditionalProperties map[string]string `protobuf:"bytes,11,rep,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StreamOrderBookL2ResponseV1) Reset() {
	*x = StreamOrderBookL2ResponseV1{}
	mi := &file_sdk_stream_orderbookl2_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderBookL2ResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderBookL2ResponseV1) ProtoMessage() {}

func (x *StreamOrderBookL2ResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_orderbookl2_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderBookL2ResponseV1.ProtoReflect.Descriptor instead.
func (*StreamOrderBookL2ResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_orderbookl2_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamOrderBookL2ResponseV1) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *StreamOrderBookL2ResponseV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamOrderBookL2ResponseV1) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StreamOrderBookL2ResponseV1) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *StreamOrderBookL2ResponseV1) GetUpdateType() StreamOrderBookL2UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return StreamOrderBookL2UpdateType_UNKNOWN
}

func (x *StreamOrderBookL2ResponseV1) GetAsks() []*Order {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *StreamOrderBookL2ResponseV1) GetBids() []*Order {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *StreamOrderBookL2ResponseV1) GetTsExchange() *core.TimestampValue {
	if x != nil {
		return x.TsExchange
	}
	return nil
}

func (x *StreamOrderBookL2ResponseV1) GetTsCollection() *core.TimestampValue {
	if x != nil {
		return x.TsCollection
	}
	return nil
}

func (x *StreamOrderBookL2ResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

func (x *StreamOrderBookL2ResponseV1) GetAdditionalProperties() map[string]string {
	if x != nil {
		return x.AdditionalProperties
	}
	return nil
}

var File_sdk_stream_orderbookl2_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_orderbookl2_v1_response_proto_rawDesc = "" +
	"\n" +
	"(sdk/stream/orderbookl2_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17sdk/core/wrappers.proto\x1a%sdk/stream/orderbookl2_v1/order.proto\"\x86\x05\n" +
	"\x1bStreamOrderBookL2ResponseV1\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x1f\n" +
	"\vsequence_id\x18\x04 \x01(\tR\n" +
	"sequenceId\x12F\n" +
	"\vupdate_type\x18\x05 \x01(\x0e2%.kaikosdk.StreamOrderBookL2UpdateTypeR\n" +
	"updateType\x12#\n" +
	"\x04asks\x18\x06 \x03(\v2\x0f.kaikosdk.OrderR\x04asks\x12#\n" +
	"\x04bids\x18\a \x03(\v2\x0f.kaikosdk.OrderR\x04bids\x129\n" +
	"\vts_exchange\x18\b \x01(\v2\x18.kaikosdk.TimestampValueR\n" +
	"tsExchange\x12=\n" +
	"\rts_collection\x18\t \x01(\v2\x18.kaikosdk.TimestampValueR\ftsCollection\x125\n" +
	"\bts_event\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x12t\n" +
	"\x15additional_properties\x18\v \x03(\v2?.kaikosdk.StreamOrderBookL2ResponseV1.AdditionalPropertiesEntryR\x14additionalProperties\x1aG\n" +
	"\x19AdditionalPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*D\n" +
	"\x1bStreamOrderBookL2UpdateType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bSNAPSHOT\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02B\x8f\x01\n" +
	"#com.kaiko.sdk.stream.orderbookl2_v1P\x01ZFgithub.com/kaikodata/kaiko-go-sdk/stream/orderbookl2_v1;orderbookl2_v1\xaa\x02\x1dKaikoSdk.Stream.OrderBookL2V1b\x06proto3"

var (
	file_sdk_stream_orderbookl2_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_orderbookl2_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_orderbookl2_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_orderbookl2_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_orderbookl2_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_orderbookl2_v1_response_proto_rawDesc), len(file_sdk_stream_orderbookl2_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_orderbookl2_v1_response_proto_rawDescData
}

var file_sdk_stream_orderbookl2_v1_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_orderbookl2_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_stream_orderbookl2_v1_response_proto_goTypes = []any{
	(StreamOrderBookL2UpdateType)(0),    // 0: kaikosdk.StreamOrderBookL2UpdateType
	(*StreamOrderBookL2ResponseV1)(nil), // 1: kaikosdk.StreamOrderBookL2ResponseV1
	nil,                                 // 2: kaikosdk.StreamOrderBookL2ResponseV1.AdditionalPropertiesEntry
	(*Order)(nil),                       // 3: kaikosdk.Order
	(*core.TimestampValue)(nil),         // 4: kaikosdk.TimestampValue
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_sdk_stream_orderbookl2_v1_response_proto_depIdxs = []int32{
	0, // 0: kaikosdk.StreamOrderBookL2ResponseV1.update_type:type_name -> kaikosdk.StreamOrderBookL2UpdateType
	3, // 1: kaikosdk.StreamOrderBookL2ResponseV1.asks:type_name -> kaikosdk.Order
	3, // 2: kaikosdk.StreamOrderBookL2ResponseV1.bids:type_name -> kaikosdk.Order
	4, // 3: kaikosdk.StreamOrderBookL2ResponseV1.ts_exchange:type_name -> kaikosdk.TimestampValue
	4, // 4: kaikosdk.StreamOrderBookL2ResponseV1.ts_collection:type_name -> kaikosdk.TimestampValue
	5, // 5: kaikosdk.StreamOrderBookL2ResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	2, // 6: kaikosdk.StreamOrderBookL2ResponseV1.additional_properties:type_name -> kaikosdk.StreamOrderBookL2ResponseV1.AdditionalPropertiesEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sdk_stream_orderbookl2_v1_response_proto_init() }
func file_sdk_stream_orderbookl2_v1_response_proto_init() {
	if File_sdk_stream_orderbookl2_v1_response_proto != nil {
		return
	}
	file_sdk_stream_orderbookl2_v1_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_orderbookl2_v1_response_proto_rawDesc), len(file_sdk_stream_orderbookl2_v1_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_orderbookl2_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_orderbookl2_v1_response_proto_depIdxs,
		EnumInfos:         file_sdk_stream_orderbookl2_v1_response_proto_enumTypes,
		MessageInfos:      file_sdk_stream_orderbookl2_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_orderbookl2_v1_response_proto = out.File
	file_sdk_stream_orderbookl2_v1_response_proto_goTypes = nil
	file_sdk_stream_orderbookl2_v1_response_proto_depIdxs = nil
}
