// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/trades_v1/request.proto

package trades_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamTradesRequestV1
type StreamTradesRequestV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InstrumentCriteria is instrument exchange, class and code, wildcard (*) can be used.
	InstrumentCriteria *core.InstrumentCriteria `protobuf:"bytes,1,opt,name=instrument_criteria,json=instrumentCriteria,proto3" json:"instrument_criteria,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamTradesRequestV1) Reset() {
	*x = StreamTradesRequestV1{}
	mi := &file_sdk_stream_trades_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTradesRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTradesRequestV1) ProtoMessage() {}

func (x *StreamTradesRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_trades_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTradesRequestV1.ProtoReflect.Descriptor instead.
func (*StreamTradesRequestV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_trades_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *StreamTradesRequestV1) GetInstrumentCriteria() *core.InstrumentCriteria {
	if x != nil {
		return x.InstrumentCriteria
	}
	return nil
}

var File_sdk_stream_trades_v1_request_proto protoreflect.FileDescriptor

const file_sdk_stream_trades_v1_request_proto_rawDesc = "" +
	"\n" +
	"\"sdk/stream/trades_v1/request.proto\x12\bkaikosdk\x1a\"sdk/core/instrument_criteria.proto\"f\n" +
	"\x15StreamTradesRequestV1\x12M\n" +
	"\x13instrument_criteria\x18\x01 \x01(\v2\x1c.kaikosdk.InstrumentCriteriaR\x12instrumentCriteriaB{\n" +
	"\x1ecom.kaiko.sdk.stream.trades_v1P\x01Z<github.com/kaikodata/kaiko-go-sdk/stream/trades_v1;trades_v1\xaa\x02\x18KaikoSdk.Stream.TradesV1b\x06proto3"

var (
	file_sdk_stream_trades_v1_request_proto_rawDescOnce sync.Once
	file_sdk_stream_trades_v1_request_proto_rawDescData []byte
)

func file_sdk_stream_trades_v1_request_proto_rawDescGZIP() []byte {
	file_sdk_stream_trades_v1_request_proto_rawDescOnce.Do(func() {
		file_sdk_stream_trades_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_trades_v1_request_proto_rawDesc), len(file_sdk_stream_trades_v1_request_proto_rawDesc)))
	})
	return file_sdk_stream_trades_v1_request_proto_rawDescData
}

var file_sdk_stream_trades_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_stream_trades_v1_request_proto_goTypes = []any{
	(*StreamTradesRequestV1)(nil),   // 0: kaikosdk.StreamTradesRequestV1
	(*core.InstrumentCriteria)(nil), // 1: kaikosdk.InstrumentCriteria
}
var file_sdk_stream_trades_v1_request_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamTradesRequestV1.instrument_criteria:type_name -> kaikosdk.InstrumentCriteria
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_stream_trades_v1_request_proto_init() }
func file_sdk_stream_trades_v1_request_proto_init() {
	if File_sdk_stream_trades_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_trades_v1_request_proto_rawDesc), len(file_sdk_stream_trades_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_trades_v1_request_proto_goTypes,
		DependencyIndexes: file_sdk_stream_trades_v1_request_proto_depIdxs,
		MessageInfos:      file_sdk_stream_trades_v1_request_proto_msgTypes,
	}.Build()
	File_sdk_stream_trades_v1_request_proto = out.File
	file_sdk_stream_trades_v1_request_proto_goTypes = nil
	file_sdk_stream_trades_v1_request_proto_depIdxs = nil
}
