// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/trades_v1/response.proto

package trades_v1

import (
	core "github.com/kaikodata/kaiko-go-sdk/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side
type StreamTradesResponseV1_TradeSide int32

const (
	// Unknown side (not specified).
	StreamTradesResponseV1_UNKNOWN StreamTradesResponseV1_TradeSide = 0
	// Buy side.
	StreamTradesResponseV1_BUY StreamTradesResponseV1_TradeSide = 1
	// Sell side.
	StreamTradesResponseV1_SELL StreamTradesResponseV1_TradeSide = 2
)

// Enum value maps for StreamTradesResponseV1_TradeSide.
var (
	StreamTradesResponseV1_TradeSide_name = map[int32]string{
		0: "UNKNOWN",
		1: "BUY",
		2: "SELL",
	}
	StreamTradesResponseV1_TradeSide_value = map[string]int32{
		"UNKNOWN": 0,
		"BUY":     1,
		"SELL":    2,
	}
)

func (x StreamTradesResponseV1_TradeSide) Enum() *StreamTradesResponseV1_TradeSide {
	p := new(StreamTradesResponseV1_TradeSide)
	*p = x
	return p
}

func (x StreamTradesResponseV1_TradeSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamTradesResponseV1_TradeSide) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_stream_trades_v1_response_proto_enumTypes[0].Descriptor()
}

func (StreamTradesResponseV1_TradeSide) Type() protoreflect.EnumType {
	return &file_sdk_stream_trades_v1_response_proto_enumTypes[0]
}

func (x StreamTradesResponseV1_TradeSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamTradesResponseV1_TradeSide.Descriptor instead.
func (StreamTradesResponseV1_TradeSide) EnumDescriptor() ([]byte, []int) {
	return file_sdk_stream_trades_v1_response_proto_rawDescGZIP(), []int{0, 0}
}

// StreamTradesResponseV1
type StreamTradesResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Additionnal properties, specific to the exchange.
	AdditionalProperties map[string]string `protobuf:"bytes,1,rep,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Amount / quantity of asset bought or sold, displayed in base currency.
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Instrument class, empty when instrument not mapped.
	Class string `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	// Instrument code, empty when instrument not mapped.
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// Instrument exchange code, for example "cbse" (Coinbase).
	Exchange string `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Sequence ID for event. Sortable in lexicographic order.
	SequenceId string `protobuf:"bytes,6,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	// Trade ID, empty string when not present.
	Id string `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	// Price for the trade.
	Price float64 `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	// Trade side.
	Side StreamTradesResponseV1_TradeSide `protobuf:"varint,9,opt,name=side,proto3,enum=kaikosdk.StreamTradesResponseV1_TradeSide" json:"side,omitempty"`
	// Timestamp of trade, when provided by the exchange.
	TsExchange *core.TimestampValue `protobuf:"bytes,10,opt,name=ts_exchange,json=tsExchange,proto3" json:"ts_exchange,omitempty"`
	// Timestamp of collection (event entered Kaiko's infrastructure), before nomalization.
	TsCollection *core.TimestampValue `protobuf:"bytes,11,opt,name=ts_collection,json=tsCollection,proto3" json:"ts_collection,omitempty"`
	// Event generation timestamp (event created by Kaiko), after normalization.
	TsEvent       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTradesResponseV1) Reset() {
	*x = StreamTradesResponseV1{}
	mi := &file_sdk_stream_trades_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTradesResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTradesResponseV1) ProtoMessage() {}

func (x *StreamTradesResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_trades_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTradesResponseV1.ProtoReflect.Descriptor instead.
func (*StreamTradesResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_trades_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamTradesResponseV1) GetAdditionalProperties() map[string]string {
	if x != nil {
		return x.AdditionalProperties
	}
	return nil
}

func (x *StreamTradesResponseV1) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StreamTradesResponseV1) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *StreamTradesResponseV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamTradesResponseV1) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StreamTradesResponseV1) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *StreamTradesResponseV1) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamTradesResponseV1) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamTradesResponseV1) GetSide() StreamTradesResponseV1_TradeSide {
	if x != nil {
		return x.Side
	}
	return StreamTradesResponseV1_UNKNOWN
}

func (x *StreamTradesResponseV1) GetTsExchange() *core.TimestampValue {
	if x != nil {
		return x.TsExchange
	}
	return nil
}

func (x *StreamTradesResponseV1) GetTsCollection() *core.TimestampValue {
	if x != nil {
		return x.TsCollection
	}
	return nil
}

func (x *StreamTradesResponseV1) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

var File_sdk_stream_trades_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_trades_v1_response_proto_rawDesc = "" +
	"\n" +
	"#sdk/stream/trades_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17sdk/core/wrappers.proto\"\x95\x05\n" +
	"\x16StreamTradesResponseV1\x12o\n" +
	"\x15additional_properties\x18\x01 \x03(\v2:.kaikosdk.StreamTradesResponseV1.AdditionalPropertiesEntryR\x14additionalProperties\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12\x1f\n" +
	"\vsequence_id\x18\x06 \x01(\tR\n" +
	"sequenceId\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12>\n" +
	"\x04side\x18\t \x01(\x0e2*.kaikosdk.StreamTradesResponseV1.TradeSideR\x04side\x129\n" +
	"\vts_exchange\x18\n" +
	" \x01(\v2\x18.kaikosdk.TimestampValueR\n" +
	"tsExchange\x12=\n" +
	"\rts_collection\x18\v \x01(\v2\x18.kaikosdk.TimestampValueR\ftsCollection\x125\n" +
	"\bts_event\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\atsEvent\x1aG\n" +
	"\x19AdditionalPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\tTradeSide\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02B{\n" +
	"\x1ecom.kaiko.sdk.stream.trades_v1P\x01Z<github.com/kaikodata/kaiko-go-sdk/stream/trades_v1;trades_v1\xaa\x02\x18KaikoSdk.Stream.TradesV1b\x06proto3"

var (
	file_sdk_stream_trades_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_trades_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_trades_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_trades_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_trades_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_trades_v1_response_proto_rawDesc), len(file_sdk_stream_trades_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_trades_v1_response_proto_rawDescData
}

var file_sdk_stream_trades_v1_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_stream_trades_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_stream_trades_v1_response_proto_goTypes = []any{
	(StreamTradesResponseV1_TradeSide)(0), // 0: kaikosdk.StreamTradesResponseV1.TradeSide
	(*StreamTradesResponseV1)(nil),        // 1: kaikosdk.StreamTradesResponseV1
	nil,                                   // 2: kaikosdk.StreamTradesResponseV1.AdditionalPropertiesEntry
	(*core.TimestampValue)(nil),           // 3: kaikosdk.TimestampValue
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
}
var file_sdk_stream_trades_v1_response_proto_depIdxs = []int32{
	2, // 0: kaikosdk.StreamTradesResponseV1.additional_properties:type_name -> kaikosdk.StreamTradesResponseV1.AdditionalPropertiesEntry
	0, // 1: kaikosdk.StreamTradesResponseV1.side:type_name -> kaikosdk.StreamTradesResponseV1.TradeSide
	3, // 2: kaikosdk.StreamTradesResponseV1.ts_exchange:type_name -> kaikosdk.TimestampValue
	3, // 3: kaikosdk.StreamTradesResponseV1.ts_collection:type_name -> kaikosdk.TimestampValue
	4, // 4: kaikosdk.StreamTradesResponseV1.ts_event:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sdk_stream_trades_v1_response_proto_init() }
func file_sdk_stream_trades_v1_response_proto_init() {
	if File_sdk_stream_trades_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_trades_v1_response_proto_rawDesc), len(file_sdk_stream_trades_v1_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_trades_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_trades_v1_response_proto_depIdxs,
		EnumInfos:         file_sdk_stream_trades_v1_response_proto_enumTypes,
		MessageInfos:      file_sdk_stream_trades_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_trades_v1_response_proto = out.File
	file_sdk_stream_trades_v1_response_proto_goTypes = nil
	file_sdk_stream_trades_v1_response_proto_depIdxs = nil
}
