// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/stream/aggregates_ohlcv_v1/response.proto

package aggregates_ohlcv_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamAggregatesOHLCVResponseV1
type StreamAggregatesOHLCVResponseV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregate (interval).
	Aggregate string `protobuf:"bytes,1,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	// Instrument class.
	Class string `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	// Close value of OHLCV.
	Close string `protobuf:"bytes,3,opt,name=close,proto3" json:"close,omitempty"`
	// Instrument exchange.
	Exchange string `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// High value of OHLCV.
	High string `protobuf:"bytes,5,opt,name=high,proto3" json:"high,omitempty"`
	// Low value of OHLCV.
	Low string `protobuf:"bytes,6,opt,name=low,proto3" json:"low,omitempty"`
	// Open value of OHLCV.
	Open string `protobuf:"bytes,7,opt,name=open,proto3" json:"open,omitempty"`
	// Sequence ID for event. Sortable in lexicographic order.
	SequenceId string `protobuf:"bytes,8,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	// Instrument code.
	Code string `protobuf:"bytes,9,opt,name=code,proto3" json:"code,omitempty"`
	// Timestamp of event.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// UID is timestamp truncated to interval of OHLCV.
	Uid string `protobuf:"bytes,11,opt,name=uid,proto3" json:"uid,omitempty"`
	// Volume of OHLCV.
	Volume        string `protobuf:"bytes,12,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAggregatesOHLCVResponseV1) Reset() {
	*x = StreamAggregatesOHLCVResponseV1{}
	mi := &file_sdk_stream_aggregates_ohlcv_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAggregatesOHLCVResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAggregatesOHLCVResponseV1) ProtoMessage() {}

func (x *StreamAggregatesOHLCVResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_stream_aggregates_ohlcv_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAggregatesOHLCVResponseV1.ProtoReflect.Descriptor instead.
func (*StreamAggregatesOHLCVResponseV1) Descriptor() ([]byte, []int) {
	return file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAggregatesOHLCVResponseV1) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StreamAggregatesOHLCVResponseV1) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *StreamAggregatesOHLCVResponseV1) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

var File_sdk_stream_aggregates_ohlcv_v1_response_proto protoreflect.FileDescriptor

const file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDesc = "" +
	"\n" +
	"-sdk/stream/aggregates_ohlcv_v1/response.proto\x12\bkaikosdk\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x02\n" +
	"\x1fStreamAggregatesOHLCVResponseV1\x12\x1c\n" +
	"\taggregate\x18\x01 \x01(\tR\taggregate\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x14\n" +
	"\x05close\x18\x03 \x01(\tR\x05close\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x12\n" +
	"\x04high\x18\x05 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\tR\x03low\x12\x12\n" +
	"\x04open\x18\a \x01(\tR\x04open\x12\x1f\n" +
	"\vsequence_id\x18\b \x01(\tR\n" +
	"sequenceId\x12\x12\n" +
	"\x04code\x18\t \x01(\tR\x04code\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03uid\x18\v \x01(\tR\x03uid\x12\x16\n" +
	"\x06volume\x18\f \x01(\tR\x06volumeB\xa2\x01\n" +
	"(com.kaiko.sdk.stream.aggregates_ohlcv_v1P\x01ZPgithub.com/kaikodata/kaiko-go-sdk/stream/aggregates_ohlcv_v1;aggregates_ohlcv_v1\xaa\x02!KaikoSdk.Stream.AggregatesOHLCVV1b\x06proto3"

var (
	file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDescOnce sync.Once
	file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDescData []byte
)

func file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDescGZIP() []byte {
	file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDescOnce.Do(func() {
		file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDesc), len(file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDesc)))
	})
	return file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDescData
}

var file_sdk_stream_aggregates_ohlcv_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_stream_aggregates_ohlcv_v1_response_proto_goTypes = []any{
	(*StreamAggregatesOHLCVResponseV1)(nil), // 0: kaikosdk.StreamAggregatesOHLCVResponseV1
	(*timestamppb.Timestamp)(nil),           // 1: google.protobuf.Timestamp
}
var file_sdk_stream_aggregates_ohlcv_v1_response_proto_depIdxs = []int32{
	1, // 0: kaikosdk.StreamAggregatesOHLCVResponseV1.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_stream_aggregates_ohlcv_v1_response_proto_init() }
func file_sdk_stream_aggregates_ohlcv_v1_response_proto_init() {
	if File_sdk_stream_aggregates_ohlcv_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDesc), len(file_sdk_stream_aggregates_ohlcv_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_stream_aggregates_ohlcv_v1_response_proto_goTypes,
		DependencyIndexes: file_sdk_stream_aggregates_ohlcv_v1_response_proto_depIdxs,
		MessageInfos:      file_sdk_stream_aggregates_ohlcv_v1_response_proto_msgTypes,
	}.Build()
	File_sdk_stream_aggregates_ohlcv_v1_response_proto = out.File
	file_sdk_stream_aggregates_ohlcv_v1_response_proto_goTypes = nil
	file_sdk_stream_aggregates_ohlcv_v1_response_proto_depIdxs = nil
}
